### ISSUE TITLE
Using JsonApiDotNetCore with another API as the data source?

### ISSUE THREAD

**Issue by gordsmash** [json-api-dotnet/JsonApiDotNetCore#1003]
We are using the JSON:API standard with the JsonApiDotNetCore package for our data. However, we will not be getting our data from SQL, but from a different API that we use internally.

With JsonApiDotNetCore, is it possible to use a different API as the data source rather than a SQL database as the data source? If so, is there an example project that implemented this?

Thanks.

**Comment by bkoelman** [comment]
Yes, this is documented at https://www.jsonapi.net/usage/extensibility/layer-overview.html. There's an example at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/Examples/NoEntityFrameworkExample.

**Comment by gordsmash** [comment]
Exactly what I needed, thanks!
