### ISSUE TITLE
Default Page Size and Pagination when using non-EF as data source.

### ISSUE THREAD

**Issue by gordsmash** [json-api-dotnet/JsonApiDotNetCore#1005]
Hello! I have my project setup to use a custom resource service that does not use Entity Framework as the data source. I am able to get data just fine with my custom resource service. However, I noticed that when using it, that the options in Json:API for page size/page numbers are no longer being enforced. I have my Startup.cs set as:
```
services.AddJsonApi(options =>
{
    options.SerializerSettings.ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new KebabCaseNamingStrategy()
    };
    options.DefaultPageSize = new PageSize(10);
    options.MaximumPageSize = new PageSize(50);
    options.MaximumPageNumber = null;
    options.IncludeTotalResourceCount = true;
}, resources: builder => builder.Add<MyResource, string>("my-resource"),
discovery: discovery => discovery.AddCurrentAssembly());
```
When doing a GET on my endpoint to return results, the data is formatted correctly, but the page size limit is not being enforced.

Since I am using a custom resource service for our data, does this mean I will also have to write custom code to handle page size/pagination for it?

Thank you.

**Comment by bart-degreed** [comment]
Yes, along with other things such as sorting, filtering, inclusions and sparse fieldsets. When using EF Core, those are turned into SQL, so it executes on the database server. It doesn't make sense to download millions of rows from the database first and then page/sort in memory. That does not scale.

To get parsed results from query string parameters, you can inject them and take them into account in your custom logic to fetch data.

**Comment by gordsmash** [comment]
Thanks Bart. I've been going over the documentation and code snippets on [jsonapi.net](https://www.jsonapi.net/) and also the [NoEntityFrameworkExample](https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/Examples/NoEntityFrameworkExample) example here on github to get an idea of what is required to get a custom resource service up and running completely. 

To make sure I'm heading in the right direction for implementing this, and based on what I'm seeing, the custom logic for sorting/filtering/inclusions/sparse fieldsets/relationships is going to have to be defined in resource definitions, in the custom resource services, and possibly in the JsonApi controllers?

**Comment by bart-degreed** [comment]
Resource definitions are called from the built-in resource service and repository. Since you're replacing those, you'll have to call into them yourself if you want to use them.

I recommend to inject `IEnumerable<IQueryConstraintProvider>` in your custom resource services to obtain access to parsed and validated query string parameters. Injecting and filling `IPaginationContext` is needed for correct links rendering. It helps to take a close look at the built-in resource service and repository to see how to drive things and what to inject to obtain the details you need.

**Comment by bart-degreed** [comment]
@gordsmash Do you need this issue to remain open?

**Comment by gordsmash** [comment]
@bart-degreed I'm good now, you answered my questions about this. Thanks!
