### ISSUE TITLE
Sparse Fieldsets not working when reference navigation property name in querystring

### ISSUE THREAD

**Issue by rachael-ross** [json-api-dotnet/JsonApiDotNetCore#1006]
#### DESCRIPTION

I've been using a version of JADNC from 10/2020 and got latest about a month ago. The queries that were working great for months, no longer work when it comes to sparse fieldsets on navigation properties and I'm not seeing any change in documentation about this.

#### STEPS TO REPRODUCE

I have this Plan class that has **PlanType**, **Platform** and **RecordKeeper** "HasOne" navigation properties.  I also have a collection of **PlanAssetRollup** which is named _AssetRollups_.

    public class Plan : Identifiable<long>
    {       
        [Attr]
        [Required, MaxLength(100)]
        public string Name { get; set; }
      
        [Attr]
        public int PlanTypeId { get; set; }

        [HasOne]
        public virtual PlanType PlanType { get; set; }

        [Attr]        
        public int? PlatformId { get; set; } 

        [HasOne]
        public virtual Platform Platform { get; set; }

        [Attr]       
        public int RecordKeeperId { get; set; }

        [HasOne]
        public virtual RecordKeeper RecordKeeper { get; set; }

        [HasMany]
        public ICollection<PlanAssetRollup> AssetRollups { get; set; } = new HashSet<PlanAssetRollup>();   
    }

One of the queries we've been using is:

 ```/plans?
  include=planType,platform,recordKeeper,assetRollups,assetRollups.org
  &fields=id,name
  &fields[recordKeeper]=name
  &fields[platform]=name
  &fields[planType]=name
  &fields[assetRollups.org]=city,stateId
```

We reference the actual property names, not the types.

I've stepped through the code and this is where the exception is occurring:

   ```
ResourceGraph::GetResourceContext
   return _resources.SingleOrDefault(resourceContext => resourceContext.PublicName == resourceName);
```
which is called by SparseFieldTypeParser::GetResourceContext

In examining the populated graph, I have pluralized types.

Can you let me know what has changed to cause this difference in behavior?

#### EXPECTED BEHAVIOR

Expect client developer to be able to query navigation properties by property names.

#### ACTUAL BEHAVIOR

{
    "errors": [
        {
            "id": "e718598b-22be-43cb-8970-fc6b1010ad3c",
            "status": "400",
            "title": "The specified fieldset is invalid.",
            "detail": "Resource type 'recordKeeper' does not exist.",
            "source": {
                "parameter": "fields[recordKeeper]"
            }
        }
    ]
}

#### VERSIONS USED
- JsonApiDotNetCore version:
- ASP.NET Core version:
- Entity Framework Core version: 
- Database provider:

**Comment by bkoelman** [comment]
Yes, we changed this in v4.0.0. The breaking change is documented in the release notes at https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v4.0.0. The reason for this change is we discovered our implementation violated the json:api spec. I think we also updated the docs according to this change, but please let us know if we missed something.

**Comment by rachael-ross** [comment]
Yeah, after I posted this, I took a look at the spec and saw [TYPE]. 

This is a bummer...The way it was implemented before gave more precise control - unless I'm not understanding fully.

For instance, let's say you have a class "Employee" that also has navigation properties of type "Employee".  You want all root Employee fields, but only the first and last names of the Manager and only email of the HiredBy. However, you can only include "fields[employees]" once and it will apply to all of them?

Am I understanding this correctly?

```
public class Employee: Identifiable<long>
{       
    [HasOne]
    public virtual Employee Manager { get; set; }
  
    [HasOne]
    public virtual Employee HiredBy { get; set; }

    [Attr]
    public string FirstName { get; set; }

    [Attr]
    public string LastName { get; set; }

    [Attr]
    public string EmailAddress { get; set; }
}
```

Regardless, the spec is the spec so I understand the decision to change the implementation.

**Comment by bart-degreed** [comment]
> Am I understanding this correctly?

Yes.
