### ISSUE TITLE
NHibernate support

### ISSUE THREAD

**Issue by lofcz** [json-api-dotnet/JsonApiDotNetCore#1043]
Since v3 there has been a move to support orms other than efcore, #291 tracks Marten support, Mongo already exists as a separate package. Nhibernate is a well-known orm with a large userbase which would benefit from being supported by JADNC. This issue aims to track progress to do this. If anyone has already started working on an adapter please feel free to share as I would like to avoid reinventing the wheel.

**Comment by bart-degreed** [comment]
Hi @lofcz, thanks for expressing interest in this. I've used NHibernate in some projects many years ago. However, we currently have no plans to invest time in adding NHibernate support to JADNC and we are not aware of anyone already working on that.

So feel free to give it a try, but note it's going to be a large amount of work, though.

**Comment by bkoelman** [comment]
Closing, as this feature request has been open for a very long time. The JADNC team has no interest in implementing this, and no community members have expressed such interest either. Feel free to add a comment if you'd like to start working on this.
