### ISSUE TITLE
Support for client-generated IDs

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#1054]
Currently the OpenApi integration takes into account the `JsonApiOptions.AllowClientGeneratedIds` option when generating schemas for resource objects, but this hasn't been thoroughly tested.

**Comment by bkoelman** [comment]
`AllowClientGeneratedIds` was renamed to `ClientIdGeneration`. It can be set in global options, then overridden per resource type. See https://www.jsonapi.net/usage/options.html#client-generated-ids.
