### ISSUE TITLE
Support for query string parameters

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#1058]
The current OpenApi integration does not support any query parameters. The task is to describe the standard JsonApiDotNetCore query features as [query parameters](https://swagger.io/docs/specification/describing-parameters/#query-parameters) in the OAS:
- filtering
- sorting
- including
- pagination
- field selection

 A first effort would be to add all parameters as string key-value pairs. So far two possible directions for a solution have been identified:
- Instantiating a customized `ControllerParameterDescriptor` and adding it to `ActionDescriptor.Parameters`, using the metadata mechanism we have built in the core of the OpenApi integration.
- Post-processing using a Swashbuckle `IOperationFilter`.

**Comment by bkoelman** [comment]
This should also take [AttrCapabilities] into account.

**Comment by bkoelman** [comment]
Should take `[DisableQueryString]` on controllers into account.
