### ISSUE TITLE
Generalized handling of link objects

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#1062]
The current state of the OpenApi integration has a hardcoded configuration for where and when links are included in schemas.

In JADNC this can be configured by:
-  ~toggling `JsonApiOptions.DefaultPageSize` (enabling/disabling paging links)~
   - This wouldn't be correct. Even when pagination is turned off by default, it can still be activated per request using the `page[size]` query string parameter.
-  `LinkTypes` cascading configuration

These settings should be taken into account when links are included or excluded in the generation of schemas.

**Comment by bkoelman** [comment]
Should include an end-to-end test for `describedby` with a non-default path.

**Comment by bkoelman** [comment]
Should include a test for the following scenario:

```http
GET /api/todoItems/1/assignee HTTP/1.1
```
```json
{
  "data": {
    "type": "people",
    "id": "1",
    "attributes": {
    },
    "relationships": {
    },
    "links": {
      "self": "/api/people/1" // <---
    }
  }
}
```
Where the marked link is _omitted_ from the response when the `/api/people/1` endpoint is unavailable. This happens when `PeopleController` doesn't exist.
