### ISSUE TITLE
Reuse schema for POST and PATCH versions of resource request object

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#1064]
Currently the integration always uses a different resource object for patching and posting purposes in schema generation.

There exist two different schemas for posting and patching a resource object because in principle their set of attributes may differ as a result of attribute capability configurations. However, if the attribute capabilities are configured in such a way that there is no difference, there is no need to distinguish between `ResourcePostRequestObject` and `ResourcePatchRequestObject`. We can then introduce an optimisation by using `ResourceRequestObject` for both.

It needs to be carefully if the effect of such optimization on the usage of a generated client is desired: changing attribute capabilities could lead to generated types changing or appearing in an unexpected way.

**Comment by bkoelman** [comment]
I don't think this is worth the effort. It changes class names when updating capabilities, which can be perceived as confusing. The optimization is solely a smaller schema, which affects client generation and the Swagger UI. These are not performance critical. It does not improve endpoint execution time.
