### ISSUE TITLE
Contains filter errors on more than one value

### ISSUE THREAD

**Issue by rachael-ross** [json-api-dotnet/JsonApiDotNetCore#1085]
#### DESCRIPTION

When attempting to use the `contains` filter with more than one value, we receive an error.

#### STEPS TO REPRODUCE

If I try '**contains**', I receive a syntax error:

    /funds?filter=contains(ticker,'DRMBX','LHCAX')

If I try '**any**', it returns the appropriate records that exactly match:

    /funds?filter=any(ticker,'DRMBX','LHCAX')

#### EXPECTED BEHAVIOR

The documentation states `Equals one value from set` for `any`, which I interpret to mean a **full match**.

The documentation states 'Contains text' for `contains`, which I interpret to mean a **partial match**. From the documentation, the example below shows two values being passed to `contains`.

From https://www.jsonapi.net/usage/reading/filtering.html : 
![image](https://user-images.githubusercontent.com/17603150/133853963-555d777d-523f-418a-9719-a1805bb8bdda.png)

#### ACTUAL BEHAVIOR

```
{
    "errors": [
        {
            "id": "14207389-cfa8-435a-aece-47a3c7269c59",
            "status": "400",
            "title": "The specified filter is invalid.",
            "detail": ") expected.",
            "source": {
                "parameter": "filter"
            }
        }
    ]
}
```

#### VERSIONS USED
- JsonApiDotNetCore version:
- ASP.NET Core version:
- Entity Framework Core version:
- Database provider:

**Comment by bart-degreed** [comment]
Very sharp! Yes, you're right, the example is wrong. 

All you're saying is true: `contains` performs a partial match against a single value, while `any` performs an exact match against a set of the values, where at least one member in the set must be identical to the field.

So the example should be:

~GET /articles?include=author,tags&filter=equals(author.lastName,'Smith')&filter[tags]=contains(label,'tech','design') HTTP/1.1~
GET /articles?include=author,tags&filter=equals(author.lastName,'Smith')&filter[tags]=any(label,'tech','design') HTTP/1.1
