### ISSUE TITLE
DTO support / models & controllers isolation /  serialization mechanism

### ISSUE THREAD

**Issue by vidyaevoleg** [json-api-dotnet/JsonApiDotNetCore#1094]
Hello there!

I'm trying to figure out how to apply JADNC to a bit more complicated cases. 

1) For example, we have one model Post that could be updated from multiple endpoints `/api/admin/*` and  `/api/client/*`. In this case model class should stay the same, but payloads for those endpoints should be different:
`/api/client/*` payload: `{ "text": "...", "name": "..." }`
`/api/admin/*` payload: `{ "text": "...", name: "...", "showOnMainPage": true }`

The case makes me thinking of using 2 different DTO objects here: `AdminPostDto` and `ClientPostDto`, but how I can say to the controller to use `ClientPostDto` as input parameter for `CreateAsync` action and return `Post` object itself after the creation? The default behaviour says that `Post` object is expected as input and as output. Is that possible to change this rule somehow?

2) How I can expose different attributes from the same model,  but for the different controllers. For example, Client app should not receive `showOnMainPage` property, but it's needed within Admin app

Thanks!

**Comment by bart-degreed** [comment]
What you're describing violates the JSON:API spec and is not possible. However, what you can do instead is use a single resource model, but hide some fields for non-admin users. See example at https://www.jsonapi.net/usage/extensibility/resource-definitions.html#excluding-fields.
