### ISSUE TITLE
Question: How to handle resource creation where a relationship is required

### ISSUE THREAD

**Issue by VincentVrijburg** [json-api-dotnet/JsonApiDotNetCore#1134]
DESCRIPTION

I have multiple resources where attributes and relations are required (set through the fluent API in the EF Core context).

Although I set the relationship in my JSON body (see example below) the relationship does not seem to get attached to the parent resource.

```json
{
    "data": {
        "type": "cars",
        "attributes": {
            "param1": 1,
            "param2": false
        }
    },
    "relationships": {
      "engine": {
        "data": {
          "type": "engines",
          "id": "01b98643-17ce-4983-ab11-a55852000b94"
        }
      }
    }
}
```

Now, I checked what was supposed to be written in the database (by setting a breakpoint on the 'OnWritingAsync' method in the definition of this resource) and I found that the relationship was indeed not attached.

What I'm trying to accomplish is that the relationship is set from the gecko, whereafter the related entity is retrieved, while the payload is deserialized into the entity. This way the (non-mapped) attributes that depend on this relationship can be computed.

Also, when the relationship data is not provided it should return a relevant error message.

What is the recommended approach to accomplish this?
I feel like this should be a feature out of the box and I'm not the first one asking about this, but I couldn't find anything in the documentation and I couldn't find an older issue talking about this.

EXPECTED BEHAVIOR

I expect the resource to be created with the assigned relationship where attributes depending on the relationship can be computed as well.

ACTUAL BEHAVIOR

Violation of not-null constraints for resources with required relations (DbUpdateException).

VERSIONS USED
- JsonApiDotNetCore version: 4.2.0
- .NET version: 5.0
- Entity Framework Core version: 5.0.12
- Database provider: Postgres

**Comment by VincentVrijburg** [comment]
This is a bit awkward because it seems like I made a small error in my request body.
The `relationships` object should be inside the `data` object. Thus, the request body should look like this:

```json
{
    "data": {
        "type": "cars",
        "attributes": {
            "param1": 1,
            "param2": false
        },
        "relationships": {
            "engine": {
                "data": {
                "type": "engines",
                "id": "01b98643-17ce-4983-ab11-a55852000b94"
                }
            }
        }
    }
}
```

After which the expected behaviour is the actual behaviour, as described in my issue above.

I hope this helps!

**Comment by bart-degreed** [comment]
If you'd use data annotations (such as `[Required]`) instead of the EF Core Fluent API and turn on ASP.NET ModelState validation in options (enabled by default in v5), you'd get a nice error message.

For example, in v5 (where we corrected the returned source pointer path), sending:

```http
POST http://localhost:14140/api/v1/todoItems HTTP/1.1
```

```json
{
  "data": {
    "type": "todoItems",
    "attributes": {
      "description": "Finish homework",
      "priority": "Low"
    }
  },
  "relationships": {
    "owner": {
      "data": {
        "type": "people",
        "id": "1"
      }
    }
  }
}
```

Returns:

```json
{
  "links": {
    "self": "/api/v1/todoItems"
  },
  "errors": [
    {
      "id": "d2f09e1a-4c4a-43e3-b1d1-aa7f8a179f51",
      "status": "422",
      "title": "Input validation failed.",
      "detail": "The Owner field is required.",
      "source": {
        "pointer": "/data/relationships/owner/data"
      }
    }
  ]
}
```
