### ISSUE TITLE
JsonApiResourceService<TResource, TId> Not Firing for Atomic Operations

### ISSUE THREAD

**Issue by rachael-ross** [json-api-dotnet/JsonApiDotNetCore#1172]
#### DESCRIPTION

I have a few classes that inherit from JsonApiResourceService<TResource, TId> and are registered in startup. When making requests to JsonApiController-derived implementations, the custom ResourceServices are executing fine. However, when performing an atomic operation where I'm creating multiple resource types, they are not.

The resources ARE being created/updated successfully, but the custom logic isn't being executed.

#### STEPS TO REPRODUCE

I've tried a couple of different ways to register them:

```
 services.AddScoped<IResourceService<Plan, long>, PlanResourceService>();
 services.AddScoped<JsonApiResourceService<Plan, long>, PlanResourceService>();
```

#### EXPECTED BEHAVIOR

I would expect the pipeline to execute for each operation as it would via the single type controllers.

#### ACTUAL BEHAVIOR

In stepping through the code, an instance of JsonApiResourceService<TResource, TId> is being used, rather than the registered implementation.

#### VERSIONS USED
- JsonApiDotNetCore version: 5.0.2
- ASP.NET Core version: 6.0.5
- Entity Framework Core version: 6
- Database provider: SQL Server

**Comment by rachael-ross** [comment]
Just found the answer... 

```services.AddResourceService<PlanResourceService>();```

**Comment by bkoelman** [comment]
That's correct. The indiviual handlers for operations resolve their minimal interface needed, for example `ICreateService<,>`. And as you already discovered, `AddResourceService` registers them all.
