### ISSUE TITLE
Add support for custom media types

### ISSUE THREAD

**Issue by leandroaraujosouza** [json-api-dotnet/JsonApiDotNetCore#1174]
**Context**
I have a requirement to accept a custom media type, i.e _application/vnd.company.somecode.someothercode.version+json_

**Possible solution**

I'd like to have the ability to configure the Middleware like the below:

```csharp
services.AddJsonApi()
             .RemoveDefaultMediaType()
             .AddCustomMediaType("application/vnd.company.somecode.someothercode.version+json");
```
* The **.RemoveDefaultMediaType()** method would make the JADNC Framework **deny** requests with the default **application/vnd.api+json** media type
* The **.AddCustomMediaType()** would cause the JsonApiMiddleware to allow requests with the custom media type and to produce the response with the same current format.

**Note**

Please, let me know if that makes sense for the context of this framework, if it does, I'll be proposing a solution shortly

Thank you!

**Comment by bkoelman** [comment]
This violates [the JSON:API spec](https://jsonapi.org/format/1.1/#introduction), so I'm going to need a stronger reason to enable that:
> JSON:API requires use of the JSON:API media type ([application/vnd.api+json](http://www.iana.org/assignments/media-types/application/vnd.api+json)) for exchanging data.

However, you can use non-JSON:API endpoints in the same project by not inheriting from our base controller classes. The middleware remains silent in that case. See examples at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers.

Would that work for you?

**Comment by leandroaraujosouza** [comment]
Thanks for the quick reply. I'll be looking into it 😀

**Comment by leandroaraujosouza** [comment]
Hi @bkoelman By the time we're discussing this I didn't have any argument to support this, but now, I know that we're using a [Additional Media Type Structured Syntax Suffixes](https://www.rfc-editor.org/rfc/rfc6839) and I can see many Media Types like the one I proposed in here https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by bkoelman** [comment]
I still don't understand your point. So there's RFC6839, which specifies that suffixes can be used in media types in HTTP traffic. JSON:API conforms to that by using the `+json` suffix. Then there's a list of known media types, which includes the one for JSON:API.

The JSON:API spec is quite clear that only "application/vnd.api+json" must be used, followed by a detailed protocol for content negotiation, versioning, extensions and profiles.

So the JSON:API spec is more strict than the HTTP spec, intentionally. It dictates how clients and servers need to behave when using the JSON:API protocol. Likewise, the spec for XML or JSON formats is more strict than the general spec for exchanging text files or binary files. Making it more specific enables specific use cases, which is a good thing.

Nobody is enforcing you to use JsonApiDotNetCore, or even the JSON:API spec. But JsonApiDotNetCore tries to be compliant to JSON:API, so providing mechanisms to break it seems like a bad idea, unless there's a good motivation for it. After all, if you're telling API clients that you're using JSON:API to communicate, better adhere to it so you can establish successful communication. What's the point of agreeing on a protocol, then doing something that violates that?

You still haven't explained _why_ you want to use a different media type. "I have a requirement" doesn't motivate me to introduce a mechanism that solely exists to _violate_ JSON:API spec compliance. Anyone can make up requirements, which may be based on misunderstandings. So why do you have this requirement?

If you want JSON:API to relax its requirements for media types, I suggest you open an issue to change the JSON:API spec at https://github.com/json-api/json-api. Though I expect they're going to want a good reason for that too...
