### ISSUE TITLE
Question: How to get concrete FilterExpression from query string?

### ISSUE THREAD

**Issue by milosloub** [json-api-dotnet/JsonApiDotNetCore#1175]
#### SUMMARY
Hi, I'm trying to read value from concrete filter query. For example, application uses query like:
`GET api/orders?filter=equals(isFinished,'true') `
or
`GET api/orders?filter[isFinished]=true `
I would like to catch presence of this filter usage, read 'true' value and use it elsewhere. Is there any way to achieve this?
Thank you.

**Comment by bkoelman** [comment]
To access parsed JSON:API query string parameters, inject `IEnumerable<IQueryConstraintProvider>` in your constructor. For example, the following code traverses the providers to get a list of top-level filters:
```c#
FilterExpression[] filtersInTopScope = _constraintProviders
        .SelectMany(provider => provider.GetConstraints())
        .Where(constraint => constraint.Scope == null) // top-level only
        .Select(constraint => constraint.Expression)
        .OfType<FilterExpression>()
        .ToArray();
```
Similarly, the example at: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/018531106a5542e7b74155670aae79658857b76f/test/JsonApiDotNetCoreTests/IntegrationTests/Archiving/TelevisionBroadcastDefinition.cs#L76-L81 searches for includes.

**Comment by milosloub** [comment]
Perfect, it is exactly what I was looking for. Thanks
