### ISSUE TITLE
How to apply query filtering in a NoEntityFramework scenario?

### ISSUE THREAD

**Issue by gazmunro** [json-api-dotnet/JsonApiDotNetCore#1180]
#### SUMMARY
We have an implementation that has mixed EF & non EF backed resources, We'd like to support filtering for the non EF backed resources but can't see a straightforward way to do it.

#### DETAILS
Our scenario is similar to the example workitem service 
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/Examples/NoEntityFrameworkExample/Services/WorkItemService.cs
When we provide filter parameters and debug it seems as though JADNC is trying to intepret them and throwing errors - perhaps we need a way to tell JADNC not to try and apply filters to the non EF backed resources and some way to access the filter metadata so that we can implement it ourselves?

#### STEPS TO REPRODUCE
Try to implement any arbitrary filter to the WorkItemService in the NoEntityFrameworkExample project

#### VERSIONS USED
- JsonApiDotNetCore version: 5.0.1
- ASP.NET Core version: 6.0
- Entity Framework Core version: N/A
- Database provider: N/A

####
Thanks :)

**Comment by bkoelman** [comment]
I've created an example at #1181, which shows how to access query string parameters from a resource service.

I'm not getting any errors, so please include more details such as the stack trace, example request, etc. if you need help with that.

**Comment by gazmunro** [comment]
Thanks for your help. 

The issue was caused by a misunderstanding of the Spec and an attempt to use a filter like the example 
GET /comments?filter[post]=1 HTTP/1.1
From https://jsonapi.org/recommendations/#filtering
Rather than from your documentation here
https://www.jsonapi.net/usage/reading/filtering.html

We have been able to adapt your example to our use case

**Comment by bkoelman** [comment]
Glad to hear this works for you.

Note you can still use the old filter syntax by adding `options.EnableLegacyFilterNotation = true` at startup, as described [here](https://www.jsonapi.net/usage/reading/filtering.html).
