### ISSUE TITLE
Improve error message when duplicate controller found

### ISSUE THREAD

**Issue by bkoelman** [json-api-dotnet/JsonApiDotNetCore#1188]
Include the fully qualified type names of the conflicting controllers at https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/6b69ed3f8f396348b1665e6395acfb77ab74c4bd/src/JsonApiDotNetCore/Middleware/JsonApiRoutingConvention.cs#L81.

**Comment by balaji222528** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/41604317/189572397-b36c9411-2af4-469c-aee0-63962d1f5f2f.jpeg)

This is my controller 
When I update my package am getting the issue as Multiple configuration found for resource type 'DocumentListResponse'.

**Comment by balaji222528** [comment]
When it reaches this line ![image](https://user-images.githubusercontent.com/41604317/189573238-062ecd61-289d-4293-ab7a-b298f25828da.jpeg)
 It's coming out of the loop when I point to jadnc. But throws error when I update the bigger reference

**Comment by bkoelman** [comment]
First of all: don't hijack this issue. This one is tracking to improve the error message, which is unrelated to *why* you are hitting this error. Create a new issue and fill out all the requested information, including repro steps.

Your messages here and in the chat are quite chaotic and don't make any sense to me. There is no loop in your screenshot and I have no idea what you mean with "bigger reference". Also you're not showing what's in the dictionary *at the time the exception is thrown*, nor what the current resource type is. Those two identify the conflict. I assumed you'd be able to debug this, look around, and make sense of what's happening, but apparently this is going nowhere. In case you have a peer around that's a senior developer, I'd suggest you ask him/her for help on debugging.

Either way, I'm going to require repro steps. Whether you're going to find the repro steps based on what you learned while debugging, or by iteratively removing parts (as described in the chat) is up to you. The best repro is a full project that I can open and run. No screenshots please.

**Comment by balaji222528** [comment]
Hey Bart
We were able to figure out the root cause of this issue .
If I use the nugget refrence to my project , it creates the autogenerated
file under the resource using source generator and thatswhy we got that
error as multiple controller etc .
Is there any am way I can switch that off?
