### ISSUE TITLE
Using "authorize" with Auto-generated controller?

### ISSUE THREAD

**Issue by bracke** [json-api-dotnet/JsonApiDotNetCore#1194]
#### SUMMARY
If I use hand-written controllers, I can use the [Authorize] attribute, is there a way to do something similar with Auto-generated controller (using the [Resource] attribute)?

#### VERSIONS USED
- JsonApiDotNetCore version: 5.0.2
- ASP.NET Core version: net6.0
- Entity Framework Core version: 6.0.8
- Database provider: SQL Server

**Comment by bkoelman** [comment]
It depends, see https://gitter.im/json-api-dotnet-core/Lobby?at=6323378b3a42316d33f0e016.

**Comment by bracke** [comment]
So, the solution would be to add it to the partial?

Is it perhaps possible to add it globally to all controllers?

**Comment by bkoelman** [comment]
> So, the solution would be to add it to the partial?

Yes.

> Is it perhaps possible to add it globally to all controllers?

Not with source generators. How would you expect that to work?
If not using source generators, you can define your own base class that inherits from JsonApiController and put the attribute there.

**Comment by bracke** [comment]
I guess in the end it would be just as simple to just use hand-written controllers.

**Comment by matthewblott** [comment]
Hi, I had a look at the Gitter exchange above but it doesn't make any sense to me. Is it possible to use the Authorize attribute? If not, is it possible to intercept the requests via middleware and check user claims? I had a look through the examples and the docs but couldn't see anything.
