### ISSUE TITLE
No DbContext was found in assembly.

### ISSUE THREAD

**Issue by ail-milan** [json-api-dotnet/JsonApiDotNetCore#1200]
#### DESCRIPTION
I have created a solution. which have 2 projects,
1. `Project A` (WebAPI) - .NET 6.0
2. `Project B` (Class Library c#) - .NET 6.0

Now what happed is my DbContext is in the `Project B`, all my DB related stuff is in the `Project B`
All my controllers are in the `Project A`.
`Project A` has a reference to `Project B`. 

`Project A` `Program.cs` content ...
```c#
builder.Services.AddDbContext<DatabaseContext>();
// Json:API config
builder.Services.AddJsonApi<DatabaseContext>();
```

`Project B` `DatabaseContext.cs` content ...
```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    string connectionString = _configuration.GetConnectionString("DBConnection");
    optionsBuilder.UseSqlServer(connectionString, b => b.MigrationsAssembly("Project A"));
}
```

Now try to create Migrations using below command...
```
dotnet-ef migrations add Init_DB
```

it will be giving me error ...
```
No DbContext was found in assembly
```

**Comment by bkoelman** [comment]
This sounds like an EF Core problem. JADNC just consumes the model to serve API requests, it has nothing to do with migrations. You'll probably get the same error when not using JADNC at all. Can you verify that?

**Comment by ail-milan** [comment]
If I remove the line 
```c#
builder.Services.AddJsonApi<DatabaseContext>();
```

it will work perfectly ...

**Comment by bkoelman** [comment]
I'm quite surprised to hear that. I'm willing to help and find the root cause. For that I'm going to need to reproduce this, but my knowledge of how migrations work is superficial. It would help if you can provide a minimal repro project (zip or GitHub) with the exact steps to get to the error (for example, from which directory you're running the command). It would also help to include the versions used (OS, .NET, EF, etc)

**Comment by ThomasBarnekow** [comment]
Wouldn't you normally have to specify the project that contains the DbContext if is it not in the main (startup) one? EF Core migrations will not find it otherwise.

**Comment by ail-milan** [comment]
I have just tried with your given sample code, and it will work perfectly!!
Here I have created sample from your code, and it is working fine,
[DemoAPI](https://github.com/ail-milan/DemoProj/archive/refs/heads/master.zip) Project

Closing this issue!!
Thanks for guiding me.

**Comment by bkoelman** [comment]
Glad to hear this works for you. And thanks for sharing your project.
