### ISSUE TITLE
Handling query string parameters without EF Core

### ISSUE THREAD

**Issue by bkoelman** [json-api-dotnet/JsonApiDotNetCore#1202]
From https://gitter.im/json-api-dotnet-core/Lobby?at=634e9e31a3ccb16cbe13f782:

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 18 14:38_
> Hello everyone, I am trying to use JsonApiDotNetCore without EntityFramework, on an already existing database (and on which I cannot change the structure).
I have tables that don't have a unique id, but are composed of the parent key + a child key. What is the best practice to build my resources? Can I define a "Tid" with a multi-value key?
> 
> Here is a simple example in a database
> 
> Persons :
> ID NAME
> 1 Ryder
> 2 Joe
> 3 William
> 
> Dogs
> PARENTID | ID | DOG
> 1 | 1 | Rubble
> 1 | 2 | Marshall
> 2 | 1 | Rocky
> 
> How would you build the resource classes?

_Bart Koelman @bkoelman Oct 18 18:48_

> If you'd use EF Core, we have a sample that shows how to handle composite PKs at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/JsonApiDotNetCoreTests/IntegrationTests/CompositeKeys. But if you don't use EF Core, then you're responsible for implementing logic to query the database yourself, so you can do it in any way you want.

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 19 11:22_
> Hi Bart and thanks for the quick response! I had also thought of an implementation based on key concatenation, so I'll go with that. I have another question, again because of the fact that I'm not using entity, how do I intercept the parameters passed by filters and sorts? Is it in JsonApiResourceDefinition? Because OnApplySort and OnApplyFilter seem not to be called, while OnApplySparseFieldSet is called when i use expected query args.

_Bart Koelman @bkoelman [Oct 19 13:16]_
> See [json-api-dotnet/JsonApiDotNetCore#1181](https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1181), which shows how to access parsed query string parameters. When not using EF Core, you'll need to make the appropriate calls into resource definitions yourself (via injected IResourceDefinitionAccessor). The reason you're seeing OnApplySparseFieldSet being called is because the response serializer throws out any additional fields that were retrieved from database, but should not be returned. Normally it is called twice, the first time allowing to fetch additional fields from DB, typically if there are calculated properties whose value depends on another property that isn't requested.

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 20 00:55_
> Thank you! My mistake was to extract the expressions in the service constructor, but it seems that the analysis is not yet done at that time.
> By doing the expression extraction in each service command, I get the data passed in the url. I need now to create my own base service class, have to include the expression parsing + definition event calls + calls to my custom repository. Great job anyway, great framework!

_Bart Koelman @bkoelman Oct 20 03:54_
> Thanks!

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 22 00:38_
> Hello, I have a new problem, I have integrated a property exposed with a relation [HasMany] in my entity. When I try to load via http://route/1?include=myproperty the json flow response returns "included": [] while my object is correctly instantiated on the c# side, I can't understand what's wrong, is it a problem with the serialization options? The uri seems to be well interpreted because if I fill a bad value in myproperty, I have an error. I have the problem with a [HasOne] attribute too. Any suggestions?

_Bart Koelman @bkoelman Oct 22 01:47_
> I would guess you didn't populate the relationship property with objects retrieved from the database, but it's hard to say without more info. Can you create an issue with minimal repro steps?

_Bart Koelman @bkoelman Oct 22 01:50_
> Alternatively, you can step into the source code from our NuGet while debugging, see the next link on how to use: https://devblogs.microsoft.com/dotnet/improving-debug-time-productivity-with-source-link/

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 23 10:06_
> My entities :
> ```c#
> public class Person : Identifiable<int>
> {
>     [Attr]
>     public string Name { get; set; }
>     [Attr]
>     public int Age { get; set; }
>     [HasMany]
>     ICollection<Dog> Dogs { get; set; }
> }
> 
> public class Dog : Identifiable<string>
> {
>     [HasMany]
>     public Person Owner { get; set; }
>     [Attr]
>     public string Name { get; set; }
> }
> 
> public class Program
> {
>     var builder = WebApplication.CreateBuilder(args);
>     builder.Services.AddJsonApi(opt =>
>     {
>         opt.SerializerOptions.WriteIndented = true;
>         opt.RelationshipLinks = JsonApiDotNetCore.Resources.Annotations.LinkTypes.All;
>         opt.DefaultAttrCapabilities = JsonApiDotNetCore.Resources.Annotations.AttrCapabilities.All;
>         opt.ResourceLinks = JsonApiDotNetCore.Resources.Annotations.LinkTypes.All;
>         opt.TopLevelLinks= JsonApiDotNetCore.Resources.Annotations.LinkTypes.All;
>     },
>     discovery =>
>     {
>         discovery.AddCurrentAssembly();
>     });
> 
>     builder.Services.AddScoped<IResourceService<Person, int>, PersonService>();
>     builder.Services.AddScoped<IResourceService<Dog, string>, DogService>();
>     builder.Services.AddScoped<IDogRepository, DogRepository>();
>     builder.Services.AddScoped<IPersonRepository, PersonRepository>();
>     var app = builder.Build();
> 
>     app.UseRouting();
>     app.UseJsonApi();
>     app.MapControllers();
> 
>     app.Run();
> }
> 
> public class PersonService : IResourceService<Person, int>
> {  
>     IPersonRepository repo;
>
>     public PersonService(IPersonRepository repo)
>     {
>         repo = _repo;
>     }
> 
>     public Task<Person> GetAsync(int id, CancellationToken cancellationToken)
>     {
>         return Task.Run(() => { return repo.GetByID(id); });
>     }
> 
>     public Task<IReadOnlyCollection<Person>> GetAsync(CancellationToken cancellationToken)
>     {
> 
>         return Task.Run(() => { return repo.GetAll(); });
>     }
>     // ...
> }
> 
> public class DogService : IResourceService<Dog, string>
> {
>     IDogRepository _repo;
> 
>     public DogService(IDogRepository repo)
>     {
>         _repo = repo;
>     }
> 
>     public Task<Dog> GetAsync(string id, CancellationToken cancellationToken)
>     {
>         return Task.Run(() => { return repo.GetById(id); });
>     }
> 
>     public Task<IReadOnlyCollection<Dog>> GetAsync(CancellationToken cancellationToken)
>     {
>         return Task.Run(() => { return _repo.GetAll(); }); 
>     }
>     // ...
> }
> ```

_Alexandre DOMS @Alexandre.D-IdemSante_gitlab Oct 23 10:12_
> I tried to debug it, when calling http://route/Dogs/1?include=owner, but i saw nothing, i think it's in the ResponseModelAdapter, when Convert function is called, especially when document.Included = GetIncluded(rootNode); is called.

**Comment by bkoelman** [comment]
I'm not seeing any code that sets the `Dog.Owner` property based on the `include` query string parameter, therefore the serializer doesn't render it. You haven't included the code from the repositories nor are using `IEnumerable<IQueryConstraintProvider> constraintProviders` anywhere to fetch the requested includes from the database. Can you add the missing code?

> I tried to debug it, when calling http://route/Dogs/1?include=owner, but i saw nothing

What do you mean by "nothing"? Are you getting no response, are you unable to step into the code? Please be more specific on what you tried exactly, including the expected and observed outcome.

**Comment by bkoelman** [comment]
Thanks, that's helpful. There's another piece missing that I forgot to mention.

The serializer determines which includes to render, based on the `include` query string parameter. But instead of reading includes directly from the constraint providers, there's an additional step involved. Because user code may have changed the includes via resource definitions, the final set of includes is normally stored in `IEvaluatedIncludeCache`.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/af461681cbf2e745c1af665f46d159ef85932d09/src/JsonApiDotNetCore/Serialization/Response/ResponseModelAdapter.cs#L67-L68

In your case, the cache is empty, so no includes are rendered. To make it work, you need to call `IEvaluatedIncludeCache.Set()` before serialization occurs. It can be done in the following way:

```c#
public DogRepository(PersonRepository personRepo, IEvaluatedIncludeCache evaluatedIncludeCache,
    IResourceGraph resourceGraph)
{
    // ... existing code unmodified ...

    ResourceType dogType = resourceGraph.GetResourceType<Dog>();
    RelationshipAttribute dogOwnerRelationship = dogType.GetRelationshipByPropertyName(nameof(Dog.Owner));

    // alternative way to obtain the relationship:
    // dogOwnerRelationship = resourceGraph.GetRelationships<Dog>(dog => dog.Owner).Single();

    var includeElementExpression = new IncludeElementExpression(dogOwnerRelationship);
    var includeExpression = new IncludeExpression(ImmutableHashSet.Create(includeElementExpression));
    evaluatedIncludeCache.Set(includeExpression);
}
```
This is the most straightforward way to set it up. The downside of course is that it's all hard-coded to dogs and persons. You may want to consider borrowing more from JADNC, such as `IQueryLayerComposer.ComposeFromConstraints()`. I'm not saying that you should, because it comes at the cost of added complexity and adding more than you need. Anyway, the primary concern of this type is to transform query string parameters into a database-independent data structure called `QueryLayer`, which contains the parsed representation of filters, includes, pagination, sorting, and sparse fieldsets. While running `ComposeFromConstraints`, it calls into resource definitions (several, but not all) and sets up `IEvaluatedIncludeCache` and `ISparseFieldSetCache` accordingly. See https://www.jsonapi.net/internals/queries.html for the layers involved. You can even take it a step further by using the built-in resource service and only implementing your own repository. This gives you tons of extras, such as change detection and several other features the JSON:API spec enables. Assuming you're going to explore that direction, the task at hand is to transform `QueryLayer` into your database-specific calls, which may not be something trivial to achieve. It all depends on your needs and where you want to take your project in the future...

Another tip: You can inject request-scoped `IJsonApiRequest`, which provides ambient info about the current request, such as the resource type and the current endpoint characteristics. Once you're ready for dealing with POST/PATCH, `ITargetedFields` is another request-scoped ambient type that contains which attributes and relationships are affected.

If you don't mind me asking, what's the reason you're not using EF Core?

**Comment by Alex-Doms** [comment]
Ok, it's working well now, thanks! I'm working on a redesign in .net core of an old application coded in VB6. The database is Oracle, and on a version 9, it seems that EF is not compatible on some parts, but I plan to investigate it because the reasons I was given are quite vague.

You can close the ticket, and thanks again.

**Comment by Alex-Doms** [comment]
Hi, I have a new question for this issue, it's seems that evaluatedIncludeCache works for only with one include, how do i setup it, if i have an include request for more than one relation?

**Comment by bkoelman** [comment]
IncludeExpression contains a set of subtrees. You can build your own (example [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/3069341bbdc8ef61ab395f6a8f10f683bc310ef9/benchmarks/Serialization/ResourceSerializationBenchmarks.cs)) or just feed a string to IncludeParser (example [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b48f02e5e2ef9b1550972d8c89c5951f66be8ef1/test/JsonApiDotNetCoreTests/UnitTests/Serialization/Response/ResponseModelAdapterTests.cs#L573)).

In general, many questions you can find the answer for by searching for usages in our codebase, or debugging a test to see how things look like. We have excellent coverage for all kinds of things, just a small subset is in the documentation website.
