### ISSUE TITLE
Handle int (in DTO) as string in JSON for attribute properties

### ISSUE THREAD

**Issue by bkoelman** [json-api-dotnet/JsonApiDotNetCore#1226]
See the question at https://stackoverflow.com/questions/74740975/c-sharp-jsonapidotnetcore-handle-int-in-dto-as-string-in-json-for-attribute-pr.

**Comment by bkoelman** [comment]
See #1227.

**Comment by zefanjajobse** [comment]
in C# it is still used as int, but frontend expects a string. since it's no longer via newtonsoft we don't know how to convert only on getting the data to the frontend when item contains id (see Code example Newtonsoft). the solution given converts for C# as well.
The workaround we gave only works on get/filter requests, not when posting back.

**Comment by bkoelman** [comment]
It's not helping when multiple people post parts of the same question (that contradict each other) in different places. For example:

> Due to some strange things in the React front-end application, we need to handle int's as Strings in the JSON objects. Both for return as posting.

vs:

> but the project used a newtonsoft custom converter to write all integers that contains "Id" in the key as string on GET requests, on returning and filtering etc it needs to be a integer.

That's quite vague. I assumed you want INT in the database, but have them be exposed as strings in the JSON (incoming and outgoing). And that's what my answer accomplishes. As I said in the PR, you can use EF7 conventions to generalize the approach for any field whose name ends with "Id".

So if this somehow does not meet your needs, please specify what you _do_ need exactly. Provide an example request/response for GET and POST, include your database tables, etc.

Filtering on something that isn't mapped to the database won't work, so the `EmployeeId`/`PublicEmployeeId` approach is not a solution (forget about using `[NotMapped]` if you need filtering, sorting etc).

If you want different field types for incoming and outgoing JSON, you're basically breaking the JSON:API spec. Many other things (such as OpenAPI) aren't going to work reliably when doing that. Sure you can write a STJ converter, but instead of trying to implement such hacks, perhaps your time is better spent getting to the bottom of "some strange things in the React front-end application". Can you make the frontend work with both incoming and outgoing string attributes in the JSON?

**Comment by bkoelman** [comment]
On a side note: exposing IDs as attributes is not what JSON:API is designed for. Model them as relationships instead, so you get the full HATEOAS experience, allow clients to include related resources in a single request for high performance, allow clients to compose filters than span relationships etc.

**Comment by zefanjajobse** [comment]
I understand handling ints as strings is not what you want, however we're stuck to it right now. The option you gave about EF7, that is only conversion between DB and C# DTO, in our DTO we just want the property as an int.
The problem is, that when using the Attr attribute, it completely ignores for example the JsonNumberHandling, which seems a bug to us.

**Comment by bkoelman** [comment]
As documented at https://www.jsonapi.net/usage/resources/attributes.html#complex-attributes, serialization attributes can be specified on properties of nested types (`Bar.CompoundMember`), but not on the property itself (`Foo.Bar`). That is [by design](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/233#issuecomment-671943874), so I don't understand what bug you have in mind. Anyway, nested types is not what you're asking for, so this documentation section does not apply to your case.

I've pushed another commit to the PR that uses a custom JSON converter instead of EF Core mappings, so the conversion only happens one-way.

**Comment by zefanjajobse** [comment]
thnx, that worked, I'm sorry that we weren't clear enough with our info.

**Comment by bkoelman** [comment]
Glad to hear this unblocks you.
