### ISSUE TITLE
Nested includes, missing data

### ISSUE THREAD

**Issue by Michielvv87** [json-api-dotnet/JsonApiDotNetCore#1255]
I have an application, which we've recently updated to v5.1 of JsonApiDotNetcore

The API is consumed from a react application.

We have a call to a shift-employee endpoint, which returns specific shift-employee links. In the call, I also include the field shift.shiftEmployees, so basically it includes the shfit this shift employee is linked to, and also all the shift-employees linked to that shift.

In a previous version of the package, in the included tag, also the main data object was represented. Now it isn't anymore. In React it's missing data if you map only the shifts from the results.

Attached the JSON response, where employee id 305 is only in the data attribute, and not in the included.
[response.json.txt](https://github.com/json-api-dotnet/JsonApiDotNetCore/files/10663909/response.json.txt)

Is it possible to make the API include this item?

**Comment by bkoelman** [comment]
Yes, this was changed in #1195. The JSON:API spec was clarified to no longer allow this, and we adapted JADNC accordingly. There's no configuration setting to revert to the old behavior.

**Comment by Michielvv87** [comment]
Thanks for the response, this makes things clear
