### ISSUE TITLE
JsonInvalidAttributeInfo hiding root cause of issue?

### ISSUE THREAD

**Issue by bjornharrtell** [json-api-dotnet/JsonApiDotNetCore#1266]
While debugging a serialization issue I noted that JsonException is catched at https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/d2e321c9b2023174e7bf6ff2f91911d6044c8a6f/src/JsonApiDotNetCore/Serialization/JsonConverters/ResourceObjectConverter.cs#L194 for explained reasons, but nothing from that exception is saved/propagated into the JsonInvalidAttributeInfo and as such possibly hiding the root cause of the issue (even though the issues mentioned). Wouldn't it make sense to keep the JsonException around as a member of JsonInvalidAttributeInfo?

**Comment by bkoelman** [comment]
I didn't think the original exception message contained any helpful information, while its source location was wrong. Can you provide an example where the exception message clarifies things?

**Comment by bkoelman** [comment]
@bjornharrtell If you'd like the original exception included, please provide an example that shows its added value. Otherwise I'm going to close this. I'm not against the change, but we need to rationalize and have a test for test it.
