### ISSUE TITLE
SignalR response with JSON:API serialization

### ISSUE THREAD

**Issue by Michielvv87** [json-api-dotnet/JsonApiDotNetCore#1270]
This question is also posted on stackoverflow: https://stackoverflow.com/questions/76153578/jsonapidotnetcore-and-signalr-implementation

What I want to do, is send updated objects with SignalR to my client. These updated objects, needs to be in the JSON:API specs also.
I tried to serialize an object, with the `SerializerOptions` and `SerializerWriteOptions` from `IJsonApiOptions`. This doesn't work. I also saw it was missing the `ResourceObjectConverter` in the converters, so I added it manually, but it gives no changed result. Still just the object as a 'simple' JSON response.

Is it possible to manually seralize objects with the same settings as the JADNC does? Or even better, to assign the same seriliazation to the SignalR library, so it does it automatically

**Comment by Michielvv87** [comment]
Also tried to call the IResponseModelAdapter.Convert method, this gives an error, as I'm calling a save to in this case a shift-employee endpoint, which triggers a change in a Shift, which I want to distribute.
This IResponseModelAdapter is according to the source code, closer to what I need, than my previous attempt.

**Comment by bkoelman** [comment]
Hi @Michielvv87, thanks for reaching out.

The response serialization in JsonApiDotNetCore is tied to the resource graph, which is built at startup and provides details about the JSON:API resources and fields in your API project. When built, it adds the appropriate JSON converters into options. Serialization also depends on ambient information about the current request, which is injected in the constructor of `ResponseModelAdapter`. The code [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/benchmarks/Serialization) shows how to set that up when running outside of a typical ASP.NET request.

Just in case it helps, there's also #465, though based on a pretty old version. I'm not at all familiar with SignalR, so apologies if this points you in the wrong direction.

If you need more help, please share a minimal repro, including exception stack traces, etc.

**Comment by Michielvv87** [comment]
I fixed it, almost, but good enough to let it work. In the SO post I've added my code I used

**Comment by bkoelman** [comment]
Great, thanks!
