### ISSUE TITLE
Inconsistent and Erroring Behavior When Using EF OwnsOne/OwnsMany Mapping

### ISSUE THREAD

**Issue by rtablada** [json-api-dotnet/JsonApiDotNetCore#1271]
#### DESCRIPTION

When using EF OwnsOne/OwnsMany properties for nested or complex data structures/mappings JADNC 5 returns inconsistent results, nulls, or errors depending on use of `include` or sparse fieldsets.

* For regular requests with no sparse fields and no includes, properties mapped with `OwnsOne` act as expected
* When includes for other models are requested properties mapped with `OwnsOne` will return as null or invalid results
* When using sparse fields on a resource with `OwnsOne` mappings, a tracking error is thrown.

#### STEPS TO REPRODUCE

Full reproduction project: https://github.com/rtablada/JsonApiDotnetExamples

#### EXPECTED BEHAVIOR

Attrs which expose properties from `OwnsOne` should allow regular `Attr` behavior and work with `include` and `fields` as any other exposed attribute

#### ACTUAL BEHAVIOR

`OwnsOne` `Attr` properties...
*  return expected result with no complex query string
* return null when `include` operations are requested from query string
* error when sparse fields are requested for `OwnsOne` attribute

#### VERSIONS USED
- JsonApiDotNetCore version: 5.1.2
- ASP.NET Core version: 7.0.0
- Entity Framework Core version: 7.0.4 
- Database provider: PG for example project ☝🏽 (occurs with MSSQL as well)

**Comment by bkoelman** [comment]
Hi @rtablada, thanks for reporting this and providing great repro instructions.

I've verified that #1272 fixes the two cases from your repro, but you may want to do additional testing. Until now, we didn't have any tests for using owned entities. I haven't looked into OwnsMany usage.

One thing to be aware of: Partial updates do not preserve existing values _within_ statistics. For example:
```
PATCH https://localhost:7175/countries/1 HTTP/1.1

{
  "data": {
    "type": "countries",
    "id": "1",
    "attributes": {
      "statistics": {
        "population": 456
      }
    }
  }
}
```
would clear the existing value of `gdp`. Although EF Core can update just the `Population` column, JSON:API has no concept of merging the individual fields _within_ an attribute. If you're in need of that, [JSON columns](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns) may better suit your needs. Adding non-MSSQL support is on the [roadmap](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/plan#json-columns) of EF Core 8.
