### ISSUE TITLE
Array of entity in one parameter

### ISSUE THREAD

**Issue by Alex-Doms** [json-api-dotnet/JsonApiDotNetCore#1280]
#### SUMMARY
Hello everyone, I have to implement a specific business call, I need to send a list of instances of my entity in a parameter to my controller, but is it possible with JsonApiDotnetCore controllers?

#### DETAILS

In my controller <myEntity, string>, I made a function like this : 
```
[HttpPatch()]
 public List<myEntity> MyCall([FromBody] List<myEntity> myEntities)
{
...
}
```

Compilation is ok, but when i called it with a body like this : 

```
{
     "data": 
  [
     {
     "type":"myEntities", "attributes" :{}
     }
  ]
}
```

I got this error : 

"status": "422",
            "title": "Failed to deserialize request body: Expected an object, instead of an array."

I think the controller has a restriction on the resource, that we can't use other kind of object in our [FromBody] parameters ?
Is a work around is possible? 

Thanks for your help! 

#### VERSIONS USED
- JsonApiDotNetCore version: 5.1.0
- ASP.NET Core version: .Net Core 7
- Entity Framework Core version: Custom
- Database provider: nc

**Comment by bkoelman** [comment]
Use a custom controller, as described at https://www.jsonapi.net/getting-started/faq.html#how-do-i-expose-non-jsonapi-endpoints. There's a sample at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/JsonApiDotNetCoreTests/IntegrationTests/NonJsonApiControllers.

You can't do this inside a JSON:API controller, as it violates the JSON:API rules of when objects and arrays are permitted.

**Comment by Alex-Doms** [comment]
Ok, that's what I thought, but I was hoping that for a collection there would be another alternative. I'm going to make my own controller. I'll make my own controller.
