### ISSUE TITLE
Add dark mode to documentation landing page

### ISSUE THREAD

**Issue by bkoelman** [json-api-dotnet/JsonApiDotNetCore#1291]
The docfx site features dark mode, but our landing page (based on [this template](https://bootstrapmade.com/ninestars-free-bootstrap-3-theme-for-creative/)) at www.jsonapi.net does not. Ideally, it would reuse the setting that docfx stores in the browser settings.

**Comment by bkoelman** [comment]
Here's one way to do it:

The Chrome addin [Night Eye](https://chrome.google.com/webstore/detail/dark-mode-night-eye/alncdjedloppbablonallfbkeiknmkdi) renders the page pretty nice when switched to dark mode. It has a free trial for one month.

What I think needs to be done:
1. Update the existing HTML page at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/docs/home based on the latest [template](https://bootstrapmade.com/ninestars-free-bootstrap-3-theme-for-creative/), because it uses Bootstrap v5.3.2, which includes [support for dark mode](https://getbootstrap.com/docs/5.3/customize/color-modes/).
2. Somehow extract the changed colors, after turning on dark mode in Night Eye, and apply them to the .css file. I can see the new colors using Inspect Element in Chrome Dev Tools, but I don't understand where they come from.
3. Write JavaScript that sets `data-bs-theme` to the root `<HTML>` element, based on the `theme` (dark/light/auto) property that docfx stores in local storage (see [docfx theme.ts](https://github.com/dotnet/docfx/blob/main/templates/modern/src/theme.ts)).
4. Add a drop-down button (similar to what docfx provides) to toggle the mode.

Unfortunately, I'm pretty clumsy and inexperienced when it comes to styling. Any help would be immensely appreciated! If you know of a different landing page template with built-in dark-mode support, that could be an even better solution than the steps above.

**Comment by bkoelman** [comment]
Another browser add-in that produces a nice dark mode is [Dark Reader](https://darkreader.org/).

**Comment by verdie-g** [comment]
In https://github.com/dotnet/docfx/pull/8482 a "modern" template was introduced. From that screenshot it seems to implement dark mode

![image](https://github.com/json-api-dotnet/JsonApiDotNetCore/assets/9092290/49fc33af-7077-48f2-9cff-b979f559d079)

**Comment by bkoelman** [comment]
This issue is not about docfx.

**Comment by bkoelman** [comment]
A different (simpler) approach is described at https://radu-matei.com/blog/dark-mode/.
