### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by btecu** [json-api-dotnet/JsonApiDotNetCore#1295]
Can the model be shared with the `EF Core` entity?
When trying, getting `Partial declarations of 'UsersController' must not specify different base classes`, but it's unclear if that's the issue.

Using the latest nuget package with `EF Core 7` and `.NET 7`, the [documentation](https://www.jsonapi.net/getting-started/step-by-step.html) steps don't seem to match, so it be great if it could be reviewed and updated.

For example https://www.jsonapi.net/usage/resource-graph.html suggests using this:
`builder.Services.AddJsonApi<AppDbContext>(discovery => discovery.AddCurrentAssembly());`

However, `.AddCurrentAssembly()` doesn't seem to exist.

**Comment by bkoelman** [comment]
Please try this instead:
```c#
builder.Services.AddJsonApi<AppDbContext>(
    discovery: discovery => discovery.AddCurrentAssembly())
```

See the named parameters at: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/4183f62ca24576a48c6fa2eeee6e16a0fb327608/src/JsonApiDotNetCore/Configuration/ServiceCollectionExtensions.cs#L20-L22

**Comment by btecu** [comment]
Thanks @bkoelman, that worked!
I'll leave the issue open in case you want to track the documentation update.

**Comment by bkoelman** [comment]
Thanks for reporting this. Updated docs are available at https://www.jsonapi.net/usage/resource-graph.html.
