### ISSUE TITLE
Can i return different request and response models from jsonapicontroller

### ISSUE THREAD

**Issue by bhavik-mittal** [json-api-dotnet/JsonApiDotNetCore#1341]
I have made a CustomController inherited from JsonApiController<Class1, long> now while returning the response i want to return class2 and while returning class2 i am getting the error that says 'Class2 does not exist in the resource graph.'

What needs to be done to resolve this issue?

**Comment by bkoelman** [comment]
Add your class to the resource graph? If would help if you shared some more info and code.

**Comment by bhavik-mittal** [comment]
public class GendersController : JsonApiController<GenderRequestModel, Guid>
{

        public GendersController(IJsonApiOptions options, IResourceGraph resourceGraph, ILoggerFactory loggerFactory, IResourceService<GenderRequestModel, Guid> resourceService) : base(options, resourceGraph, loggerFactory, resourceService)
        {
        }
		[HttpPost]
		public override async Task<IActionResult> PostAsync([FromBody] GenderRequestModel requestModel, CancellationToken cancellationToken)
        {
            var response = await _masterService.CreateAsync(requestModel);
            var record = _mapper.Map<GenderResponseModel>(response);  // using automapper
            if (record == null)
            {
                throw new JsonApiException(new ErrorObject(HttpStatusCode.Conflict)
                {
                    Title = "Internal server error in creating the record",
                    StatusCode = HttpStatusCode.InternalServerError
                });
            }
            return CreatedAtRoute("GendersGetById", new { id = record.Id }, record);
        }
}

Program.cs File - >
            services.AddJsonApi(options =>
            {
                options.Namespace = "api";
                options.UseRelativeLinks = true;
                options.IncludeTotalResourceCount = true;
                options.ValidateModelState = true;
            }, discovery =>
            {
                discovery.AddAssembly(typeof(GenderRequestModel).Assembly);
                discovery.AddAssembly(typeof(GenderResponseModel).Assembly);
            });

In the above code snippet I have a genders controller inherited from JsonApiController and GenderRequestModel is a resource but i want to do the mapping and return the response of GenderResponseModel.

Do i need to make GenderResponseModel as resource ? If i make GenderResponseModel as Resource then i get the error 
JsonApiDotNetCore.Errors.InvalidConfigurationException: 'Resource type 'GenderResponseModel' depends on 'System.Guid', which was not added to the resource graph.'

If i donot make GenderResponseModel as Resource then gets the below error:-
"errors": [
        {
            "id": "3f5626a9-c4fb-4d20-ac23-99241727a678",
            "status": "500",
            "title": "An unhandled error occurred while processing this request.",
            "detail": "Data being returned must be resources, operations, errors or null."
        }
    ],

**Comment by bkoelman** [comment]
Thanks for the clarification.

It looks like you don't quite understand what this project is about. It would help to familiarize yourself with JSON:API, which is what this project implements. At a high level, JSON:API defines resources and the relationships between them, similar to relational database tables and keys. CRUD operations provide access to them, along with operators to filter, sort, paginate, select sparse fieldsets and side-load related resources.

There's no concept of request/response models in REST APIs. I recommend to read the JSON:API spec and our documentation website if you still want to use this project.

**Comment by bhavik-mittal** [comment]
Thanks for clarification
