### ISSUE TITLE
Base Abstract Resource with Generics

### ISSUE THREAD

**Issue by kostas-kapasakis** [json-api-dotnet/JsonApiDotNetCore#1360]
Hello guys .

I have been trying to create a base class with generics , in order to remove boilerplate code for all the derived resources classes.
But unfortunately it seems that it cannot work , due to the error below , which in a way makes sense.

**JsonApiDotNetCore.Errors.InvalidConfigurationException: Resource type 'Iwcp.Rest.Domain.Entities.Common.ResourceHistoricalRecord`4[TResourceId,TAction,TSnapshot,TDeltaMetadata]' depends on 'TSnapshot', which was not added to the resource graph.**

#### DETAILS

I have this base class 

    public abstract class ResourceHistoricalRecord<TResourceId, TAction, TSnapshot, TDeltaMetadata> : 
    Identifiable<TResourceId>,
        IHistoricalEntity<TResourceId, TAction, TSnapshot, TDeltaMetadata>  
        where TAction: Enum  
        where TSnapshot: class
        where TDeltaMetadata: class
    {
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column]
        public required Guid CorrelationId { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("ResourceId")]
        public required TResourceId ResourceId { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("Action")]
        public TAction Action { get; set; } = default!;

        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("CreatedBy")]
        public int CreatedById { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("AddedAt")]
        public required DateTimeOffset AddedAt { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "new")]
        [Column("New")]
        public TSnapshot? New { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "previous")]
        [Column("Previous")]
        public TSnapshot? Previous { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "deltaMetadata")]
        [Column("DeltaMetadata")]
        public TDeltaMetadata? DeltaMetadata { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude)]
        [ForeignKey(nameof(CreatedById))]
        public User CreatedBy { get; set; } = null!;
    }

Which implements the following interface

       public interface IHistoricalEntity<TResourceId, TAction, TSnapshot, TDeltaMetadata>
       {
        public Guid CorrelationId { get; set; }

        public TResourceId ResourceId { get; set; }
        
        public TAction Action { get; set; }
        
        public int CreatedById { get; set; }
        
        public DateTimeOffset AddedAt { get; set; }
        
        public TSnapshot New { get; set; }
        
        public TSnapshot? Previous { get; set; }
        
        public TDeltaMetadata? DeltaMetadata { get; set; }
        
        public User CreatedBy { get; set; }
        
       }

And then I am creating derived classes like below

           [Resource(GenerateControllerEndpoints = JsonApiEndpoints.None, PublicName = "ExampleDerivedHistoryRecord")]
           [Table("ExampleDerivedHistoryRecord")]
           public class ExampleDerivedHistoryRecord:
              ResourceHistoricalRecord<int, CommonResourceActions, ExampleDerivedHistoryRecordSnapshot,
             ExampleDerivedHistoryRecordDeltaMetadata>
             { }
    
 

But unfortunately I am facing the issue above.
I thought of creating a base abstract class of a snapshot class and then somehow , each new derive class overrides the TSnapshot with a snapshot derived class but could not make it work.

Any ideas of how something like that could work , or the only way is to remove these properties that require generics and repeat them in each derived resource ?

Thanks in advance.

#### VERSIONS USED
- JsonApiDotNetCore version: 5.3.0
- ASP.NET Core version: .NET 7
- Entity Framework Core version: 7.0.1
- Database provider: SQL Server

**Comment by bkoelman** [comment]
It's unclear to me what you're trying to accomplish. Many types are missing,  can you provide a complete example? Do you intend to publicly expose nheritance through your API, or is this just internal to reduce duplicate code? In the latter case, I don't see why the type needs to be added to the resource graph. Are you aware that SQL Server has built-in efficient support for historical tables? https://www.learnentityframeworkcore.com/misc/temporal-tables

**Comment by kostas-kapasakis** [comment]
Hey @bkoelman thanks for replying.

I had considered the proposed solution but unfortunately we have very custom needs for historical , thus we need to be able to fully control, expand , integrate this historical changes , is not a simple audit data log.

So my intention was the later , (internal to reduce duplicate code)

I fixed the issue by adding the implementation of the IIdentifiable in the resource instead of the base class.

Meaning that now my base class is as below

`
   public abstract class ResourceHistoricalRecord<TResourceId, TAction, TSnapshotNew, TSnapshotPrevious, TDeltaMetadata>:
    IHistoricalEntity<TResourceId, TAction, TSnapshotNew, TSnapshotPrevious, TDeltaMetadata>
        where TAction: Enum
        where TSnapshotNew: class
        where TSnapshotPrevious: class
        where TDeltaMetadata: class
    {
        public TResourceId Id { get; set; } = default!;
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column]
        public required Guid CorrelationId { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("ResourceId")]
        public required TResourceId ResourceId { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("Action")]
        public TAction Action { get; set; } = default!;

        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("CreatedBy")]
        public int CreatedById { get; set; }
        
        [Attr(Capabilities = AttrCapabilities.AllowView | AttrCapabilities.AllowFilter | AttrCapabilities.AllowSort)]
        [Required]
        [Column("AddedAt")]
        public required DateTimeOffset AddedAt { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "new")]
        [Column("New")]
        public TSnapshotNew? New { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "previous")]
        [Column("Previous")]
        public TSnapshotPrevious? Previous { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude, PublicName = "deltaMetadata")]
        [Column("DeltaMetadata")]
        public TDeltaMetadata? DeltaMetadata { get; set; }
        
        [HasOne(Capabilities = HasOneCapabilities.AllowView | HasOneCapabilities.AllowInclude)]
        [ForeignKey(nameof(CreatedById))]
        public User CreatedBy { get; set; } = null!;
        
        [NotMapped]
        public string? StringId { get; set; }
        
        [NotMapped]
        public string? LocalId { get; set; }
    }

`

And when creating a new historical resource I used the following

`
    [Resource(GenerateControllerEndpoints = JsonApiEndpoints.None, PublicName = "VolumeDiscountHistoryRecord")]
    [Table("VolumeDiscountHistoryRecordsJson")]
    public class VolumeDiscountHistoryRecord : 
        ResourceHistoricalRecord<
            int, 
            CommonResourceActions,
            VolumeDiscountHistorySnapshotNew,
            VolumeDiscountHistorySnapshotPrevious,
            VolumeDiscountHistoryDeltaMetadata>,
        IIdentifiable<int>
    { }

`

**Comment by kostas-kapasakis** [comment]
Closes as found the solution
