### ISSUE TITLE
Change HasOneCapabilities.AllowSet with AllowCreate and AllowUpdate Capabilities

### ISSUE THREAD

**Issue by JohnStrim** [json-api-dotnet/JsonApiDotNetCore#1381]
**Is your feature request related to a problem? Please describe.**

In HasOne specifically you've provided only the AllowSet Capability Which allows a Relationship resource to be changed both on Post and Patch Requests. The problem is that when we have scenarios like Master/Detail Resources where each time we insert a Detail Record we are obliged to add the AllowSet Capability in order to set the relationship. But we don't want to allow changing the Master Relationship from the Detail Record which at the moment we have to implement our own logic to do. 

**Describe the solution you'd like**
We would like to request the possibility that you extend the HasOneCapabilities and include the AllowCreate and AllowUpdate Capabilities instead of the AllowSet as this will allow to perform all Payload Restrictions through your attributes and only focus on actual business logic in the internal Validators 

**Describe alternatives you've considered**
We are forced to add this logic in our Validators at the moment which is not a good thing as we have to stop our internal Validation Logic trying to match your payload rules which could be avoided.

**Comment by bkoelman** [comment]
Hi @JohnStrim, thanks for your suggestion. Unfortunately, this requires executing an additional query for one-to-one relationships where the foreign key is defined at the other side. For backwards compatibility, `AllowSet` would become `AllowCreate | AllowUpdate`, resulting in existing users experiencing this performance hit. The alternative, failing at runtime while processing a request, doesn't sound very appealing either.

A different split was suggested in #1187, but that wouldn't have solved your problem.

**Comment by bkoelman** [comment]
Sure, but there's no need to change JsonApiDotNetCore for that. See the example at #1386.

**Comment by JohnStrim** [comment]
@bkoelman my current implementation looks a lot like yours. Basically we've implemented an ImmutableAttribute and when this attribute is assigned on a property if it shows up in the targettedFields after having been assigned before we return a Forbidden error code.
The problem with this is that we've put it in a central validation we have and we are forced to break the rest of our validation process in order to execute it. Also our format doesn't match exactly your error format but I understand this is our only alternative at the moment. Thank you!

**Comment by bkoelman** [comment]
It should be easy to create your own generic base class that implements `IResourceDefinition` and register it as an open type. If you need more help, please provide a minimal sample that I can change to show how to do that.
