### ISSUE TITLE
How to remove the id and links in the errors

### ISSUE THREAD

**Issue by bhavik-mittal** [json-api-dotnet/JsonApiDotNetCore#1434]
The errors that gets thrown from the apis contains id and links but as per json:api documentation those are not required if your error contains other fields such as title or detail. How can we achieve removing id and links from the errors being thrown ?

**Comment by bkoelman** [comment]
JADNC is very pluggable, please search/debug the sources a bit before asking such questions next time. In this case, you can override `ExceptionHandler.CreateErrorResponse`. I would recommend to keep Id though. When a consumer reports a problem, you can search your logs to obtain more details about what happened.

**Comment by bhavik-mittal** [comment]
Ok thanks
