### ISSUE TITLE
Support links in resource objects (DocumentData)

### ISSUE THREAD

**Issue by OKTAYKIR** [json-api-dotnet/JsonApiDotNetCore#144]
How can I create links object using noentityframework such as the following;

```
{
	"data": {
		"type": "user",
		"id": "1f42940ba0b046188b46ff43c6872eb4",
		 "links": {
			  "self": "https://www.example.com/api/v1/users/1f42940ba0b046188b46ff43c6872eb4"
			},
		"attributes": {
			"givenName": "Fyodor Mikhailovich",
			"familyName": "Dostoyevsky"
		}
	}
}
```

**Comment by jaredcnance** [comment]
We do not currently support links objects _within_ the resource object. However, I see no reason we shouldn't. I'm fine with adding this as a feature targetted for a 2.1.x release. Is this a blocker for your use case?

**Comment by OKTAYKIR** [comment]
I need to use in the future but at the moment is not urgent.

Thanks

**Comment by amit-ch** [comment]
Is it possible to generate links object manually outside of resource objects with noentityframework. For example when I do get all, I should be able to generate first and last links 
`
{
    "data": [
        {
            "attributes": {
                "isActive": false
            },
            "type": "organisation",
            "id": "1243"
        }
    ],
    "links": {
        "last": "https://localhost:44346/organisation?page[size]=10&page[number]=10",
        "first": "https://localhost:44346/organisation?page[size]=10&page[number]=1"
    }
}
`

**Comment by amit-ch** [comment]
I am able to access PageManager just before serving the response and give values for total records and current page which is generating the links fine. If there is some other neat way of doing it, please let me know. Thanks.

**Comment by maurei** [comment]
@amit-ch that sounds like the way I'd try to solve it

**Comment by maurei** [comment]
Introduced in #558
