### ISSUE TITLE
Passing Multiple GUIDs in Query String as List Parameter

### ISSUE THREAD

**Issue by abhinavchauhan12** [json-api-dotnet/JsonApiDotNetCore#1446]
I have a attribute `List<Guid> Ids;` in my resource . How to pass the Ids in `filter[Ids]` such that I could retrieve my Ids from query layer ?

Because , I have  used the below endpoint :- 
`https://localhost:7004/test/?filter[Ids]=d06eb7db-43ff-4c47-8714-f364bcc07e0b,6c23191b-48cb-4e9a-bcad-2783105898fe`
but faced the below error :- 

```
"status": "400",
            "title": "The specified filter is invalid.",
            "detail": "Failed to convert 'd06eb7db-43ff-4c47-8714-f364bcc07e0b' of type 'String' to type 'List`1'.",
            "source": {
                "parameter": "filter[Ids]"
            }
```

**Comment by bkoelman** [comment]
This is currently not possible. There's a workaround at https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/1370#issuecomment-1782216704 by storing your list as a separated string. Adding support for filtering inside non-primive objects (including collections) is tracked at #1439.

Closing as a duplicate.
