### ISSUE TITLE
EF many-to-many support

### ISSUE THREAD

**Issue by LeonidEfremov** [json-api-dotnet/JsonApiDotNetCore#151]
As I understand this is not supported? Can you add this ability?

**Comment by jaredcnance** [comment]
EF Core does not support many to many relationships without a join table. Ref https://github.com/aspnet/EntityFramework/issues/1368

Am I misunderstanding the question?

**Comment by LeonidEfremov** [comment]
You right, we have to use another entity to link main entities. Can you provide example for model decoration, f.e. Product - ProductTag - Tag. When I call GET /products/?include=tags I have to get Tags list, - how I can reach this?

**Comment by jaredcnance** [comment]
The json:api way of doing this would be to leverage deeply nested inclusions using relationships paths:

> Note: For example, a relationship path could be comments.author, where comments is a relationship listed under a articles resource object, and author is a relationship listed under a comments resource object.

>Note: A server may choose to expose a deeply nested relationship such as comments.author as a direct relationship with an alias such as comment-authors. This would allow a client to request /articles/1?include=comment-authors instead of /articles/1?include=comments.author. By abstracting the nested relationship with an alias, the server can still provide full linkage in compound documents without including potentially unwanted intermediate resources.

However, this is [not currently supported](https://github.com/Research-Institute/json-api-dotnet-core/issues/39). You may be able to implement a workaround at the repository layer ([here](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L158) and [here](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L102)). The other thing you would need to do is add a property on the model like so:

```csharp
class Product {
  // ... 
  [NotMapped]
  [HasMany("tags")]
  public List<Tag> Tags { get; set; }
}
```

Then in the repository, you should be able to do something like:

```csharp
public virtual async Task<Product> GetAndIncludeAsync(int id, string relationshipName)
{
    if(relationshipName == "tags") {
        return await Get()
            .Include(p => p.ProductTags)
            .ThenInclude(pt => pt.Tags)
            .SingleOrDefaultAsync(e => e.Id.Equals(id));
    }
    else {
        return await base.GetAndIncludeAsync(id, relationshipName);
    }
}
```

The above is pseudo code that has not been compiled or tested, but is the approach I would take for now.

Regarding direct support of many-to-many relationships, I do not plan on supporting that until EF Core supports it. However, I am open to working on deeply nested inclusions in the near future. My current focus is on #150 (Operations Support). Once that lands I'd be happy to move onto deeply nested inclusions.

**Comment by LeonidEfremov** [comment]
Thank you, now is clear.

**Comment by jaredcnance** [comment]
@LeonidEfremov please feel free to ping me on the project gitter channel if you need any support.

**Comment by thomasirmer** [comment]
@LeonidEfremov 
I know this has been closed a while ago. Did you figure out how to solve it? And did Jared's suggestion work for you?

Thanks!

**Comment by jaredcnance** [comment]
@thomasirmer the above solution is how we're using it in other projects. However, after some thought I think it would be good to support this feature even after EF provides direct support for Many-To-Many w/o a join table. The API might look something like:

```c#
public class Product : Identifiable 
{
  [NotMapped]
  [HasMany("tags", through: nameof(ProductTags), by: ProductTag.Tag)]
  public List<Tag> Tags { get; set; }

  public virtual List<ProductTag> ProductTags { get; set; }
}
```
