### ISSUE TITLE
ASP.Net Core v2 Support and Versioning

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#161]
One of the major issues here pertains to how this library as a whole is going to approach versioning with the AspNetCore packages. The current version (v2.1.4) targets `Microsoft.AspNetCore.*` 1.1.2+. 

### Support Checklist
- [x] .props file
- [x] Update examples
- [x] Update tests

## Update

Below is the planned version scheme:

| JADNC Version   | AspNetCore Version | Operations Support |
|-----------------|--------------------|--------------------|
| 2.1.10 (current)  | 1.1.*                         | -                               |
| 2.1.?                    | 1.1.*                         | ✓                             |
| 2.2.0-beta          | 2.0.*                        | -                              |
| 2.2.0                   | 2.0.*                        | ✓                             |
| 3.0.*                   | 3.0.*                        | ✓                             |
| 3.1.*                    | 3.1.*                         | ✓                            |

**Comment by thomasirmer** [comment]
Hi Jared,
I'm just digging into JsonApiDotNetCore. Does this issue mean, that it is not yet available for .NET core 2.0?
Thanks

**Comment by jaredcnance** [comment]
Are you asking about AspNetCore 2.0 or the 2.0 runtime?

You should be able to use it on any runtime (including .Net Core 2.0) that implements netstandard1.6. This issue is about the AspNetCore versions referenced by the library. 

If you're referring to the runtime, can you post your csproj, Program.cs, Startup.cs, and a controller?

If you're referring to The Microsoft.AspNetCore.* packages, please know this is a high priority issue and we hope to have this resolved soon.

**Comment by thomasirmer** [comment]
Oh sorry for not mentioning that. I was referring to AspNetCore. I'll stay tuned for any updates then.

Thanks.
