### ISSUE TITLE
Skip serializing Dictionary Keys using Camel Case and preserve their Original Case

### ISSUE THREAD

**Issue by JohnStrim** [json-api-dotnet/JsonApiDotNetCore#1622]
#### SUMMARY
In our API we are using your library and as expected it converts all properties to camel case which is expected. The same principle though affects Dictionary Keys and therefore changes their original Casing pattern which is a bad for our implementation. Is there a way in JsonOptions to force Json.Api to skip Dictionary Keys from its Camel Case Pattern?

#### STEPS TO REPRODUCE
Here is how a property of Dictionary<string, string> is serialized, that some keys's originally were with Capital first letter.
```json
"fields": {
                "gateway": "https://local/api",
                "clientId": "asdfasdfasdfasdf",
                "field1": "xf6kadfadfasdfasdfada",
                "field2": "EUR",
                "field3": "2",
            },
```
-->

**Comment by bkoelman** [comment]
Yes, just change the [default setting](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/eb2ef95b29e0f4f33b891ec8dbc0ff96be8be53d/src/JsonApiDotNetCore/Configuration/JsonApiOptions.cs#L101-L117) for [DictionaryKeyPolicy](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.dictionarykeypolicy?view=net-8.0) in serializer options at startup:
```c#
services.AddJsonApi<AppDbContext>(options => options.SerializerOptions.DictionaryKeyPolicy = null);
```
Setting it to `null` activates the default policy, which is pascal casing.

**Comment by JohnStrim** [comment]
Worked like a charm! Thank you very much!
