### ISSUE TITLE
Potential issue with patch

### ISSUE THREAD

**Issue by nialljt1** [json-api-dotnet/JsonApiDotNetCore#175]
I am having a problem with Patch on all my entities. Get, Post and Delete are all working as expected. When a send a Patch it returns a status of 200 but the field I have specified hasn't been updated. It is like all entity properties have immutable set to true, which is not the case. Apologies if this is something obvious that I have missed. I attached details of the entity definition and details of an API call.
[Patch Issue.txt](https://github.com/json-api-dotnet/JsonApiDotNetCore/files/1383997/Patch.Issue.txt)

**Comment by jaredcnance** [comment]
@nialljt1 maybe I'm misunderstanding something, but the body in your attachment is not a valid json:api document? or did you simplify the payload?

**Comment by nialljt1** [comment]
Apologies. My fault. Please close this. You were right I hadn't the correct format in the body. Also, I hadn't set the Content-Type to "application/vnd.api+json" in the header. Sorry for wasting your time.
