### ISSUE TITLE
Allow overriding more JsonSerializerSettings

### ISSUE THREAD

**Issue by dnperfors** [json-api-dotnet/JsonApiDotNetCore#185]
Currently it is already possible to change the default `JsonContractResolver`. However it is not possible to change other settings (like adding the StringEnumConverter) for just JsonApiDotNetCore (it is possible to change the global default settings via `JsonConvert.DefaultSettings`)

Is there a reason why this is not possible? If not, I am happy to provide a PR where it is possible to change all settings.

**Comment by jaredcnance** [comment]
A PR would be appreciated 👍
