### ISSUE TITLE
Support custom filter strategy

### ISSUE THREAD

**Issue by dnperfors** [json-api-dotnet/JsonApiDotNetCore#186]
Filtering is not really specified in the jsonapi.org specification and we have actually chosen an other filter strategy than is implemented in JsonApiDotNetCore.
Would it be possible/desirable to make the parsing of query strings more adaptable, so that we can override the `ParseFilterQuery` method to support queries like `filter[attribute][lt]=value` instead?

**Comment by jaredcnance** [comment]
I agree that this is an area where we need to be more flexible. What I would like to see happen is the parsing logic moved out of `QuerySet` into an injectable service. The way it is currently written, `JsonApiContext` [implicitly depends on](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Services/JsonApiContext.cs#L66) `QuerySet` which contains the parsing logic. There should be a service which parses the queries and returns the built `QuerySet`
