### ISSUE TITLE
DocumentBuilder crashes when building Arrays

### ISSUE THREAD

**Issue by shuebner** [json-api-dotnet/JsonApiDotNetCore#200]
Method `DocumentBuilder.Build(IEnumerable<IIdentifiable> entities)`:

When `entities` is an Array (and thus not a generic type) .GenericTypeArguments[0] crashes with IndexOutOfRangeException.

Does anything speak against the following simple fix?

```csharp
var entitiesType = entities.GetType();
var entityType = entitiesType.IsArray ? entitiesType.GetElementType() : entitiesType.GenericTypeArguments[0];
```

**Comment by jaredcnance** [comment]
That sounds reasonable to me. Would you like to open a PR?

**Comment by shuebner** [comment]
The same thing happens with HashSet. I will file another pull request. Please disregard #202 at your convenience.
