### ISSUE TITLE
Creation format

### ISSUE THREAD

**Issue by Nono31** [json-api-dotnet/JsonApiDotNetCore#201]
Hello,
It look like JsonApiDotNetCore doesn't respect the post format:
http://jsonapi.org/format/#crud-creating
Is it plan ? Or hard to implement ?

**Comment by jaredcnance** [comment]
It does (see the sample request below from our test suite).
- What response are you receiving?
- Have you verified the request `Content-Type = "application/vnd.api+json"` ?
- Are there additional details you can provide?

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/0ff419b758e2f3bfbdae21aefd69efe596c58e20/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/CreatingDataTests.cs#L56-L77

**Comment by Nono31** [comment]
My bad I was only use application/json
