### ISSUE TITLE
NotFound("Test") Exception

### ISSUE THREAD

**Issue by Nono31** [json-api-dotnet/JsonApiDotNetCore#203]
Hello
When I add some text on return NotFound("Test") on your getbyid CustomJsonApiController I have an error:
```
{
    "errors": [
        {
            "title": "Object reference not set to an instance of an object.",
            "status": "400"
        }
    ]
}
```
It's try to serialize my text instead of returning a 404

**Comment by jaredcnance** [comment]
How are you imagining the text should be handled? Typically, I would expect a simple `HTTP 404` Status Code with no error message since the semantics of 404 are pretty clear. But, I suppose in the event of an error, we could generate an error document:

```json
{
    "errors": [{
        "title": "Test.",
        "status": "404"
    }]
}
```

What is your use case here?

**Comment by Nono31** [comment]
I Use mongodb so I implement a ResourceService, when my GetRelationshipAsync don't found a relationship entity I throw throw new JsonApiException(404, $"Relationship {relationshipName} not found.");

**Comment by jaredcnance** [comment]
@Nono31 that is a different situation than what you described in the first issue. The original issue is about returning 404 with a string (`return NotFound("Test")`). What you just described (throwing an exception) is unrelated and are 2 execution paths.

**Comment by Nono31** [comment]
The Object reference not set to an instance of an object. Exception is throw in the same place on both cases

**Comment by jaredcnance** [comment]
Can you please submit an example.

If you're calling `return NotFound()` AND an exception is being thrown by the `ResourceService`, then you must be implementing different exception handling. Typically the code path looks like:
```
Controller → Service (returns null if not found) → Controller returns 404
```
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/a4f437092f89737489930ce7bd6a5277c8d8d194/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L121-L122

If a `JsonApiException` is thrown in the service, it should be unhandled by the controller:
```
Controller → Service throws → Serializer creates error document
```

**Comment by jaredcnance** [comment]
Closing due to lack of detail. Please reopen if you can provide more detail.
