### ISSUE TITLE
Expose CQRS constructor on JsonApiController

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#205]
Users should be allowed to expose all endpoints, but define the allowable actions by the provided constructor arguments.

So, instead of:

```csharp
public class TodoItemsController : BaseJsonApiController<TodoItem>
{
    public TodoItemsController(
        IJsonApiContext jsonApiContext,
        ICreateService<TodoItem> create) 
        : base(jsonApiContext, create: create)
    { }

    [HttpPost]
    public override async Task<IActionResult> PostAsync([FromBody] T entity) => await base.PostAsync(entity);
}
```

you can:

```csharp
public class TodoItemsController : JsonApiController<TodoItem>
{
    public TodoItemsController(
        IJsonApiContext jsonApiContext,
        ICreateService<TodoItem> create) 
        : base(jsonApiContext, create: create)
    { }
}
```

all other methods should return `HTTP 405 Method Not Allowed`

**Comment by wayne-o** [comment]
Hey, could you provide some background on this? Think the CQRS part is confusing me :p

**Comment by jaredcnance** [comment]
CQRS isn't the best way to describe this. Basically, we allow limiting of the allowed HTTP queries and commands per operation. This is done through interface segregation. Implementations of `IResourceService` also implement the following:

```
IGetAllService<T, TId>
IGetByIdService<T, TId>
IGetRelationshipsService<T, TId>
IGetRelationshipService<T, TId>
ICreateService<T, TId>
IUpdateService<T, TId>
IUpdateRelationshipService<T, TId>
IDeleteService<T, TId>
```

However, your services are not required to implement ALL of them. As an example, I could have a custom `FooAggregate` that represents an aggregate of other resources backed by an ad hoc query and should be read-only. By using the following constructor overload, the only allowed route will be `GET /foo-aggregates`. All other routes will return `HTTP 405`. 

```csharp
public class FooAggregatesController : JsonApiController<FooAggregate>
{
    public TodoItemsController(
        IJsonApiContext jsonApiContext,
        IGetAllService<FooAggregate> getAll) 
        : base(jsonApiContext, getAll: getAll)
    { }
}
```

As far as background goes, the interface segregation was originally done in support of #150 (Multiple Operations per Request Support - official Operations json:api proposal by dgeb should be landing in the next few weeks).

**Comment by wayne-o** [comment]
gotcha :) basically more fine grained support over the operations supported on an endpoint - been playing about with this project in one of my side projetcs and have to say, it's pretty amazing stuff - really good :)

**Comment by jaredcnance** [comment]
Exactly. That's awesome. Always glad to get user feedback.
