### ISSUE TITLE
Other Id name

### ISSUE THREAD

**Issue by wdmeeste1** [json-api-dotnet/JsonApiDotNetCore#206]
Is their away to set your own Id without implementing the Id of Identifiable?

I have multiple classes where following has set for Id:

```
[Key]
public int ID { get; set; }
```

**Comment by jaredcnance** [comment]
No, by implementing the interface (`IIdentifiable`) or base class (`Identifiable`), it allows us to avoid some runtime reflection. You could override the `Id` property and use it as a proxy to `ID`, and set your key as `JsonIgnore` to prevent ambiguity during serialization/deserialization. Something like :
 
```csharp
class Foo : Identifiable {
  [NotMapped] // ← if you're using Entity Framework
  public override int Id { 
    get => ID;
    set => ID = value; 
  }

  [Key, JsonIgnore]
  public int ID { get; set; }
}
```

that hasn't been tested at all, so let me know if it doesn't work for you.

**Comment by wdmeeste1** [comment]
Thxs that works!
