### ISSUE TITLE
Inconsistent casing for sort and filter queries

### ISSUE THREAD

**Issue by shuebner** [json-api-dotnet/JsonApiDotNetCore#209]
I noticed that in a query, for the sort criteria casing does not matter while for the filter criteria the exact name is needed in the URL.
E. g. `[Attr("fileName")]` can be used for sorting with `?sort=filename`, but can only be used for filtering with `?filter[entity]=fileName` while `?filter[entity]=filename` does not work.

Is that on purpose?

**Comment by jaredcnance** [comment]
It's not intentional and is an artifact from a prior approach that apparently didn't get cleaned up properly in `QueryParser`. It does a `

**Comment by shuebner** [comment]
That last comment got cut apparently.

So, are you fixing this or should I prepare a PR?

**Comment by jaredcnance** [comment]
☝️

**Comment by shuebner** [comment]
I won't be able to make PR until next week.
