### ISSUE TITLE
Restrict maximum page size per resource

### ISSUE THREAD

**Issue by firedigger** [json-api-dotnet/JsonApiDotNetCore#217]
Currently, ApiJson app divides massive data into pages. 
Default page size is 10 instances of data.
By adding an argument `?page[size]=5"&"page[number]=2` data will be split into pages that contain 5 instances on each page and it will show page #2.
I would like to be able to specify the maximum page size for my resources so that too massive queries are impossible. Something like an Attribute for the resource class with an int parameter and an exception if the requested page size exceeds it (or just return the maximum page size in that case).

**Comment by jaredcnance** [comment]
I agree an attribute makes sense, we don't currently have any attributes on the resource level. I would suggest a `PaginatedResourceAttribute` that might look like:

```csharp
[PaginatedResource(allowPagination: true, maxPageSize: 10, defaultPageSize: 5)]
public class ArticlesResource { /*...*/ }
```
