### ISSUE TITLE
Filtering on custom ResourceService returns all data

### ISSUE THREAD

**Issue by wim-jan** [json-api-dotnet/JsonApiDotNetCore#230]
I'm sure I'm missing something from the documentation, but I can't get the filter on my resource working. For full clarification, I'm not using Entity Framework but rather MongoDB.

I'm working on the following setup:

```c#
public class Foo : Identifiable<Guid>
{
  public override Guid Id { get; set; }
  
  [Attr("fooAttribute")]
  public string FooAttribute { get; set; }
}

public class FooController : JsonApiController<Foo, Guid>
{
  public FooController(IJsonApiContext jsonApiContext, IResourceService<Foo, Guid> resourceService) : base(jsonApiContext, resourceService)
  {
  }
}

public class FooResourceService : IResourceService<Foo, Guid>
{
  private readonly IFooRepository _fooRepository; // My custom repository that connects to MongoDB

  public function FooResourceService(IFooRepository fooRepository)
  {
    _fooRepository = fooRepository;
  }

  public async Task<IEnumerable<Foo>> GetAsync()
  {
    return await _fooRepository.FindAllAsync(); // Let's just assume this returns something of type Foo
  }

  // Snip
}
```

With the following configuration:
```c#
var mvcBuilder = services.AddMvc();
services.AddJsonApi(opt =>
{
  opt.Namespace = "api/v1";
  opt.BuildContextGraph(builder =>
  {
    builder.AddResource<Foo>("foo");
  });     
}, mvcBuilder);

services.AddScoped<IFooRepository, FooRepository>();
services.AddScoped<IResourceService<Foo, Guid>, FooResourceService>();
```

Now, when requesting `/api/v1/foo`, I get all kinds of `Foo`'s like this:

```json
{
  "data": [
    {
      "type": "foo",
      "id": "42cb8061-a91e-400c-ac9a-1d5a7d6d0220",
      "attributes": {
        "fooAttribute": "bar"
      }
    },
    {
      "type": "foo",
      "id": "DFBB5D3D-A8A2-4839-973A-9185816EEFE4",
      "attributes": {
        "fooAttribute": "qoox"
      }
    }
  ]
}
```

Excellent! Now I want to filter on `fooAttribute` by requesting `/api/v1/foo?filter[fooAttribute]=bar`. But this results in the exact same resultset... 

Am I missing something obvious?

**Comment by wim-jan** [comment]
To answer my own question: I've sort of copied the filter function from the `EntityResourceService` to my own ResourceService:

```c#
protected IQueryable<TEntity> ApplySortAndFilterQuery(IQueryable<TEntity> entities, IJsonApiContext context)
{
  var query = context.QuerySet;

  if (context.QuerySet == null)
    return entities;

  if (query.Filters.Count > 0)
  {
    foreach (var filter in query.Filters)
    {
      var attrFilter = new AttrFilterQuery(context, filter);
      entities = entities.Filter(attrFilter);
    }
  }

  if (query.SortParameters != null && query.SortParameters.Count > 0)
    entities = entities.Sort(query.SortParameters);

  return entities;
}
```

**Comment by jaredcnance** [comment]
So, were you able to solve your problem? depending on your Mongo client, you should just be able to substitute the `IEntityRepository` implementation. Work was done in #211 to ensure this was possible. If that doesn't work for you, then you should be able to override `GetAsync()` but only replace the parts you need replaced.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b06ce62a3bce0656f3865dd19e65a2263e02b346/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L42-L57

Specifically, this is probably what should be replaced with your ` _fooRepository.FindAllAsync()`.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b06ce62a3bce0656f3865dd19e65a2263e02b346/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L44

Everything else can stay the same as long as you can return an `IQueryable<Foo>`

**Comment by wim-jan** [comment]
@jaredcnance Yes, I was able to fix my problem.

Regarding your proposed solution, this indeed only works when the repository returns an `IQueryable<Foo>`. The problem with my implementation however is that my repository does not return an `IQueryable<Foo>` but rather an `IQueryable<SomethingThasBecomesFoo>`. I'm working with a strict separation between the view-layer and the data-layer and thus can not create a repository that returns the `IQueryable<Foo>` as `Foo` is only something that makes sense on the view.

**Comment by jaredcnance** [comment]
Closing this issue. Please feel free to re-open if you're still having issues.
