### ISSUE TITLE
Formatting only

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#235]
I appologise if this isn't the place for this question. 

I want to use JsonApiDotNetCore for the majority of reads in my API but for some I don't want to use the EF stuff - where the endpoint actually needs to call a backend service to retrieve the objects to send out in JSON  API format.

Is there a way to use this library to format the response only?

**Comment by wayne-o** [comment]
I just found this:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/Examples/ReportsExample/Services/ReportService.cs

I guess this is the way to go?

**Comment by wayne-o** [comment]
In fat I can see it is :)

CLosing this now - sorry for the noise!

**Comment by jaredcnance** [comment]
That's right! Generally you would just implement the required service. Check out the docs too https://json-api-dotnet.github.io/#/resource-services

If you need any assistance feel free to post back here.

**Comment by wayne-o** [comment]
I think I'll be good from here - thanks for getting back to me :)
