### ISSUE TITLE
Allow filtering on properties of HasMany relationships

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#238]
Consider the following:

```csharp
public class Foo : Identifiable
{
   [HasMany("bars")]
   public List<Bar> Bars { get; set; }
}

public class Bar : Identifiable
{
   [Attr("isActive")] public bool IsActive { get; set; }

   [HasOne("foo")]
   public Foo Foo { get; set; }
   public int FooId { get; set; }
}
```

If you try to filter
```
/foos?filter=bars.isActive=true
```

It will result in an exception

```
ArgumentException: 'IsActive' is not a member of type 'System.Collections.Generic.List`1[Bar]'
Parameter name: propertyOrFieldName
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at JsonApiDotNetCore.Extensions.IQueryableExtensions.Filter[TSource](IQueryable`1 source, RelatedAttrFilterQuery filterQuery)
   at JsonApiDotNetCore.Services.EntityResourceService`2.ApplySortAndFilterQuery(IQueryable`1 entities)
   at JsonApiDotNetCore.Services.EntityResourceService`2.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JsonApiDotNetCore.Controllers.BaseJsonApiController`2.<GetAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JsonApiDotNetCore.Controllers.JsonApiController`2.<GetAsync>d__3.MoveNext()
```

We should consider an approach similar to [EF Plus's IncludeFilter](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryIncludeFilter.Shared/Extensions/IQueryable%60.IncludeFilter.cs) : http://entityframework-plus.net/query-include-filter

### Workaround

The current workaround is to query the child resource directly and expose the parent id as an attribute on the resource:

```
GET /articles?filter[authorId]=1&filter[isActive]=true
```

**Comment by XaserAcheron** [comment]
This is really kicking my rump -- I'm trying to do this with a HasManyThrough relationship so the posted workaround doesn't apply. Any advice, by chance?

**Comment by maurei** [comment]
@XaserAcheron is this still an issue? We can consider looking into it after releasing 3.2.0

**Comment by XaserAcheron** [comment]
It's still a bit troublesome -- I ended up having to do some non-ideal workarounds from the UI side in order to get around the limitation -- but I'm not critically blocked or anything, thankfully. :)

Thanks for the help, BTW!

**Comment by maurei** [comment]
That is, indeed, suboptimal. I think this issue is one of the more workable issues so we might still look into it after v3.2.0. Also, you are encouraged to get started on it (in which case you can PM me with any questions)

**Comment by wisepotato** [comment]
@maurei this would be easily done in the new filtering/hooks backend.

**Comment by maurei** [comment]
In that case you'd have to "hardcode" the filter in a hook, which doesnt allow for much flexibility like when filters are added dynamically with query params. 

Although might be possible to inject JsonApiContext in the hooks and access the url query params as such, that feels hacky. I think it should be supported off the shelve

**Comment by wisepotato** [comment]
I meant that we can parse the query filters and apply them on the needed items, as we are parsing them in memory anyway, refardless of hooks
