### ISSUE TITLE
Make most service layer methods protected

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#239]
Currently, almost any customization no matter how small results in a lot of code copying because many methods in the service layer are private. These should be protected so derived classes may use the base class implementations without copying code.

**Comment by wayne-o** [comment]
I was going to add this exact issue! I’ll try and submit a PR for it over the weekend

**Comment by maurei** [comment]
This is still an issue for the repository layer
