### ISSUE TITLE
Document client library specific usage

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#240]
Client libraries will differ. We should document some of the differences and things you may need to do for each client.

### OrbitJS

- Kebab Cased Filters: orbit cases the filters as kebab-case but expects camelCased responses
  - https://github.com/orbitjs/orbit/issues/488

### EmberJS

- ...

**Comment by bart-degreed** [comment]
Closing this, as the current JADNC team has no experience with these client libraries.

**Comment by maurei** [comment]
[There is actually one that I built myself for angular](https://github.com/maurei/ngx-api-orm)

**Comment by wayne-o** [comment]
Ember data plays nicely too :)

**Comment by wayne-o** [comment]
OK so the new query style stuff doesn't work at all with ember-data :/

That's quite painful
