### ISSUE TITLE
Does this work with fsharp?

### ISSUE THREAD

**Issue by NullVoxPopuli** [json-api-dotnet/JsonApiDotNetCore#244]
just wondering, wanting to build a json:api api with fsharp, and this library seems the most feature-complete.

I guess, alternatively, is there a way to _just_ use the (de)serialization parts? cause then I could just use whatever web server

**Comment by jaredcnance** [comment]
Regarding F#, I'm not sure. I've honestly never tried it, but there's no obvious reason (to me) why it shouldn't work. I'd be happy to work with you on it if you need any support. Regarding **just** serialization, that's a very small part of this library and while it is part of our roadmap to make that possible, there is [one blocker](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/237) at the moment.

**Comment by NullVoxPopuli** [comment]
Sounds good, yeah, I'll give it a go. F# has objects and stuff, cause all of dotnet is compatible with all dotnet-languages. F# doesn't have all the OO features that C# does, but that's fine. 

I guess, re: just (de)serialization, I'm mostly wanting to have the functionality provided by http://jsonapi-rb.org
which is:
 - (de)serialization of POROs / AR objects (equiv: POJOs / EF Entities)
 - still being able to use include and sparse fieldsets
 - choosing to, by default, not render the relationship data if the relationship is not 'inpcluded' (useful for has many relationships, because for my purposes, a list of id/types isn't meaningful, and I'd like to save the db accesses. :-)
 - build error objects

I'm still pretty new to F#/dotnet web dev, and so far, it seems that this library has all the features I'd want (even if it has more, and I'd be using a subset).

The reason why I don't _really_ want to use a jsonapi _only_ web framework is just in case I need an endpoint with non-jsonapi format.

As for web frameworks, I've been looking at
https://github.com/SaturnFramework/Saturn, which is Giraffe-based -- so I was hoping to use jsonapidotnetcore with that :-)

anywho, I'll start playing with this in F#, and see what happens

**Comment by maurei** [comment]
Interested to know what you learned from this. Closing as no further action required.
