### ISSUE TITLE
Allow actions to accept other contents than JSON

### ISSUE THREAD

**Issue by soldag** [json-api-dotnet/JsonApiDotNetCore#257]
It would be nice, if actions or controllers could be excluded from the request content type check in the `RequestMiddleware`. 

I'd like to add the possibility to upload the file to my JSON API application. This is currently not possible, because requests with other content types than `application/vnd.api+json` are rejected by the middleware with a 415 response.

**Comment by jaredcnance** [comment]
Hi @soldag, the only time our framework will return a 415 is (from the spec) 
> if a request specifies the header Content-Type: application/vnd.api+json with any media type parameters.

So, unless you're passing in something like `Content-Type: application/vnd.api+json; version=2` the 415 should not be coming from this framework.

I ran a quick test by adding the following method to [the example app](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e7c65db8cf9bcd064eb7001703b8a2238095ee4f/src/Examples/JsonApiDotNetCoreExample/Controllers/TestValuesController.cs#L5-L14):

```c#
[HttpPost]
public IActionResult Post([FromBody] object content) => Ok(content);
```

And sent the following request:

```http
POST /testValues HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
  "key": "value"
}
```

Received response:

```http
HTTP/1.1 200 OK
Date: Wed, 11 Apr 2018 09:52:52 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel

{
  "key":"value"
}
```

The media type check takes place in our middleware:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/eb2c309dfbcc78d12ead4ad676323629ec33a05a/src/JsonApiDotNetCore/Middleware/RequestMiddleware.cs#L28-L37

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e7c65db8cf9bcd064eb7001703b8a2238095ee4f/src/JsonApiDotNetCore/Middleware/RequestMiddleware.cs#L55-L59

If the content-type is not `application/vnd.api+json` our reader is never invoked:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e7c65db8cf9bcd064eb7001703b8a2238095ee4f/src/JsonApiDotNetCore/Formatters/JsonApiInputFormatter.cs#L18

I believe the 415 you're receiving is from the ASP.Net Core framework. If you can you provide some more information, I'd be happy to work through the problem with you. I would need to see your:
- `Startup.Configure` and `Startup.ConfigureService`
- The model
- The controller
- The http request your submitting (content can be excluded)

Are you uploading using the `enctype='multipart/form-data'` and binding to an `IFormFile` ? Or are you using a `MultipartReader`?

**Comment by soldag** [comment]
Hi @jaredcnance,

thanks for your quick answer. I could fix my problem with the help of your hints. I incorrectly used the `FromBody` attribute for the `IFormFile` argument of the action, which resulted in the reported error.
