### ISSUE TITLE
Doesn't work without entity framework

### ISSUE THREAD

**Issue by lecoque** [json-api-dotnet/JsonApiDotNetCore#261]
No enity framework example itself has dependency on ef

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/Examples/NoEntityFrameworkExample/NoEntityFrameworkExample.csproj

I did everything and without passing DbContext, it won't work.

> Unable to resolve service for type 'JsonApiDotNetCore.Data.IDbContextResolver' while attempting to activate 'JsonApiDotNetCore.Data.DefaultEntityRepository`...

It seems like DbContext is required no matter if I use it

**Comment by jaredcnance** [comment]
Closing, discussion moved to #292. Please reopen if you're stuck on anything.
