### ISSUE TITLE
Multiple EF contexts

### ISSUE THREAD

**Issue by joshhubers** [json-api-dotnet/JsonApiDotNetCore#269]
First off, thanks for the fantastic library. It has been extremely beneficial for my project.

Is it possible to use multiple EF Core DbContexts? I'm attempting to add two different contexts, but the second overrides the first.

Ex.

    services.AddJsonApi<ContextA>(opt =>
            {
                opt.AllowCustomQueryParameters = true;
                opt.Namespace = "api/v1";
            }, mvcBuilder);

    services.AddJsonApi<ContextB>(opt =>
            {
                opt.AllowCustomQueryParameters = true;
                opt.Namespace = "api/v1";
            }, mvcBuilder);

Where both ContextA and ContextB are EF Core DbContext's.

When I request resources from controllers that use ContextB, I get the resources as expected. When I request from controllers that use ContextA I get a
`
"ArgumentException","detail":"DbSet of type {DbSet of ContextA} not found on the DbContext"
`

Commenting out the first AddJsonApi call changes the which context is working as expected.

**Comment by jaredcnance** [comment]
Hi - yes! I am currently working on an application that has this requirement. I haven't finished validating this, but it looks something like:
```csharp
services.AddJsonApi(options => {
  options.BuildContextGraph((builder) =>
  {
     // add both contexts using the builder
     builder.AddDbContext<DbContextA>();
     builder.AddDbContext<DbContextB>();
  });
}, mvcBuilder);
```

Register new `IDbContextResolver` implementations:
```csharp
services.AddScoped<DbContextAResolver>();
services.AddScoped<DbContextBResolver>();
```

You can then create a general repository for each context and the inject it per resource type. This example shows how you can create a single `DbContextARepository` for all entities that are members of `DbContextA`.

```csharp
public class DbContextARepository<TEntity> 
: DefaultEntityRepository<TEntity> where TEntity : class, IIdentifiable<int>
    {
        public DbContextARepository(
            ILoggerFactory loggerFactory,
            IJsonApiContext jsonApiContext,
            DbContextAResolver contextResolver)
        : base(loggerFactory, jsonApiContext, contextResolver)
        { }
    }
```

Then inject the repository for the correct entity, in this case `Foo` is a member of `DbContextA`:

```csharp
services.AddScoped<IEntityRepository<Foo>, DbContextARepository<Foo>>();
```

I recognize that this is not ideal, and I plan on fully documenting this process once I've had some time to flush out any possible challenges. Also, this should be included as part of #241 to improve the DX around the use of multiple contexts. Ideally, we'd like to be able to provide this functionality without this amount of boilerplate.
