### ISSUE TITLE
Improve Error Message For Invalid Objects Passed To Serializer

### ISSUE THREAD

**Issue by junmar** [json-api-dotnet/JsonApiDotNetCore#270]
![capture](https://user-images.githubusercontent.com/9524611/39135200-fe31a8a6-474a-11e8-8dec-47f6a45ba028.PNG)

**Comment by jaredcnance** [comment]
The serializer expects you to either return the model or am Errors object. Take a look at this documentation https://json-api-dotnet.github.io/#/custom-errors.
If that solves your issue, I’d like to leave this open as a task to  make this error message more useful.

**Comment by junmar** [comment]
Thanks. Documentation saves my  day.
