### ISSUE TITLE
Convert rest API to Json Api

### ISSUE THREAD

**Issue by jrock2004** [json-api-dotnet/JsonApiDotNetCore#279]
I am calling an api that is returning me rest. I want to convert that to JSON Api. Is there a way to easily do this with your package or do I really need to make only DB calls for this to work?

Here is the model I setup

```
public class AccessTokenResponse : Identifiable<int>
  {
    [Attr("access-token")]
    public string access_token { get; set; }
    [Attr("error")]
    public string error { get; set; }
    [Attr("error-description")]
    public string error_description { get; set; }
    [Attr("expires-in")]
    public string expires_in { get; set; }
  }
```

Here is the code I am trying to populate it with

```
var request = await _client.GetAsync($"{apiUrl}/access_token?client_id={client_id}&client_secret={client_secret}&grant_type={grant_type}");

request.EnsureSuccessStatusCode();

var response = await request.Content.ReadAsStringAsync();

_token = JsonConvert.DeserializeObject<AccessTokenResponse>(response);
```

**Comment by jrock2004** [comment]
@jaredcnance That is a good place for getting the token sure. But when I am ready to make a bunch other calls I would think those would not be services as well, would they?

**Comment by jaredcnance** [comment]
You haven't really shared enough of your requirements for me to give you much more than that. What resources are you exposing through your json:api application? You should be able to compose services like you normally would. I'm making assumptions about your application, but if you had a resource `Foo` that is backed by some other HTTP service (we'll call the external service `bar.com`) that uses OpenId/OAuth and you're simply proxying `Foo` back to your client application, the architecture might look like:

```
FoosController
└── FooService
    └── BarClient
        ├── TokenStore
        |   └── IMemoryCache
        └── HttpClient
```

`FoosController` -> `FooService` -> `BarClient` -> `TokenStore`

where:

- FoosController is your JsonApiDotNetCore controller
- FooService is your JsonApiDotNetCore service layer that exposes the methods required to perform json:api operations to the controller
- BarClient is the client service that knows how to communicate with bar. com
- TokenStore provides a cached storage mechanism so you don't have to re-authenticate on every request.


Hopefully, this provides a reasonable example of how JsonApiDotNetCore applications can still be composed like any other application.
