### ISSUE TITLE
SaveChanges error handling, better error handling implementation

### ISSUE THREAD

**Issue by enemyofthedawn** [json-api-dotnet/JsonApiDotNetCore#285]
Currently repositories ignore the fact that database can fail and repositories simply return null so are services. 

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/4982d9b3ac45454f01d2701ab719f3b69738498e/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L105

Controllers return NotFound when 5xx error would be more appropriate.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/1a860c46ead8fc688c86d407f6419521fcd1e335/src/Examples/JsonApiDotNetCoreExample/Controllers/TodoItemsCustomController.cs#L80-L83

There should be some way to tell what caused the error when using a service from controller and react with appropriate HTTP error code at the same time keeping service layer decoupled from api layer.

**Comment by jaredcnance** [comment]
If you’re getting a 404 response, then it should be the case that you have sent a request to update an entity that does not exist. Is that not the case?

5xx should only be returned in the case of a server exception for which the client can retry. And I believe these are properly handled. Can you provide an example where it is in fact a server error (5xx) and not a client error (4xx) that we are responding to incorrectly?

**Comment by enemyofthedawn** [comment]
I think you are right. SaveChanges will throw exception in case of failure and that can be handled with filters and return 5xx error. So SaveChanges returning 0 doesn't indicate failure.
