### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#289]
- [v2.2.4](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v2.2.4) needs to be included on the [documentation site](https://github.com/json-api-dotnet/json-api-dotnet.github.io)
- [v2.3.3](https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/316) options need to be added

**Comment by bart-degreed** [comment]
Closing, as I believe the documentation has been updated meanwhile.
