### ISSUE TITLE
Attribute Naming Conventions

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#293]
It would be great if we could define an app-wide naming convention for attributes and relationships with default options. So, instead of:
```c#
[Attr("fooBar")]
public object FooBar { get; set; }
```

You would specify a convention:

```c# 
// Startup.cs
options.AttributeNameConvention = NamingConvention.CamelCase;

// Model.cs

[Attr]
public object FooBar { get; set; }
```

A possible interface for `AttributeNameConvention` might be:

```c#
public interface INamingConvention {
  string Convert(string propertyName);
}
```

**Comment by btecu** [comment]
Instead of setting the field name straight on the properties or introducing a new setting (keep code simple), we could just use `Newtonsoft.Json.Serialization.NamingStrategy`.

Somewhat related, `Newtonsoft.Json` provides enough decorators that it wouldn't be necessary to have our own `[Attr]`, `[BelongTo]` or `[HasMany]`. Those can be inferred from types. Simple properties such as primitives, `DateTime`, `Guid` and `string` can be considered `[Attr]`. Class properties can be `[BelongsTo]` (one to one) while collections will be `[HasMany]`.

Opting in would be the default and to opt out of serializing a field, `[JsonIgnore]` (`Newtonsoft.Json.JsonIgnoreAttribute`) can be used.

`ContextGraph` along with `Newtonsoft.Json` should be sufficient to build a serialization / deserialization package that can be isolated from the other EF / Controllers specific codebase.

**Comment by btecu** [comment]
If overriding the name is a concern, `[JsonProperty]` (`Newtonsoft.Json.JsonPropertyAttribute`) allows for specific a custom name (overrides the naming strategy).

**Comment by jaredcnance** [comment]
I think using the existing `NamingStrategy` type would probably be fine, we already have a pretty hard dependency on Newtonsoft, so I don't think there's a problem there. Also, in case you weren't aware, we already allow users to specify `JsonSerializerSettings` for serialization of complex types. I need to look a little closer to see if this would be the right place to specify this behavior or if we should have an additional configuration value for `NamingStrategy`.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/390db0982664763d35328ca55113c0d7d2b7c794/src/JsonApiDotNetCore/Configuration/JsonApiOptions.cs#L144-L148

One thing to remember is that the existing attributes provide more options than just name overrides. I've enumerated these other configuration properties below:

- Attr: publicName, isImmutable, isFilterable, isSortable
- HasOne / HasMany: publicName, documentLinks, canInclude, withForeignKey

So, while I think our target should be enabling resource definitions that do not **require** these attributes, I don't think we should dispense with them altogether.

Also, inferring relationships based on types can get tricky. This is not a safe assumption:

> Class properties can be [BelongsTo] (one to one) while collections will be [HasMany]

There are some reference (class) types that would be considered "simple" types (e.g. `String`) so that would require whitelisting simple types. Also, we support complex attributes, for example:

```json
{
  "data": {
    "attributes": {
       "key" : {
         "nested-key": "nested-value"
       }
    }
  }
}
```

An alternative to this is to try to discover all resources and then determine their relationships by looking for properties where the property type is a registered type on the graph (or the property type is an enumerable of a registered type -- `List<T>`). I think this is feasible, but probably out-of-scope for this first pass.

This is an interesting idea:
> Opting in would be the default and to opt out of serializing a field, [JsonIgnore]

But, I have a couple reservations here:

- Types may need to be serialized in contexts other than json:api request/responses. Maybe this is ok.
- This is not the only way to determine whether or not a type should be serialized in Newtonsoft.Json. There are some features in Newtonsoft that we wouldn't support and I could see this causing confusion:
   - [ShouldSerialize](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm)
   - [ContractResolver](https://www.newtonsoft.com/json/help/html/ContractResolver.htm)
   - [SerializationCallbacks](https://www.newtonsoft.com/json/help/html/SerializationCallbacks.htm)
   - and lots more

_I think_ it may be confusing if users try to use established Newtonsoft.Json features and then they just don't work because we aren't simply doing `JsonConvert.DeserializeObject<T>(...)`. 
We don't actually deserialize directly using Newtonsoft. It looks more like:

- Deserialization:
`string` → `JsonConvert.Deserialize` → `Document` → extract context and create the target type

- Serialization: 
resource → create `Document` which contains `ResourceObject`s which are dictionaries with string keys → `JsonConvert.Serialize` → `string`

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b6ce80d9c8f7eceb56ed62f6ccb56c0213338b2c/src/JsonApiDotNetCore/Models/ResourceObject.cs#L6-L13

Because of these reasons, I believe we should keep the existing attributes. They can be used as overrides when there are exceptions to the established convention, or extra configuration is required that is specific to the attribute (e.g `isFilterable = false`). 

---

For this iteration users should be able to change models from:

```c#
public class Article : Identifiable {
  [Attr("name")]
  public string Name { get; set; }

  [HasMany("authors")]
  public List<Person> Authors { get; set; }
}
```

To: 

```c#
public class Article : Identifiable {
  public string Name { get; set; }

  [HasMany("authors")]
  public List<Person> Authors { get; set; }
}
```

And after additional planning and design, I think we can achieve the following. This will require significant changes to how the `ContextGraph` is constructed.

```c#
public class Article : Identifiable {
  public string Name { get; set; }
  public List<Person> Authors { get; set; }
}
```

**Comment by jaredcnance** [comment]
With respect to removing attributes, this can be done using the `ResourceDefinition`. Currently undocumented, but available since [v2.3.4](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v2.3.4) (#297 via #324).

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b6ce80d9c8f7eceb56ed62f6ccb56c0213338b2c/test/UnitTests/Models/ResourceDefinitionTests.cs#L103-L119

Or create two distinct models (a resource and db entity), mapped at the service layer. Currently undocumented, but available since [v2.4.0](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v2.4.0) (#112 via #344, #352).

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b6ce80d9c8f7eceb56ed62f6ccb56c0213338b2c/src/Examples/ResourceEntitySeparationExample/Startup.cs#L59-L62

**Comment by btecu** [comment]
Not sure what the difference between `name` and `publicName` is but the other ones, `isImmutable`, `isFilterable` and `isSortable` are only needed for the _other part_ of the project, the one that involves controllers. I'm not sure if there's a way where we can include those extensions as part of say the `Controller` package since the serialization wouldn't need to have knowledge of those.

The idea with `[JsonIgnore]` was that the field would not make it in the serialization / deserialization. Using instead `ShouldSerialize` would cause the same result?

I'm guessing it's not feasible to go from `class` to `Json` and from `string` to `class` without going through the intermediate `Document` but if it was, it would make things easier.

**Comment by jaredcnance** [comment]
> difference between name and publicName

They are the same. The property is called [`PublicAttributeName`](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b6ce80d9c8f7eceb56ed62f6ccb56c0213338b2c/src/JsonApiDotNetCore/Models/AttrAttribute.cs#L29-L47).

> are only needed for the other part of the project, the one that involves controllers

This is the main part of the project. If all you want is serialization I recommend one of the other [.Net libraries](http://jsonapi.org/implementations/#server-libraries-net). Serialization is a small component of this project and I don't think it will be pulled out into a separate package anytime soon (unless someone else is willing to do it). I personally, don't have the motivation to separate it for the sake of separation. FWIW we do have plans to separate the ORM layer in an upcoming release.

> the field would not make it in the serialization / deserialization

Yes, I'm aware of what `JsonIgnore` does. My point is we would only support a subset of Newtonsoft's features, but users will likely think we support all of them when in fact we wouldn't. So, if they tried to use `ShouldSerialize` to control the behavior, it just wouldn't work.
