### ISSUE TITLE
Prevent attributes from being serialized

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#297]
From @rtablada:

> For some models it would be helpful to be able to define which attrs are/aren't used for serializing vs deserializing. [...] Ideally we should be able to declare/override which attrs are used for `fetch`/`create`/`update` operations similar to JSON API resources http://jsonapi-resources.com/v0.9/guide/resources.html#Fetchable-Attributes (we probably can't reproduce this exact API since JADNC uses model decorators instead of a separate resource class)

## Proposal
```c#
public UserAttributeFilter : IAttributeFilter<User> 
{
    // exclude the User.Password attribute from serialization
    public HashSet<AttrAttribute> ShouldInclude(HashSet<AttrAttribute> attributes)
      => return attributes
            .Where(attr => attr.InternalAttributeName != nameof(User.Password))
            .ToHashSet();
}
```

**Comment by rtablada** [comment]
This could also be used to add attributes for some scenarios too? Or are you thinking all possible attrs have to be declared with Decorators and then the filter is only removing?

I think `ShouldInclude` could use some naming ❤️since that could be confused with `?include` from sideloading.

**Comment by rtablada** [comment]
Having macros/quick helpers for common situations like "DeserializeOnly", "BlockDeserialize", "SerializeOnly", "BlockSerialize" could be 👍 too

**Comment by jaredcnance** [comment]
I need to think about "adding attributes" a bit...

Another option is to modify #112 to handle this. Not sure if this is a good direction, but one option would be to define the following mapping steps:

- Input Resource → Entity
- Entity → Output Resource

Where the input, entity (database model), and output _could_ all be the same model. This would make the service layer interfaces look like:

```c#
public interface IResourceService<TEntity> : IResourceService<TEntity, int> {}

public interface IResourceService<TEntity, TId> : IResourceService<TEntity, TEntity, TEntity, TId> {}

public interface IResourceService<TInput, TOutput, TEntity, TId>
{
  Task<TOutput> CreateAsync(TInput entity);
  Task<IEnumerable<TOutput>> GetAsync();
   // ...
}
```

And you would optionally provide a mapper (but I would expect most mapping to be automatic)

```c#
interface IResourceMapper {
    // input → entity
    TEntity Map(TInput input);

    // entity → output
    TOutput Map(TEntity model);
}
```
