### ISSUE TITLE
RFC: Type rename proposals

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#317]
### Feedback on this issue is desired

There are several types that could have better names. We can change the names and deprecate the old ones via inheritance.

| Current Type | Description | Proposal(s) | Final |
|---|---|---|---|
| ContextGraph | A graph of all resources and their metadata | ResourceGraph<br>JsonApiResourceGraph<br>JsonApiSchema | |
| ContextGraphBuilder | Constructs the resource graph | ResourceGraphBuilder<br>JsonApiSchemaBuilder  | |
| ContextEntity | A json:api resource and its metadata | Resource<br>JsonApiResource<br>~ResourceDefinition~ | |
| DocumentData | The json:api document resource object as defined in the spec | ResourceObject | ResourceObject |
| JsonApiException<br>.GetError() | Returns the exception as a json:api formatted error object | JsonApiException.GetErrorCollection() | |
| EntityResourceService | ... | DefaultResourceService | |
| IEntity...Repository | Used by the resource service to construct and materialize queries | IQueryBuilder | |
| [`IEntityReadRepository.Get()`](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/491a6cbed1b68a6fcc9ce69ca8b00d3b20b586c7/src/JsonApiDotNetCore/Data/IEntityReadRepository.cs#L21) | Used to get the base `IQueryable` for which most queries are built from. See https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/404#issuecomment-420468203 | . GetQueryable(...) | |
| `GenericProcessor` | When updating relationships, it is helpful to be able to use generic methods even though the generic parameter is different from the controller's generic parameters. The `GenericProcessor` gets created and then used through a non-generic interface. However, all of this makes what it does a bit confusing. Really, all it is used for is updating relationships. The fact that we chose to do it this particular way should not influence the name. | `UpdateRelationshipProcessor`<br />`PatchRelationshipProcessor`  | |

Any other suggestions?

**Comment by maurei** [comment]
All but the proposal for `IQueryBuilder` have been processed in #589. We think that the repository layer is more broad than the responsibility as implied by the name `IQueryBuilder`
