### ISSUE TITLE
PATCH returns data:[] relationships

### ISSUE THREAD

**Issue by joshhubers** [json-api-dotnet/JsonApiDotNetCore#318]
When I patch to an endpoint the relationship returns data: [], which isn't always true.
For example, if I had ingredients and recipes, I query for `recipes?include=ingredients` and I will get the included ingredients as expected.

However, if I PATCH to recipe, the relationship returns an empty array, even though relationships exist
For example:
```
{  
   "data":{  
      "attributes":{  
         "id":203,
         "title":"Cake",
      },
      "relationships":{  
         "ingredients":{  
            "links":{...},
            "data":[ ] <------- Shouldn't be empty or present?
         }
      },
      "type":"recipes",
      "id":"203"
   }
}
```

In my case I'm building an ember app, so ember thinks that the relationships just magically disappear and content on the page will disappear on update.

**Comment by joshhubers** [comment]
I should also mention I'm using v2.2.5 as I have not upgraded to Core 2.1 yet.

**Comment by jaredcnance** [comment]
Thanks for reporting this. I plan on picking this up on Monday if no one gets to it by then.

**Comment by joshhubers** [comment]
Update: I have upgraded to core 2.1, and am using v2.3.3 and still have the bug.

**Comment by jaredcnance** [comment]
@joshhubers I have reproduced the issue and am currently working on a fix.

**Comment by jaredcnance** [comment]
@joshhubers actually, I'm unable to repro. Can you take a look at the test here:

https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/332/commits/d9d1f659f672070268066bd59184772eb810ea89#diff-3291fcbe5d589cd25e4f538a16f78aadR148

And let me know if you're doing something different? Are you updating the relationship in the `PATCH` request?

**Comment by joshhubers** [comment]
@jaredcnance Thanks for the test. The test ran fine and looks like the situation I was having.

Turns out there was an initializer in the default constructor, assigning an empty list to the property.

i.e.

```
public Person()
{
  TodoItems = new List<TodoItems>();
} 
```

So the serializer believed that there was a relationship with no data.
