### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ewolution94** [json-api-dotnet/JsonApiDotNetCore#342]
Hi,

just started using JADNC (v2.3.4) with my .NET Core project (v.2.1.0). So far I got my API working with JSON API that I am able to POST and GET my data properly.

However, when I attempt to GET an item by Id it shows/throws the following error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
     at JsonApiDotNetCore.Builders.DocumentBuilder.Build(IIdentifiable entity) 
          in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Builders\DocumentBuilder.cs:line 37
     at JsonApiDotNetCore.Serialization.JsonApiSerializer.SerializeDocument(Object entity)
          in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Serialization\JsonApiSerializer.cs:line 87
     at JsonApiDotNetCore.Formatters.JsonApiWriter.WriteAsync(OutputFormatterWriteContext context) 
          in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Formatters\JsonApiWriter.cs:line 36
```

My model that I'm trying to access looks like this: (Holiday.cs)

```
    [Table("Feiertag")]
    public class Holiday : Identifiable
    {
        public Holiday()
        {

        }

        [Column("Name")]
        [MaxLength(64)]
        [Attr("name")]
        public string Name { get; set; }

        [Column("Datum")]
        [Attr("date")]
        public DateTime Date { get; set; }
    }
```

The corresponding controller like this: (HolidaysController.cs)

```
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [ValidateModel]
    [Route("api/[controller]")]
    [Produces("application/vnd.api+json")]
    [EnableCors(AntaresNames.DefaultCorsPolicy)]
    public class HolidaysController : JsonApiController<Holiday>
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="jsonApiContext"></param>
        /// <param name="resourceService"></param>
        public HolidaysController(
            IJsonApiContext jsonApiContext,
            IResourceService<Holiday> resourceService)
            : base(jsonApiContext, resourceService)
        {
        }
    }
```

I'm using Postman to send a GET request to my backend using the following URL:

```
https://localhost:44350/api/holidays/2
```

What am I missing here? Like I stated above, the "normal" GET works perfectly fine...

EDIT: Please tell me if I heend to provide additional information/code to the issue!

**Comment by joshhubers** [comment]
Hey @ewolution94 ,

Did you configure the JADNC middleware in your Startup.cs and apply your DbContext (if applicable)

>     // add jsonapi dotnet core
>     services.AddJsonApi<AppDbContext>();
>     // ...

https://json-api-dotnet.github.io/#/step-by-step

If you post your Startup.cs that would be helpful as well.

**Comment by jaredcnance** [comment]
Unable to reproduce. @ewolution94 please reopen if you have additional details.

**Comment by division-by-zero** [comment]
I get the same error when posting invalid data. Posting valid data is OK.

It only happens when I set Content-Type: application/vnd.api+json. 

It works if I set Content-Type: application/json and send data as single object (not as described here: https://jsonapi.org/format/#crud-creating)

**Comment by division-by-zero** [comment]
I've sort of managed to solve the problem but I needed to include JsonApiDotNetCore source to my project to be able to do this.

It seem error occurring JsonApiSerializer.cs

```C#
    private string SerializeDocument(object entity)
        {
            var identifiableEntity = entity as IIdentifiable;
            var document = _documentBuilder.Build(identifiableEntity);
            return _serialize(document);
        }
```
Here `identifiableEntity` is `null` because `entity` is not an `IIdentifiable` but an `ValidationProblemDetails` object.

I disabled auto model validation by putting this code to `Startup.cs`:

```C#
    services.Configure<ApiBehaviorOptions>(options =>
    {
        options.SuppressModelStateInvalidFilter = true;
    });
```
Then I've changed this line from `BaseJsonApiController`

```C#
public virtual async Task<IActionResult> PostAsync([FromBody] T entity)
        {
            if (_create == null)
                throw Exceptions.UnSupportedRequestMethod;

            if (entity == null)
                return UnprocessableEntity();

            if (!_jsonApiContext.Options.AllowClientGeneratedIds && !string.IsNullOrEmpty(entity.StringId))
                return Forbidden();

            if (!_jsonApiContext.Options.ValidateModelState && !ModelState.IsValid)
                return UnprocessableEntity(ModelState.ConvertToErrorCollection<T>(_jsonApiContext.ResourceGraph));

            entity = await _create.CreateAsync(entity);

            return Created($"{HttpContext.Request.Path}/{entity.Id}", entity);
        }
```
```C#
if (_jsonApiContext.Options.ValidateModelState && !ModelState.IsValid)
    return UnprocessableEntity(ModelState.ConvertToErrorCollection<T>(_jsonApiContext.ResourceGraph));
```
to

```C#
if (!_jsonApiContext.Options.ValidateModelState && !ModelState.IsValid)
    return UnprocessableEntity(ModelState.ConvertToErrorCollection<T>(_jsonApiContext.ResourceGraph));
```

**Comment by PiotrBrzezianski** [comment]
@jaredcnance there seems to be enough details to decide what to do with this further. 
I was able to reproduce by following the steps above - basically posting data that doesn't conform to validation attributes while using Content-Type: application/vnd.api+json.

I'm new to this codebase but it looks to me that the DocumentBuilder fails to notice that there were validation errors and tries to serialize ValidationProblemDetails object as if it was IIdentifiable resource.

This issue makes debugging quite difficult because an error in the filter bypasses a lot of logging so there is no easy way to find out what data didn't get past validation... Suppressing the filter helps but is not a great solution.
