### ISSUE TITLE
Add unit tests for service resolution

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#346]
We should have a test that validates each service can actually be resolved from the container (within a scope). See #339 for motivation. It would be fantastic if this could be done via reflection and not manually adding a new test every time you register a new service. I'm thinking we would define a static member that contained all the `ServiceDescriptor`s. Then in the test we just get this member and iterate over them to make sure they can all be resolved from the container.

**Comment by bart-degreed** [comment]
Something along the lines of https://github.com/dlemstra/ICanHazDadJoke/blob/main/test/ICanHazDadJoke.Api.Tests/AppStartup/StartupTests/TheDependencyInjectionRegistration.cs
