### ISSUE TITLE
Support POST requests to a to-many relationship link

### ISSUE THREAD

**Issue by avrittrohwer** [json-api-dotnet/JsonApiDotNetCore#353]
As per the json:api spec (under the section linked at http://jsonapi.org/format/#crud-updating-relationships)

> A server MUST respond to PATCH, POST, and DELETE requests to a URL from a to-many relationship link
    ...
   If a client makes a POST request to a URL from a relationship link, the server MUST add the specified 
   members to the relationship unless they are already present. If a given type and id is already in the 
   relationship, the server MUST NOT add it again

**Comment by maurei** [comment]
Would be nice to include this in v3.2.0
