### ISSUE TITLE
[Question] Change root URL

### ISSUE THREAD

**Issue by mathisloge** [json-api-dotnet/JsonApiDotNetCore#358]
is it possible to change the root url?
For example:

```
{
  "data": [
    {
     ...
      "attributes": {
        ...
      },
      "relationships": {
        "owner": {
          "links": {
            "self": "http://example.com/api/v1/todo-items/2026/relationships/owner",
            "related": "http://example.com/api/v1/todo-items/2026/owner"
          }
        }
      }
    }
  ]
}
```

And change all "example.com" domain to "gateway.com"

**Comment by jaredcnance** [comment]
The only supported scenarios right now are:

- relative URLs
- absolute URLs based on the current `HttpContext.Request`

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/13404ab802a5b2a53f2d9f53bd9ed89f465a296e/src/JsonApiDotNetCore/Builders/LinkBuilder.cs#L16-L22

Can you elaborate on your use case? If you're using a gateway, I would still expect the original `Host` value to be proxied back to the application layer by your web server.

**Comment by mathisloge** [comment]
Yeah, it solves my use case. Should this be closed?

**Comment by jaredcnance** [comment]
For now, yes. I have no problem adding this feature, but I want to hold off until I have a better understanding of use cases where relative links won't suffice.
