### ISSUE TITLE
Make controller boilerplate optional

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#365]
We can probably make the controller boilerplate optional a few different ways:
- Define a non-generic controller with parametrized route definitions and then route to the correct services. This would be similar to the approach used for operations. The problem here is you cannot define your own controllers. This would be a breaking change
- Codegen controllers that haven't been defined. Or require an attribute on the resource/entity class. See https://github.com/AArnott/CodeGeneration.Roslyn and https://jeremydmiller.com/2015/11/11/using-roslyn-for-runtime-code-generation-in-marten/ ... need to make sure we can generate types within the executing assembly.

**Comment by bart-degreed** [comment]
Related to #732.
