### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by summiTam** [json-api-dotnet/JsonApiDotNetCore#380]
How to implement pagination using JsonApi ?
Its not clear or is it even possible or not ?

**Comment by jaredcnance** [comment]
Have you read the docs? 

https://json-api-dotnet.github.io/#/pagination

I also recommend taking a look at the Global Options section which offers some configurability over default behavior:

https://json-api-dotnet.github.io/#/global-options

You can also see the tests here:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/PagingTests.cs
