### ISSUE TITLE
Provide API for easy service/repo registration

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#384]
## Description

```c#
services.AddResourceService<FooService>();
```

should register any applicable forms:

```c#
services.Add<IResourceService<Foo>, FooService>();
services.Add<IResourceService<Foo, int>, FooService>();
services.Add<IGetAllService<Foo>, FooService>();
services.Add<IGetAllService<Foo, int>, FooService>();
// ... 
```

It should also handle services with mappings:

```c#
services.Add<IResourceService<Foo, Bar, int>, FooService>();
```

This API may be usable by the service discovery pipeline

**Comment by btecu** [comment]
I should mention that having `services.Add<IResourceService<Foo>, FooService>();` instead of `services.Add<IResourceService<Foo, int>, FooService>();` doesn't error out, which might be confusing.

**Comment by jaredcnance** [comment]
Why should it error out? You're simply registering a dependency. The fact that the former doesn't work, should be entirely dependent upon how you're requesting the dependency in your controller/service. For example, if in your controller you request `IResourceService<Foo>` it should just work:

```c#
public class FooController : JsonApiController<Foo>
{
    public PeopleController(
        IJsonApiContext jsonApiContext,
        IResourceService<Foo> resourceService,
        ILoggerFactory loggerFactory) 
        : base(jsonApiContext, resourceService, loggerFactory)
    { }
}
```

but, if your controller requests the id specific type `IResourceService<Foo, int>`, then it will fail to activate unless that type has been registered:

```c#
public class FooController : JsonApiController<Foo>
{
    public PeopleController(
        IJsonApiContext jsonApiContext,
        IResourceService<Foo, int> resourceService,
        ILoggerFactory loggerFactory) 
        : base(jsonApiContext, resourceService, loggerFactory)
    { }
}
```
