### ISSUE TITLE
How can we automatically include certain related resources without requiring the c

### ISSUE THREAD

**Issue by Nihimon** [json-api-dotnet/JsonApiDotNetCore#385]
## Description

We'd like to include some related resources by default.  For example, automatically returning the comments for a blog post without requiring the client to specify `?include=comments`.

## Environment

- JsonApiDotNetCore Version: 2.5.1
- Other Relevant Package Versions: Asp.Net Core 2.1

**Comment by jaredcnance** [comment]
From the json:api spec:

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

So, in order to remain compliant with the spec AND support your request, there are a couple options:

- allow endpoints to disable client requested inclusions, provided pre-defined defaults
- provide default inclusions **if and only if** a client does not specify an `?include=` parameter

Which are you looking for?

**Comment by Nihimon** [comment]
I had the latter context in mind.  I would be interested in knowing the configuration options to disable the `include` query parameter, but it's not a feature I see us using.

I've seen where the IJsonApiContext has the query parameter data.  Is it recommended to directly write to the context?  I'm pretty sure I could figure out how to replace an empty set of include values with a default set.

**Comment by jaredcnance** [comment]
🤔 you may be able to do something like this in the controller constructor:

```c#
if(_jsonApiContext.QuerySet.IncludedRelationships.Contains("foos") == false) {
  _jsonApiContext.QuerySet.IncludedRelationships.Add("foos");
}
```

**Comment by shaunparsloe** [comment]
@jaredcnance I have tried to do this but the jsonApiContext.QuerySet is null in the constructor.

I don't know if it's related to a refactor in the code as I have also noticed that _jsonApiContext.ContextGraph is obsolete and has changed to _jsonApiContext.ResourceGraph

**Comment by jaredcnance** [comment]
It will be `null` if there are no queries present:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f72e8ae2247b39fbf1bf5af446b27e9420cf01f4/src/JsonApiDotNetCore/Services/JsonApiContext.cs#L71-L75

So, you can try:

```c#
if(_jsonApiContext.QuerySet == null) {
  _jsonApiContext.QuerySet = new QuerySet();
  // yes, the below line is dumb and this should get fixed.
  _jsonApiContext.IncludedRelationships = _jsonApiContext.QuerySet.IncludedRelationships;
}
```
