### ISSUE TITLE
Add method for retrieving public relationship names on the graph

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#397]
## Description

Similar to: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/113ab03ae88e78270d42404081860f67780cbf38/src/JsonApiDotNetCore/Internal/ContextGraph.cs#L121-L127

See: https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/385#issuecomment-418832975

**Comment by maurei** [comment]
This is now possible by doing
```c#
var relationship = _resourceGraph.GetRelationships( (Bar e) => e.Foos ).First();
```
