### ISSUE TITLE
Filtering on special chars sends back an un-escaped special character in the links urls

### ISSUE THREAD

**Issue by ScottEDubya** [json-api-dotnet/JsonApiDotNetCore#408]
## Description
When filtering on a special character, the links sent back don't use the encoded characters. 
e.g. a GET request to look for a name of "&" `/entities?filter[name]=%26` responds with incorrect urls in the links object:
(expected):
```
"links": {
        "last": "http://localhost:54168/entities?page[size]=50&page[number]=1&filter[name]=%26"
},
```
(actual):
```
"links": {
        "last": "http://localhost:54168/entities?page[size]=50&page[number]=1&filter[name]=&"
},
```
## Environment

- JsonApiDotNetCore Version:  2.4.0
- Other Relevant Package Versions: n/a?

**Comment by bart-degreed** [comment]
Fixed in #698.
