### ISSUE TITLE
Patch many-to-many not working relationships not set

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#415]
## Description

I added an exception (will add to pull request) to check when updating a many-to-many relationship:

```json
{
  "data" : [
	{ "type" : "teams", "id" : 15}, {"type": "teams", "id" : 14}
  ] 
}
```
Which is API spec. which you follow in your specs (great):
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/448114793a72e134f7720f436e34855df3532d32/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingRelationshipsTests.cs#L43
But it doesnt work. Because in 
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/491a6cbed1b68a6fcc9ce69ca8b00d3b20b586c7/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L184

It needs  a "relationships" parameter in the body. What exactly is the way to go here?

## Environment

- JsonApiDotNetCore Version: V3.0.0.v4
- Other Relevant Package Versions:

**Comment by jaredcnance** [comment]
> It needs a "relationships" parameter in the body. 

Not sure what you mean. The `relationships` parameter is of type `ResourceObject` [which inherits `ResourceIdentifierObject`](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/491a6cbed1b68a6fcc9ce69ca8b00d3b20b586c7/src/JsonApiDotNetCore/Models/ResourceObject.cs#L6). 

Is there a flaw in the test? Can you identify the difference between your setup and the test?

**Comment by jaredcnance** [comment]
Is the `Content-Type` set to `application/vnd.api+json`? If you debug the application and enable "break on all exceptions" is anything thrown?

**Comment by wisepotato** [comment]
Yup that was the case. Thank you for your help. You can close this now :)
