### ISSUE TITLE
Relationship update via POST not supported

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#430]
## Description
Should be able to POST to a relationship to add to it, instead of using PATCH to replace the relationship entirely.

spec: https://jsonapi.org/format/#crud-updating-relationships
## Environment

- JsonApiDotNetCore Version: latest
- Other Relevant Package Versions:

**Comment by wisepotato** [comment]
I have added a pull request with test for you to check out

**Comment by jaredcnance** [comment]
Thanks for the PR! Will review it this week but it probably won't make the v3 release. May do a quick 3.1 follower with this.

Anyways, closing this issue as a duplicate of #353.

**Comment by wisepotato** [comment]
Yeah thought as much, i'll use the PATCH in the meantime. Thanks for the update!
