### ISSUE TITLE
NullReference Nested resource include chains

### ISSUE THREAD

**Issue by Maan511** [json-api-dotnet/JsonApiDotNetCore#433]
I found a bug when including nested reources. Consider the following example:

```
class Book {
  // This is optional
  [HasOne("Author")]
  public virtual Author Author { get; set; }
}

class Author {
  [HasMany("Image")]
  public virtual IList<Image> Images { get; set; }
}

class Image {
}
```
Now when requesting Books with `?Include="Author.Images"` An exception is thrown from the ResourceGraph, when a book doesn't have an author. Because the parent entity is null.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8570b216c7ede3a7b5f9fc7a4912404a14926df5/src/JsonApiDotNetCore/Internal/ResourceGraph.cs#L118-L120

**Comment by milosloub** [comment]
I have the same issue
