### ISSUE TITLE
Securing models

### ISSUE THREAD

**Issue by catsalive** [json-api-dotnet/JsonApiDotNetCore#439]
## Description
I'm looking at using this package to replace our current Api implementation. I'm trying to find ways to secure models and model properties and prevent users from querying records they shouldn't have access to. Is there a recommended way of achieving these things?
...

## Environment
.Net core latest version
- JsonApiDotNetCore Version: latest
- Other Relevant Package Versions:

**Comment by jaredcnance** [comment]
@catsalive there are two different things you can do. The first is to customize the repository layer which allows you to alter the default queries applied at the resource level. This is discussed in the docs [here](https://json-api-dotnet.github.io/#/entity-repositories). 

The second is to create a `ResourceDefinition` that filters the output attributes based on a runtime condition. The docs have yet to be published, but you can find them [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/docs/usage/resources/resource-definitions.md#runtime-attribute-filtering).

**Comment by catsalive** [comment]
@jaredcnance Awesome! Thank you so much. And thanks to you and whoever else put effort into building this package. I'm kind of frothing at the mouth about it at work. It looks like it will fit really well with our front-end architecture.
