### ISSUE TITLE
Clone doesn't compile

### ISSUE THREAD

**Issue by dbvance** [json-api-dotnet/JsonApiDotNetCore#441]
## Description

Unzipped the clone and tried to load it with VS 2017 version 15.9.0 preview 4.0.  Ran a "clean".  Then, tried to build JsonApiDotnetCore.sln.  The following error is issued:

Unable to locate repository containing directory 'C:\Apps\Application\VS\net\C#\JsonApiDotNetCore\Extract\JsonApiDotNetCore-master\src\JsonApiDotNetCore'.

That folder exists.

How is this issue solved?
...

## Environment

- JsonApiDotNetCore Version: Latest/greatest as-of 11/02/2018.  
- Other Relevant Package Versions: VS 2017 version 15.9.0 preview 4.0

**Comment by jaredcnance** [comment]
Do you [have git installed](https://github.com/dotnet/sourcelink/issues/96)?

**Comment by jaredcnance** [comment]
Closing. If you are still having this issue with git installed, feel free to reopen.
