### ISSUE TITLE
How to correctly wire up to the service level without EF or any type of repo?

### ISSUE THREAD

**Issue by kcragin** [json-api-dotnet/JsonApiDotNetCore#443]
I am trying to wire up JADNC into my API, but I do not have any need to use EF (in fact I am looking to leverage Redis). The `ConfigureServices` of the NoEntityFramework example seemed to be a good starting point but it has me a bit confused, because it still references `AppDbContext`.

When I attempt to access my API, I get an `InvalidOperationException` during resolution because the `IDbContextResolver` cannot be resolved.

What would be the correct `AddXxx` calls in `ConfigureServices` be to get me to my non-`EntityResourceService<T>` based resource service? I am using the `AddJsonApi` overload that takes an options action and the builder from `services.AddMvcCore()`.

**Comment by jaredcnance** [comment]
Can you post the stack trace you're getting? Also, can you post your any of your custom types? I don't need the entire implementation, just the constructors because that will let me know what dependencies are being resolved from the container.

**Comment by maurei** [comment]
Closing as no reply
