### ISSUE TITLE
Can't create resource with relationship in Entity-Resource separation mode

### ISSUE THREAD

**Issue by milosloub** [json-api-dotnet/JsonApiDotNetCore#445]
Consider following:

Entities:
```
    public class Client : Identifiable
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Parent Parent { get; set; }
        public int ParentId { get; set }
    }
```
```
    public class Parent: Identifiable
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
```

Resources:
```
    public class ClientResource : Identifiable
    {
        [Attr]
        public string FirstName { get; set; }
        [Attr]
        public string LastName { get; set; }
        [HasOne]
        public ParentResource Parent { get; set; }
    }
```
```
    public class ParentResource: Identifiable
    {
        [Attr]
        public string FirstName { get; set; }
        [Attr]
        public string LastName { get; set; }
    }
```

Three Layer flow (with Automapper Profile)
`1) Controller - JsonApiController<ClientResource>`
`2) Service - EntityResourceService<ClientResource, Client, int>`
`3) Repository - DefaultEntityRepository<Client>`

If I POST request like this:
```
{
    "data": {
        "attributes": {
            "first-name": "Homer",
            "last-name": "Simpson"
        },
        "relationships": {
            "parent": {
                "data": {
                    "type": "parents",
                    "id": "1"
                }
            }
        },
        "type": "clients"
    }
}
```
the InvalidOperationException is thrown, because:
"The entity type 'ParentResource' was not found. Ensure that the entity type has been added to the model."
This exception points to line 234 of DefaultEntityRepository and it's AttachHasOnePointers method.

Do you have any idea, how to handle this? Does this mean, that Repository should be responsible for proper resolve of navigation property type?

**Comment by roblankey** [comment]
Hm. I would expect that to work just from looking at it quickly. The Course/Department example is very similar.

**Comment by roblankey** [comment]
Quick update. I do indeed get the same error when attempting to add the relationship like this. As a workaround, you can update the relationship after creation (e.g. RelationshipModifyTests)

**Comment by milosloub** [comment]
@roblankey Thanks for the info. Unfortunately I can't do this as a workaround - several clients are connected to API using about 40 controllers, so I have to keep unseparated flow. Every other operations like inclusion, filter, sort etc. works with no problems. All my acceptance tests fails only in this one use-case. If I'm thinking about solution, it's quite hell of pain :(

**Comment by roblankey** [comment]
Ok. Makes sense. Let me see what I can do.

**Comment by milosloub** [comment]
Cool! As @jaredcnance said, the same problem should be also with HasMany (I didnt't try, because we don't have this use-case...for now).
Thanks for this, it looks good!
