### ISSUE TITLE
Custom service registration during auto-discovery

### ISSUE THREAD

**Issue by ddaspit** [json-api-dotnet/JsonApiDotNetCore#455]
## Description
I am using AutoFac for dependency injection. I would like to be able to write my own logic for registering resource services with the DI container while also taking advantage of the new ability in 3.0 to auto-discover services. I tried to implement my own `AddServices()` method following the example in `ServiceDiscoveryFacade`, but I wasn't able to use `TypeLocator`, since it is internal. The simplest solution would be to make `TypeLocator` public, so that developers could take advantage of the class.

## Environment

- JsonApiDotNetCore Version: 3.0
- Other Relevant Package Versions:

**Comment by ddaspit** [comment]
My resource services have an extra interface that needs to be registered and they require property injection. I register my resource services with AutoFac like this:
``` cs
containerBuilder.RegisterType(serviceType)
    .AsImplementedInterfaces()
    .PropertiesAutowired()
    .InstancePerLifetimeScope();
```
This registers all of the interfaces that my resource services implement, including my interface, and enables property injection. I don't think there is any way to do this using the current `ServiceDiscoveryFacade`. I understand if `TypeLocator` isn't ready to be made public yet. I am currently working around this issue by copying the code from `TypeLocator` into my repo.

**Comment by ddaspit** [comment]
Sounds reasonable. I will let you know if I find any deficiencies in `TypeLocator`, but it currently fulfills my needs. Thank you for the great library.

**Comment by bart-degreed** [comment]
@ddaspit Since this issue was opened, a lot of the internals have changed. Do you still need any changes in JsonApiDotNetCore or can this be closed?

**Comment by ddaspit** [comment]
Yes, this can be closed.
