### ISSUE TITLE
problems in "Implicit Access By Service Injection"

### ISSUE THREAD

**Issue by Kylinking** [json-api-dotnet/JsonApiDotNetCore#462]
## Description
When I followed by the example in the doc to make some METHODs return status(405).  AmbiguousActionException was thrown out when I  made user controller class derived from BaseJsonApiController. But it was right when the user controller class derived from JsonApiController.
...
```
public class ShopsController : BaseJsonApiController<ShopInfos>  --- exception thrown out.
while 
public class ShopsController : JsonApiController<ShopInfos> --- everything ok.
```

**Comment by jaredcnance** [comment]
The routes are defined in `JsonApiController`, so if you choose to inherit from `BaseJsonApiController`, you'll need to define the routes yourself. Can you post your controller?

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/2a8a02f69e00725148103702594f304669cd67e1/src/JsonApiDotNetCore/Controllers/JsonApiController.cs#L67-L68

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/2a8a02f69e00725148103702594f304669cd67e1/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L105-L106

**Comment by Kylinking** [comment]
```
 [Route("api/v2/[controller]"), DisableRoutingConvention]
    public class ShopsController : JsonApiController<ShopInfos>
    {
        private readonly ILogger logger;
        public ShopsController(IJsonApiContext jsonApiContext, IGetAllService<ShopInfos> getAllService, ILoggerFactory loggerFactory) : base(jsonApiContext, getAllService)
        {
            logger = loggerFactory.CreateLogger("ShopsController");
        }

        // [HttpGet]
        // public override async Task<IActionResult> GetAsync()
        //=> await base.GetAsync();

        //[HttpGet("{id}")]
        // public override async Task<IActionResult> GetAsync(int id)
        //=> await base.GetAsync(id);
    }
```
When the ShopsController inherit from JsonApiController , the Service Injection works well. In the code I user IGetAllService.  I'll get  status 405 if I make a POST request.  
But if I change  to inherit from BaseJsonApiController. I'll get AmbiguousActionException even I make a GET request.  When I defined  my own actions like the comments, the GET request works. But POST request makes AmbiguousActionException. 
the example code in the doc makes me confused.

**Comment by jaredcnance** [comment]
I'll have to reproduce this. In general, you should just inherit from `JsonApiController` unless you need to modify the routing attributes.

**Comment by bart-degreed** [comment]
It looks like this question has been answered. Please reopen with repro steps if there is still a problem and I will investigate.
