### ISSUE TITLE
Omit empty data array in relationships

### ISSUE THREAD

**Issue by mdsharpe** [json-api-dotnet/JsonApiDotNetCore#471]
## Description
I have a requirement to build a JSON API compliant endpoint which returns an entity without its related data. The user would then request the relationship data separately. For example:
 
Entity Request: `v1/myentity/{entity-id}`.
 
Entity Relationship Request: `v1/myentity/{entity-id}/items`.
 
My endpoint currently returns this when an entity request is made:
 
```json
{
  "data": {
    "attributes": {
      "foo": 2,
      "bar": 1
    },
    "relationships": {
      "items": {
        "links": {
          "self": "http://localhost:60000/v1/myentity/1/relationships/items",
          "related": "http://localhost:60000/v1/myentity/1/items"
        },
        "data": []
      }
    },
    "type": "myentity",
    "id": "1"
  }
}
```
 
As you can see the `data` property is an empty array. This is somewhat misleading because there are related `items`, we have just not included them in this response.

In [this section of the JSON:API specification](https://jsonapi.org/format/#document-resource-object-relationships), it shows that it is not required within the relationship section to show the data attribute. It is compliant to only have a `links` member and no `data` member.

Is there any way from the controller or via configuration I could omit the array from my response in order to be compliant with the specification and not give the impression the related data is empty?

## Environment
- JsonApiDotNetCore Version: 3.0.0

**Comment by jaredcnance** [comment]
It actually should omit the relationship be default unless it's being initialized somewhere. [This is one reason](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/318#issuecomment-403021162) it can happen.

**Comment by mdsharpe** [comment]
Thanks, resolved by configuring AutoMapper to allow null collections.
