### ISSUE TITLE
Extend ResourceDefinition

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#477]
## Description

To allow for greater flexibility and reliability using filters we need to change a few things:

We need to change the dependency on `Include(string path)` in 

https://github.com/aspnet/EntityFrameworkCore/blob/473dafce1d2b2e2e2dfd49eb085b9c4bc220658a/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2452-L2469

We then need to make sure that when we have the following cases:
```
users?include=posts
posts?include=users
```
and we have a `ResourceDefinition` on users, that on both urls the Users get filtered. An example of this would be a rule that the current user that is requesting the url cannot see user with an id of `4`. Or that a user cannot patch a post with a certain type.

This will require a change in `ResourceDefinition` and the implementation thereof in the Service and Repository layer.

The repository will need to be changed:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e58a48dc25248a042bf3f3142186736faa2e908a/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L340-L374

## Environment

- JsonApiDotNetCore Version: v3.0.0

**Comment by wisepotato** [comment]
@jaredcnance the one problem i'm facing at the moment is that there isnt a cache for all ResourceDefinitions. For this to work, we need to either register the ResourceDefinitions in the `startup.cs` (which would be .. suboptimal) or in the constructor of `ResourceDefinition<TItem>`. 

I'd say both; but I'd like to know your opinion on the matter on how to approach. I made a very basic example of what I would like to achieve with `OnList` being the function called on the listing of a resource, other names would be `OnPatch`, `OnResourcePatch` or any combination, and maybe even a general function.

**Comment by wisepotato** [comment]
Ok, took a detour to get the ResourceDefinition problem on track, but currently encountering the TreeBuilding, any suggestions on how to tackle? This would alleviate a lot of trouble with deeply nested problems. We could then recursively go down the tree and apply any rules that the user has laying around. ALlowing for maximum flexibility

**Comment by jaredcnance** [comment]
We do not need a cache for `ResourceDefinition` they are cached by the IoC container in the request scope.

**Comment by wisepotato** [comment]
How can I access them without injecting them all into the repository? I couldnt figure out how to grab all resourcedefinitions..

**Comment by jaredcnance** [comment]
See my comment in the PR about `GenericProcessorFactory`.

**Comment by maurei** [comment]
Closing so we can stick to #478 for all correspondence about this

**Comment by maurei** [comment]
Resource hooks have been merged and released in v4.0.0-alpha3
