### ISSUE TITLE
Extend sparse field selection

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#479]
From #558 :

> Sparse field selection on included members in IncludedRelationshipBuilder.

Three issues:
* Complex Attributes /nested attributes do not respond to filtering sparse fieldsets
* Field properties (so non-properties!) do not respond to the filtering of sparse fieldsets if they are not mapped, they are included in the `_dbSet` filtering, which they shouldnt be, because... they're not mapped
* (optional) adding optional fields would be great, I have some attributes that are heavy to load, and my front-end guy only wants them on certain page loads. So a sparse field that would default to not show a specific attribute would be great.

**Comment by milosloub** [comment]
@wisepotato Do you mean this https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/476#issuecomment-466162290 ?

**Comment by wisepotato** [comment]
oops! Didnt find it in search, but maybe should have looked at the recent issues.... thanks!

**Comment by milosloub** [comment]
Yeah, the title of #476 is little bit confusing. When I was creating that issue I didn't notice, that this is common problem with sparse fields, not only  repository override case

**Comment by wisepotato** [comment]
the complex attributes/nested attributes do not responde to filtering sparse fieldsets still holds true i guess though.

**Comment by jaredcnance** [comment]
> * (optional) adding optional fields would be great, I have some attributes that are heavy to load

Can this be handled by `ResourceDefinition.OutputAttrs` ? When you say "heavy to load", do you mean that you don't want them loaded into memory in your JADNC application, or you don't want them loaded client side?

**Comment by wisepotato** [comment]
both to be honest, generation of a certain embed token takes very long, and doesnt need to be in the full list. Sure I can do this with a custom service, but I think we're here to look at integrating custom things into the core to keep th services and repositories light

**Comment by maurei** [comment]
@wisepotato this sounds like we can handle this using resource hooks. Can we therefore close this issue?

**Comment by wisepotato** [comment]
Absolutely!

**Comment by wisepotato** [comment]
Actually noy really, sparse field selection is not available in the hooks
