### ISSUE TITLE
Create Reference Implementation Using Graph Database

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#480]
## Description

Investigate what it would take to switch the persistence layer from a relational database to a graph db such Neptune, Titan, Arango, etc. We should provide a reference implementation for others to use and base future work on.

**Comment by bkoelman** [comment]
Closing, as this feature request has been open for a very long time. The JADNC team has no interest in implementing this, and no community members have expressed such interest either. Feel free to add a comment if you'd like to start working on this.
