### ISSUE TITLE
Increase ResourceDefinition DefaultSort Visibility

### ISSUE THREAD

**Issue by ngboardway** [json-api-dotnet/JsonApiDotNetCore#500]
We are using a data source other than Entity Framework for part of our project and are implementing IEntityRepository ourselves. We want to be able to make use of resource definitions, but currently both pieces related to sorting are marked internal or protected. 

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e58a48dc25248a042bf3f3142186736faa2e908a/src/JsonApiDotNetCore/Models/ResourceDefinition.cs#L182-L184

Is there a particular reason that the sorting functionality is hidden while the filtering functionality is public? Ideally, DefaultSort would be public like GetQueryFilters to enable its use outside of the source code.

**Comment by wisepotato** [comment]
I'll need to take some time to look into this, is this not something you can handle in the controller/service layer for now? As a workaround

**Comment by ngboardway** [comment]
We are working around this for now, yes. We would just like this functionality to be available to keep things clean/ uniform.

**Comment by wisepotato** [comment]
@maurei could you integrate this into the PR for hooks? Its a small fix

**Comment by maurei** [comment]
Afaik there is no reason it's set to `internal`, but haven't researched it properly, probably @jaredcnance would know this off the top of his head. 

That being said I've seen many other methods/properties throughout the codebase that are set `internal` or `private`, which as far as I can see just obstructs the extensibility, so I think we can just set it to `protected`.

> but currently both pieces related to sorting are marked internal or protected.

What is the problem btw with `protected` members? These are still accessible in any custom inheriting classes. Could you give me a example why the `protected` member should be `public`?

**Comment by jaredcnance** [comment]
I can't remember the motivation for making this internal off the top of my head right now. Usually, the reason for making a method `internal` is because it increases the surface area of the public API and makes it more difficult to reason about which changes are potentially breaking. So, usually when an API is added, if no use case exists (at that time) to publicly expose it, then I wouldn't. In this case `DefaultSort` provides the framework default behavior. If you want to override this, then just inherit from the type and provide a new implementation for `GetDefaultSortOrder()`.

**Comment by ngboardway** [comment]
We are implementing IEntityRepository to create a base (generic) repository for our non-ef models/ data access similar to the default entity repository. To that end we are trying to replicate this behavior.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/0416df760719a41612fda20bae21e3f7d6707855/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L119-L138

I'm proposing making DefaultSort public because trying to access the member in that way would result in errors that it is inaccessible due to its protection level (that's the message we get in a test to access GetDefaultSortOrder, which is protected).

**Comment by jaredcnance** [comment]
Makes sense. Public accessibility should be fine here.

**Comment by maurei** [comment]
made it public in 86e11d4c5ad6ad5c2ca7ca6baf253cff52719a48
