### ISSUE TITLE
Calling 'AddJsonApi' bypass all the exception handler middlewares

### ISSUE THREAD

**Issue by mabead** [json-api-dotnet/JsonApiDotNetCore#501]
## Description

Before using JsonApiDotNetCore, I had an ASP.NET Core middleware that had the responsibility to reformat all exceptions that occured in my controllers. This middleware was almost identical to [this one](http://anthonygiretti.com/2018/09/04/asp-net-core-2-1-middlewares-part1-building-a-custom-middleware/).

As soon as I started to use JsonApiDotNetCore by calling `AddJsonApi`, my middleware stopped working. This is because AddJsonApi registers an exception filter:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8570b216c7ede3a7b5f9fc7a4912404a14926df5/src/JsonApiDotNetCore/Extensions/IServiceCollectionExtensions.cs#L82

This exception filter handles **all** exceptions. My middleware is therefore unable to detect the exception.

Is there a way to disable this exception filter or to limit this exception filter to the routes that to use JSONAPI? My routes that don't use JSONAPI should still use my exception middleware.

## Environment

- JsonApiDotNetCore Version: 3.1.0.0

**Comment by mabead** [comment]
IMHO, the `JsonApiExceptionFilter` should only handle the exceptions that occur within a controller that inherits from `JsonApiController`.

**Comment by wisepotato** [comment]
I think being able to define your own exception filter is the better option here, and i get your point, but it should also happen for the mixin controller, not the derived jsonapicontroller

**Comment by mabead** [comment]
Providing my own exception filter sure is a powerful option. But I feel that calling `AddJsonApi` should not change the behavior of an existing code base (which it currently does). New users of JsonApiDotNetCore won't typically dig in the details of how this call affects the ASP.NET Core pipeline. Instead, JsonApiDotNetCore should, in my opinion, be as friction free as possible. I would suggest to add something like the following at the beginning of `JsonApiExceptionFilter.OnException`:

```csharp
var controllerActionDescriptor = context.ActionDescriptor as ControllerActionDescriptor;
if (controllerActionDescriptor == null)
{
    return;
}

var mixinControllerType = typeof(JsonApiControllerMixin);
if (!mixinControllerType.IsAssignableFrom(controllerActionDescriptor.ControllerTypeInfo))
{
    return; // Error is not from a JSONAPI controller. Don't intervene in the process.
}
```

What do you think of the idea?

In the mean time, I have no choice but to manually remove the JsonApiExceptionFilter from the list of filters added to MVC.

**Comment by jaredcnance** [comment]
Another option would be to just inspect the ContentType of the request and only handle failures for application/vnd.api+json

**Comment by maurei** [comment]
For v4.0 I think we could implement the proposal of either @mabead or @jaredcnance. I'm not sure which one is better

**Comment by wisepotato** [comment]
I disagree with @mabead that jsonapi should not change existing code base, as the errors should be Json:api spec. But you should be allowed to turn them off, or atleast alter the conditions under which they are run.

**Comment by maurei** [comment]
I'm currently looking into this now. The[ official docs have the following to say](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.0#exception-filters) about the usage of exception filters. 

>  Use exception filters only where error handling differs based on which action method is called. For example, an app might have action methods for both API endpoints and for views/HTML. The API endpoints could return error information as JSON, while the view-based actions could return an error page as HTML.

So this suggests it would be a good practice to implement something like @mabead proposes, because with this it targets only the JsonApiDotNetCore actions. On top of that, to allow for extensibility, we could stuff this functionality in a service that we inject in the exception filter, allowing users to customize how the filter behaves without having to mess with removing and readding filters.

**Comment by maurei** [comment]
Custom exception handling is now supported, see #586
