### ISSUE TITLE
HTTP PATCH doesn't update nested owned types

### ISSUE THREAD

**Issue by ayoung-cforp** [json-api-dotnet/JsonApiDotNetCore#515]
## Description

My data model has nested "owned" types.  Owned types that are direct parents of a resource can be patched just fine, but when an owned type "owns" anther type, PATCH still succeedes but ignores the nested fields.  The relevant part of the data model looks like this:

```C#
public class Student : Identifiable<string>
{
	[Attr] public string FirstName { get; set; }
	[Attr] public string LastName { get; set; }
	[Attr] public ParentInfo Parent1Info { get; set; } = new ParentInfo();
	[Attr] public ParentInfo Parent2Info { get; set; } = new ParentInfo();
}

[Owned]
public class ParentInfo
{
	[JsonProperty] public string FirstName { get; set; }
	[JsonProperty] public string LastName { get; set; }
	[JsonProperty] public Address HomeAddress { get; set; } = new Address();
	[JsonProperty] public Address WorkAddress { get; set; } = new Address();
}

[Owned]
public class Address
{
	[JsonProperty] public string StreetNumber { get; set; }
	[JsonProperty] public string StreetName { get; set; }
}
```

From what I understand, owned types use "table splitting", so this data model produces a `Student` table with columns `Id, FirstName, LastName, Parent1Info_FirstName, Parent1Info_LastName, Parent1Info_HomeAddress_StreetNumber, Parent1Info_HomeAddress_StreetName, Parent1Info_WorkAddress_StreetNumber, Parent1Info_WorkAddress_StreetName, Parent2Info_FirstName, Parent2Info_LastName, Parent2Info_HomeAddress_StreetNumber, Parent2Info_HomeAddress_StreetName, Parent2Info_WorkAddress_StreetNumber, Parent2Info_WorkAddress_StreetName`

If I initialize the database with sample data, it works, and an HTTP GET request will return the complete resource including nested owned fields:

```C#
context.Add(new Student {
	Id = "D80C6C3B-DAB3-4814-B4F5-28204D9DD328",
	FirstName = "Laurent",
	LastName = "Brosseau",
	Parent1Info = new ParentInfo {
		FirstName = "Karl",
		LastName = "Brosseau",
		HomeAddress = new Address {
			StreetNumber = "1",
			StreetName = "Home Address St."
		},
		WorkAddress = new Address {
			StreetNumber = "2",
			StreetName = "Work Address St."
		}
	}
});
```

But if I attempt to update the resource with an HTTP patch, the ParentXInfo.HomeAddress/WorkAddress fields are not updated.

Here is the body of the HTTP PATCH:

```json
{
	"data": {
		"id":"D80C6C3B-DAB3-4814-B4F5-28204D9DD328",
		"type":"students",
		"attributes":{
			"firstName":"LaurentZ",
			"lastName":"BrosseauZ",
			"parent1Info":{
				"firstName":"KarlZ",
				"lastName":"BrosseauZ",
				"homeAddress":{
					"streetNumber":"1Z",
					"streetName":"Home Address St.Z"
				},
				"workAddress":{
					"streetNumber":"2Z",
					"streetName":"Work Address St.Z"
				}
			}
		}
	}
}
```

The PATCH succeeds, and here is the return value (important part is how the `homeAddress` and `workAddress` fields haven't been updated:

```json
{
    "data": {
        "attributes": {
            "firstName": "LaurentZ",
            "lastName": "BrosseauZ",
            "parent1Info": {
                "firstName": "KarlZ",
                "lastName": "BrosseauZ",
                "homeAddress": {
                    "streetNumber": "1",
                    "streetName": "Home Address St."
                },
                "workAddress": {
                    "streetNumber": "2",
                    "streetName": "Work Address St."
                }
            },
            "parent2Info": {
                "homeAddress": {},
                "workAddress": {}
            }
        },
        "type": "students",
        "id": "D80C6C3B-DAB3-4814-B4F5-28204D9DD328"
    }
}
```

I tried overriding `PatchAsync()` in my StudentsController, and the `[FromBody] Student entity` argument is being received with the `homeAddress` and `workAddress` fields as they were specified in the request body.

Here's a snapshot of the debug output, showing the update command being executed on the db:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[@p4='D80C6C3B-DAB3-4814-B4F5-28204D9DD328' (Nullable = false) (Size = 36), @p0='LaurentZ' (Size = 8), @p1='BrosseauZ' (Size = 9), @p2='KarlZ' (Size = 5), @p3='BrosseauZ' (Size = 9)], CommandType='Text', CommandTimeout='30']
      UPDATE "Students" SET "FirstName" = @p0, "LastName" = @p1, "Parent1Info_FirstName" = @p2, "Parent1Info_LastName" = @p3
      WHERE "Id" = @p4;
      SELECT changes();
```

It looks like JsonApiDotNetCore is not mapping nested owned fields when doing a PATCH.  It is mapping them the other direction, though, since HTTP GET works correctly.

## Environment

- JsonApiDotNetCore Version: 4.0.0-alpha2
- Other Relevant Package Versions: Microsoft.AspNetCore.App (2.2.0), Microsoft.EntityFrameworkCore.Sqlite (2.2.4)

**Comment by milosloub** [comment]
@ayoung-cforp Hi, can you check if you can do it with pure EF Core approach without JADNC library? I think it's related to this issue, but havent tried
https://github.com/aspnet/EntityFrameworkCore/issues/12118

**Comment by ayoung-cforp** [comment]
Thanks for the quick follow-up.  I think that issue is precisely the problem.

It's quite misleading that [Microsoft's EF Core documention itself describes the exact thing I'm trying to do](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities) even though it's broken!

It looks like it might be fixed in version 3.0.  I'm going to switch to VS 2019 preview and try it out.

**Comment by ayoung-cforp** [comment]
I can confirm that it now works after switching to .NET Core 3.0 / Microsoft.EntityFrameworkCore.Sqlite 3.0.0-preview5.19227.1, with one caveat (this isn't a JsonApiDotNetCore problem, though maybe others will find it useful):

When I initialize owned types, at least one field (that is not another nested type) needed to be set to a non-null value, otherwise patching would fail with an error like this:

```
System.InvalidOperationException: The instance of entity type 'Student.Parent1Info#ParentInfo' with the key value '{StudentId: d80c6c3b-dab3-4814-b4f5-28204d9dd328}' is marked as 'Added', but the instance of entity type 'Student' with the key value '{Id: d80c6c3b-dab3-4814-b4f5-28204d9dd328}' is marked as 'Modified' and both are mapped to the same row.
         at Microsoft.EntityFrameworkCore.Update.ModificationCommand.AddEntry(IUpdateEntry entry)
```

This was pretty easy to work around:

```C#
[Owned]
public class ParentInfo
{
	[JsonProperty] public string FirstName { get; set; } = "";
	[JsonProperty] public string LastName { get; set; }
	[JsonProperty] public Address HomeAddress { get; set; } = new Address();
	[JsonProperty] public Address WorkAddress { get; set; } = new Address();
}

[Owned]
public class Address
{
	[JsonProperty] public string StreetNumber { get; set; } = "";
	[JsonProperty] public string StreetName { get; set; }
}
```

**Comment by wisepotato** [comment]
Closing as its not a JsonApiDotNetCore problem
