### ISSUE TITLE
IsImmutable does not throw an error

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#534]
I would expect `isImmutable` property of `Attr` to throw an error when i am updating an entity

tests:
* If i update a todo with immutable property (x) and mutable property (y), i expect an error (401/403 whatever) to be thrown or atleast for me to define the expected behaviour
* If i update a todo with immutable property (x) only I expect an error

follow up: Can i define a property to not be settable on create?

**Comment by maurei** [comment]
Fixed in #558
