### ISSUE TITLE
Missing null check in ParseSortParameters

### ISSUE THREAD

**Issue by joshdenable** [json-api-dotnet/JsonApiDotNetCore#543]
## Description

Hi all,
When requesting using a query string with an empty sort segment, e.g.
```/api/...?sort=```
or 
```/api/...?sort=text,,number```, 
a 500 is thrown instead of gracefully handling the exception. This seems to be because there's a missing null check [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/c6762b399bca08712650b1ae2bf4b06d9da957a6/src/JsonApiDotNetCore/Services/QueryParser.cs#L162). 

I'd imagine that the intended behaviour should be to skip over this `if` block in the case that the `sortSegment` is null, however I could imagine that preventing empty sort segments at this point could also be beneficial.

## Environment

- JsonApiDotNetCore Version: 3.1.0, 4.0.0-alpha3
- Other Relevant Package Versions:

**Comment by wisepotato** [comment]
Hi this will be fixed with the next alpha release
