### ISSUE TITLE
Unable to cast object of type 'System.DBNull' to type 'System.DateTime'

### ISSUE THREAD

**Issue by andrei-tara** [json-api-dotnet/JsonApiDotNetCore#546]
## Description
I have a DateTime field that can be null when calling GET the following error is thrown:
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.DateTime'.
         at MySqlConnector.Core.Row.GetDateTime(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 285
      
I've also tried adding
[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
...

## Environment

- JsonApiDotNetCore Version: 3.1.0

**Comment by wisepotato** [comment]
could you show me your full model?

Are you using a non-nullable datetime value?

**Comment by maurei** [comment]
Hi Andrei, thanks for opening an issue.  I'm suspecting this error has to do with your setup. 

Note that in C#, the type `DateTime` is a value-type and which means it is non-nullable, but mysql allows for nullable `DATETIME` fields. It looks like your connector is trying to map a nullable database field to a non-nullable C# type, i.e. I think your model should use `DateTime?` in your model.

Looking at your stacktrace it seems like you're using a custom connector. EF Core would have handled this correctly by default. Is there a particular reason you can't use EF Core?

Closing this issue for now, but sure to let us know if there is more to this issue
