### ISSUE TITLE
DbContext without defining DbSets are not Supported

### ISSUE THREAD

**Issue by ahmadalli** [json-api-dotnet/JsonApiDotNetCore#550]
## Description

this is my DbSet:

```csharp
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        Type[] types = typeof(AppDbContext).GetTypeInfo().Assembly.GetTypes();
        IEnumerable<Type> typesToRegister = types
            .Where(type => type.GetInterfaces()
                .Where(i => i.IsGenericType)
                .Any(i => i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>)));

        foreach (var type in typesToRegister)
        {
            dynamic configurationInstance = Activator.CreateInstance(type);
            addConfiguration(modelBuilder, configurationInstance);
        }

        base.OnModelCreating(modelBuilder);
    }

    private static void addConfiguration<TEntity>(ModelBuilder modelBuilder, IEntityTypeConfiguration<TEntity> configuration)
        where TEntity : class
    {
        configuration.Configure(modelBuilder.Entity<TEntity>());
    }
}
```

and I configure each model using

```csharp
#region configurations
public class Configuration : IEntityTypeConfiguration<Person>
{
    public void Configure(EntityTypeBuilder<Person> builder)
    {
        builder.ToTable(nameof(Person).Pluralize());
        builder.HasKey(x => x.Code);

        builder.Ignore(x => x.Id).Ignore(x => x.StringId);
    }
}
#endregion
```
inside my model.

but when I try to load `PersonController`, 'm getting this error:
> A resource has not been properly defined for type 'Person'. Ensure it has been registered on the ResourceGraph.

## Environment

- JsonApiDotNetCore Version: 3.1.0
- Other Relevant Package Versions:

**Comment by wisepotato** [comment]
As the error states, you will ned to register it to the resourcegraph https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html

**Comment by ahmadalli** [comment]
the point is I'm using entity framework discovery method but it doesn't support models built by model builder instead of dbset

**Comment by wisepotato** [comment]
Ah. That might be true, as we expect there to be a DbSet Available, I don't know if this is an easy fix at the moment. If you have time for investigation you are more than welcome to add a pull request as  this does seem like an OK things to support. I don't have much need for this feature as I explicitly define my models.

If we get more requests in this area we can consider devoting some time to it.

**Comment by ahmadalli** [comment]
@wisepotato could you please show me some initial point to investigate the issue?

**Comment by wisepotato** [comment]
To be honest? Wait a week. We are working on decoupling the JsonApiContext (where you're getting your error) and making it more testable and (hint hint) more extendable for different uses.

You're getting the error here:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8cca15a5ba42f8543ae937a2dcc867ee6cd303ff/src/JsonApiDotNetCore/Services/JsonApiContext.cs#L75-L77

But in our version, that we're working on for V4, the `_controllerContext` is non-existent. So what I suggest is: either help and see if you can make a basic testable example project (which helps us immensely) and do that in the branch .

New version is here: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/feat/context-decoupling/src/JsonApiDotNetCore/Services/JsonApiContext.cs#L79, as you see the function that throws your errors has been made obsolete. (and for good reason!)

**Comment by ahmadalli** [comment]
I found it but I'm not sure how can I fix it. 

we need an instance of dbContext here:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/ec4e76e51d8b4b0dfcd58d6ce3e993d69c7ecedc/src/JsonApiDotNetCore/Builders/ContextGraphBuilder.cs#L239

then we can change `AddDbContext` to something like this:

```csharp
public IResourceGraphBuilder AddDbContext<T>() where T : DbContext
{
    _usesDbContext = true;

    var contextType = typeof(T);
    var dbContext = // get the instance of T here
    var types = contextType.GetProperties()
        .Where(t => t.PropertyType.IsGenericType)
        .Where(t => t.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>))
        .Select(t => t.PropertyType.GetGenericArguments()[0])
        .Union(dbContext.Model.GetEntityTypes().Select(et => et.ClrType))
        .Distinct();

    foreach (var entityType in types)
    {
        AssertEntityIsNotAlreadyDefined(entityType);

        var (isJsonApiResource, idType) = GetIdType(entityType);
        if (!isJsonApiResource) continue;

        var resourceName = _resourceNameFormatter.FormatResourceName(entityType);
        _entities.Add(GetEntity(resourceName, entityType, idType));
    }

    return this;
}
```

**Comment by wisepotato** [comment]
I mean i cant validate if this works, but if you're free to add this to master via a pull request, i welcome it.

**Comment by ahmadalli** [comment]
the problem is I don't know how can I get the instance of `T` in this context. we need access to service provider

**Comment by ahmadalli** [comment]
P.S. I've added the properties for now but it'd be good if we solved that issue too

**Comment by maurei** [comment]
Hi @ahmadalli, thanks for opening up this issue. It seems like a useful thing to support. Like you mentioned, we need to access the service provider to get an instance of the DbContext, but at the time of calling `AddDbContext<T>` the service provider has not yet been build. Some thoughts on this:

1. Possibly we could build an intermediate service provider that we use only here. This needs investigation.
2. Alternatively, this could just be a design smell, i.e. maybe it suggests we should look in a different direction to solve this issue.

Note that we currently have very limited capacity to work on this. As @wisepotato mentioned, we are currently prioritising #504, which is required for `JsonApiDotNetCore` to be truly production ready (due to testability).  

To advance with your project, I think [manually constructing the resource graph](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html#manual-specification)
 should work. Have you tried this? 

If you're interested in really tackling this issue yourself, hit me up in our gitter channel!

**Comment by maurei** [comment]
#581 introduces the usage of an intermediate service provider in the `IServiceCollectionExtensions` we needed in this issue.
