### ISSUE TITLE
Upgrade to .net core 3.0 

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#559]
As title says

**Comment by emouawad** [comment]
Not sure if this is related:

`System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Method 'CommitAsync' in type 'JsonApiDotNetCore.Extensions.SafeTransactionProxy' from assembly 'JsonApiDotNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'`

on

          app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });

**Comment by wisepotato** [comment]
Working on this atm, will post back with updates.

**Comment by wayne-o** [comment]
Would this have made it into 3.1.0?

**Comment by maurei** [comment]
No, the .NET core 3.0 upgrade has been introduced in prerelease v4.0.0-alpha4
