### ISSUE TITLE
Cleanup tests for v4

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#566]
We will be doing something akin to #91 

* A better split between `unit`, `acceptance` and `e2e` with a 70, 20, 10 split
* No more hand building  requests, need factories for that
* Clean up naming convention.

**Comment by maurei** [comment]
see [CreatingDataTests](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/dev-v4/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/CreatingDataTests.cs) in dev-v4 for example of how tests can currently be more lean

**Comment by bart-degreed** [comment]
Superseded by #715.
