### ISSUE TITLE
Consider implementing AsyncEnumerable<T> for paging

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#570]
`AsyncEnumerable<T>` was designed to solve problems like returning a paged API response from an API in a more efficient way than currently implemented. See [this blog](https://dev.to/dotnet/what-s-the-big-deal-with-iasyncenumerable-t-in-net-core-3-1eii).

Consider implementing this in JsonApiDotNetCore

**Comment by jeff-becker-projekt202** [comment]
Is this in reference to IResourceReadRepository.PageAsync and DefaultResourceService.ApplyPageQueryAsync?

**Comment by maurei** [comment]
Yep. Off the top of my head it would probably mean that we would need a controller returning `AsyncEnumerable<T>`, but all of these needs some investigation

**Comment by bart-degreed** [comment]
Copied from Gitter channel:

Björn Harrtell @bjornharrtell Sep 25 20:42
> @bart-degreed: What was the reason to move from IEnumerable to IReadOnlyCollection in many instances? I would expect the lazyness of IEnumerable to be a good thing in some cases?

Bart Koelman @bart-degreed Sep 28 10:33
> @bjornharrtell Great question! I wanted to use IAsyncEnumerable, which provides async streaming of data. In theory this allows to start writing to the response while new records are still being received, decreasing both roundtrip time and memory usage. Two reasons kept me from doing this. First, to use IAsyncEnumerable with EF Core, some unintuitive tricks are required (see dotnet/efcore#18220). The second reason is that, due to various callbacks, we call .ToList() first anyway to prevent enumerating multiple times. Even if that were not the case in the service layer, the same happens in the serialization layer. So the functional requirement is to provide a collection of resources instead of a sequence, and IReadOnlyCollection expresses that.

**Comment by bjornharrtell** [comment]
@bart-degreed: I would imagine streaming out the response also has the issue/drawback that if an error occurs it will not be able to communicate that properly (as the HTTP header is already sent as OK or something else indicating success)

**Comment by bart-degreed** [comment]
@maurei based on discussions above, I think this can be closed.

**Comment by maurei** [comment]
Agreed
