### ISSUE TITLE
Problem with custom object changing while overriding UpdateAsync

### ISSUE THREAD

**Issue by N1ghtStorm** [json-api-dotnet/JsonApiDotNetCore#575]
## Description

I have a model, that has it's DbSet in DbContext
 ```cs
    public class Human : Identifiable
    {
        [Attr("name")]
        [StringLength(128)]
        public string Name { get; set; }

        [Attr("second-name")]
        [StringLength(128)]
        public string  SecondName{ get; set; }
    }
 ```
I have a JsonApiController, where PatchAsync method is overriden:

 ```cs
public class PeopleController : JsonApiController<Human>
{
              public PeopleController(
              IJsonApiContext json_api_context,
              IResourceService<Human> resource_service,
              ILoggerFactory logger_factory,
                : base(json_api_context, resource_service) {}

// Patch method:
     [HttpPatch("{id}")]
     public async override Task<IActionResult> PatchAsync(int id, [FromBody]Human human)
     {
         human.SecondName = "Some Second Name";
         return base.PatchAsync(id, human);
     }
}
 ```

The problem is:
This operation
 ```cs
"human.SecondName = "Some Second Name"
 ```
doesnt affect state of "human" object, we even can return base method like this:
 ```cs
"return base.PatchAsync(id, new Human());"
 ```
or
 ```cs
"return base.PatchAsync(id, null);"
 ```
the final changes in database will be taken from initial state of entity(that was taken exactly from request)

}

## Environment

- JsonApiDotNetCore Version: 3.1
- .Net Core 2.2
- Other Relevant Package Versions:

**Comment by maurei** [comment]
This problem is described in https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/536 and also describes a work around. 

This issue will be tackled in v4

**Comment by N1ghtStorm** [comment]
This problem is described in #536 and also describes a work around.
