### ISSUE TITLE
Typo: LoaDatabaseValues

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#606]
## Description
In class `JsonApiOptions`, there is a property named `LoaDatabaseValues`, which seems incorrect to me.

## Environment
- JsonApiDotNetCore Version: develop branch at 5733fe5c37074b9bbfde284c916ea368a5a0fe6e (today)

**Comment by maurei** [comment]
Good thing you're on develop branch. That's indeed a typo: free to make a PR on this, if not I'll do it upcoming week :)

**Comment by bart-degreed** [comment]
I'll leave this one for you.

**Comment by maurei** [comment]
Fixed
