### ISSUE TITLE
Bug: first/prev links not rendered on second page

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#622]
## Description
When using paging, the `first` and `prev` links are not rendered on the second page.

Example:
First page is at URL /api/books (A), which contains a link to next page: /api/books/?page[number]=1 (B). That page contains a link to its next page: /api/books/?page[number]=2 (C).

Observed behavior:
Page C contains top-level links for `first` and `prev`, but they are missing on page B.

Expected behavior:
I think the correct behavior would be for `first` and `prev` to exist also on page B, because it is the second page.

I traced this down to `LinkBuilder.SetPageLinks(...)`, which conditionally sets them:
```csharp
if (_pageService.CurrentPage > 1)
{
    links.First = GetPageLink(primaryResource, 1, _pageService.PageSize);
    links.Prev = GetPageLink(primaryResource, _pageService.CurrentPage - 1, _pageService.PageSize);
}
```

I think the condition should be changed to > 0, as index 0 appears to be the first page.

## Environment
latest version of Develop branch

**Comment by maurei** [comment]
Thanks for reporting this. I will be looking into it in the beginning of next week.

**Comment by maurei** [comment]
> I think the condition should be changed to > 0, as index 0 appears to be the first page.

Note that the index is 1-based, which means that the value for `Next` was also generated wrongly: it displayed page number 1 under `Next` when having request the first page.

#625 fixes this, and will release a new alpha version by the end of today. Thanks for reporting!

**Comment by bart-degreed** [comment]
Thanks for the fix!
