### ISSUE TITLE
Breaking change: null data returned when resource not found

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#631]
## Description
Earlier, when a resource does not exist, a 404 with an empty response body was returned. After fetch of latest master (with v4 merged in), I am now getting 404 with the next body:

Request URL: https://localhost/api/users/123

Response body:
```json
{
  "links": {
    "self": "https://localhost/api/users"
  },
  "data": null
}
```

Note the `self` link is wrong too: it misses the identity.

Traced this down to https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/a801d958d9640365f459e096b802ad5d90db33fa/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L108, so it may be intentional.

**Comment by maurei** [comment]
[the current response body is conform spec](https://jsonapi.org/format/#fetching-resources-responses-404) (except for the self link). Relevant passage:
> ... except when the request warrants a 200 OK response with null as the primary data (as described above).

It is the result of the rework of the serialization layer: it serializes `null` as `null` instead of throwing a 404. I personally prefer using 404s for non-existing routes as opposed to non-existing resources.

Nevertheless the 404 was that was thrown previously was also conform spec. We could add a switch for that in `IJsonApiOptions` or even allow to configure this on the level of each resource.

**Comment by maurei** [comment]
I will make a separate issue for the bad self link

**Comment by bart-degreed** [comment]
Perhaps I am missing something, but the spec reads:
```
A server MUST respond with 404 Not Found when processing a request to fetch a single resource that does not exist, except when the request warrants a 200 OK response with null as the primary data (as described above).
```

Both are not happening. The spec refers to a 200 with null data -or- a 404. This issue is about 404 comined with null data, which is not what the spec describes.

A bit below:

```
A server MAY include error details with error responses.
```

What is currently implemented is not error details, but a success response body, combined with a http status code that represents an error.

**Comment by maurei** [comment]
Ah -- my bad. I misread and thought it was returning a 200 with that error body. I will investigate and fix this next week.

**Comment by wisepotato** [comment]
working on this.

**Comment by maurei** [comment]
Yep, that's correct. Elaborating on your last point

> * Return a `404` when the requested route could **never** return a resource.

Would be good if an error object was returned.

Pointers:
- [this is where the error object is currently being formatted](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/a801d958d9640365f459e096b802ad5d90db33fa/src/JsonApiDotNetCore/Formatters/JsonApiWriter.cs#L48)
- [this is (I think) the origin of the 404 that is currently being thrown](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/b5207ec64a1d5a6e7daca934e0ce778e906d36e0/src/JsonApiDotNetCore/Services/DefaultResourceService.cs#L144)

**Comment by bart-degreed** [comment]
> Return a 200 when the route exists, but no data is returned.

I think this is not compliant to the spec:
```
A server MUST respond with 404 Not Found when processing a request to fetch a single resource that does not exist
```

**Comment by maurei** [comment]
The same line in the spec states an exception to that rule: 

> except when the request warrants a 200 OK response with null as the primary data (as described above).

Where I believe the *as described above* refers to the following passage:

> null is only an appropriate response when the requested URL is one that **might correspond to a single resource, but doesn’t currently**.

I.e. my reading of the specs is that when a route (i.e. relationship) exists (`articles/1/author`) but there is no associated data, it's okay to return `null` as the primary data with HTTP 200.

But IMO all of this is pretty ambiguous :/ This rule + exception is explicitly formulated for fetching single resources. Nothing is stated about the analogous scenario of a has-many route (route `articles/1/tags`). The equivalent of this rule+exception would be either a 404 or an empty list of resource objects `[ ]` (rather than `null`) as the primary data.

**Comment by bart-degreed** [comment]
> null is only an appropriate response when...

I believe this applies solely to related data, as stated in the Note block below it and illustrated by the example.

In short: `http://example.com/articles/1/author` may return 200 when article 1 exists, but does not have an associated author.

Then, the spec resumes:
> A server MUST respond with 404 Not Found when processing a request to fetch a single resource that does not exist, except when the request warrants a 200 OK response with null as the primary data (as described above).

The "except when... described above" refers to the author example. In all other cases, 404 must be used.

So I believe it is wrong to return 200 for `http://example.com/articles/1` when article 1 does not exist. And that is the scenario I submitted this bug for.

**Comment by wisepotato** [comment]
This is in-line with what @maurei  have discussed. However, we also discussed that the 200 should apply for when user id =1, exists and a GET request is sent to:


```
http://example.com/users/1/books
```
Books being a to-many resource, but this is **not** described in the spec, but we made a judgement call.

We are in agreement, but the spec is ambiguous on the multiple resources front.

**Comment by bart-degreed** [comment]
Thanks for the clarification.

**Comment by wisepotato** [comment]
hi #640  was just merged, which is the preliminary to #636. We're working on it.

**Comment by bart-degreed** [comment]
#640 breaks our code. It throws at: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/d9dd76069a35bfbd8bb180ff83213014d2601b10/src/JsonApiDotNetCore/Middleware/CurrentRequestMiddleware.cs#L119

This is because we encode our IDs, to prevent callers guessing IDs. And in some cases, they contain additional information needed to fetch the right data. So our requests look like:

```
/api/videos/ngebwA
```

For this to work, we have a custom base class that derives from `Identifiable<T>`, overriding `GetStringId` and `GetTypedId`. Additionally we do the same conversion in a custom controller base class. So while our `TId` in controllers/resources is `Int64`, the URL contains encoded strings.

**Comment by bart-degreed** [comment]
Looking at the changes, the trim/split/findindex url parsing feels a bit brittle to me. Wouldn't it be an option to use the route values, like it is done at:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/d9dd76069a35bfbd8bb180ff83213014d2601b10/src/JsonApiDotNetCore/Middleware/CurrentRequestMiddleware.cs#L251?

For example, the debugger shows me for the request path:
```
api/v3/users/ABC/completions
```

these route values:
```
{
  "action": "GetRelationship"
  "controller": "Users"
  "id": "ABC"
  "relationshipName": "completions"
}
```

Hope this helps.

**Comment by wisepotato** [comment]
Thank you, apparently the test cases were not comprehensive, the `RequestMiddleware` was not tested before this PR, so this was bound to happen. Could you make a new issue? That would help, for when I get to it tomorrow

**Comment by maurei** [comment]
Having obfuscated ID's is a good use-case. A way forward could be to not throw in the current request middleware but just store the route data as is.
