### ISSUE TITLE
Is this library proper to use for MongoDB?

### ISSUE THREAD

**Issue by mcopur** [json-api-dotnet/JsonApiDotNetCore#635]
## Description

I want to ask a question.I want to implement JSON:Api complaint service library for my project and I am using MongoDB as database. Is this library proper to use for MongoDB?

**Comment by maurei** [comment]
There currently is no off the shelve support for MongoDB.Driver, although with the current extensibility of JADNC I believe one should be able to register a mongodb implementation of the [repository layer](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Data/IResourceRepository.cs).

In the future I'm planning on abstracting away the current default repository layer (which works with EF Core) into an optional EF core extension package for this library, and adding MongoDB as a second option for the data layer. But that work hasn't started yet

**Comment by alastairtree** [comment]
Quick update - there is a PR containing a beta MongoDB implementation over at https://github.com/json-api-dotnet/JsonApiDotNetCore.MongoDb/pull/2
