### ISSUE TITLE
Question: which layer to implement audit fields

### ISSUE THREAD

**Issue by fdlane** [json-api-dotnet/JsonApiDotNetCore#637]
## Description
Currently I am implementing audit fields in the service layer.  However, the values are only persisted to the db if the api user includes the properties in the request.  

   `entity.EditedBy = _currentUser.Username;` is not applied if the user does not include the property in the `Patch` request.

How do I get the audit fields to always be persisted?

```c#
public BaseService(
  IJsonApiContext jsonApiContext,
  IEntityRepository<T, Guid> repository,
  ILoggerFactory loggerFactory,
  ICurrentUser currentUser) : base(jsonApiContext, repository, loggerFactory)
{
  _currentUser = currentUser;
}

public override async Task<T> CreateAsync(T entity)
{
  entity.CreatedBy = _currentUser.Username;
  var newEntity = await base.CreateAsync(entity);
  return newEntity;
}

public override async Task<T> UpdateAsync(Guid id, T entity)
{
  entity.EditedBy = _currentUser.Username;
  entity.EditedDate = DateTime.Now;

  var updatedEntity = await base.UpdateAsync(id, entity);

  return updatedEntity;
}
```

## Environment

- JsonApiDotNetCore Version: v4.0.0-alpha3

**Comment by maurei** [comment]
Hi @fdlane, this indeed is a bit less easy than one would expect. Internally the repository accesses the a list of all targeted attributes to know which ones to update:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/1ac9d9caaefd87ae417f98faa1e0d541ae1a9ca4/src/JsonApiDotNetCore/Data/DefaultResourceRepository.cs#L190
That means `AttrAttribute` instance associated to your `EditedBy` and `EditedDate` field must be in that list. Indeed, this is taken care of under the hood when an attribute is targeted through a `PATCH` request. In your case you would have to add this attribute to the list manually.

 In `v4.0.0-alpha4` this is relatively straight forward using the `ITargetedFields` and `IResourceGraphExplorer` services:

```c#
public BaseService(
  ... ,
  ITargetedFields targetedFields,
  IResourceGraphExplorer graph,
  ...) : base( ... ) { ... }

public override async Task<T> UpdateAsync(Guid id, T entity)
{
  entity.EditedBy = _currentUser.Username;
  entity.EditedDate = DateTime.Now;

  var attributes = _graph.GetAttributes<YourResource>( r => new { r.EditedBy, r.EditedDate });
  _targetedFields.AddRange(attributes);

  var updatedEntity = await base.UpdateAsync(id, entity);

  return updatedEntity;
}
```

I see you're on `alpha3` though. There, the equivalent of `ITargetedFields` is the `AttributesToUpdate` on `IJsonApiContext`: 
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/ec4e76e51d8b4b0dfcd58d6ce3e993d69c7ecedc/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L271

To get a hold of the attributes see my post here https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/536#issue-462522626. That is still a bit complicated in alpha3. I would recommend you to switch to alpha4 ASAP anyway.

Let me know if that helps!

**Comment by fdlane** [comment]
This was a great help and we will be moving to alpha4 soon.  Thank you!

My base class based on #536 

```
  public class BaseService<T> : EntityResourceService<T, Guid> where T : BaseEntity
    {
      private readonly ICurrentUser _currentUser;
      private readonly IResourceGraph _resourceGraph;
      private readonly IJsonApiContext _jsonApiContext;

      public BaseService(
        IJsonApiContext jsonApiContext,
        IEntityRepository<T, Guid> repository,
        ILoggerFactory loggerFactory,
        IResourceGraph resourceGraph,
        ICurrentUser currentUser) : base(jsonApiContext, repository, loggerFactory)
      {
        _currentUser = currentUser;
        _resourceGraph = resourceGraph;
        _jsonApiContext = jsonApiContext;
      }

      public override async Task<T> CreateAsync(T entity)
      {
        entity.CreatedBy = _currentUser.Username;
        var newEntity = await base.CreateAsync(entity);
        return newEntity;
      }

      public override async Task<T> UpdateAsync(Guid id, T entity)
      {
        entity.EditedBy = _currentUser.Username;
        entity.EditedDate = DateTime.Now;

        var editedByAttribute = _resourceGraph.GetContextEntity(typeof(T)).Attributes.Single(a => a.InternalAttributeName == "EditedBy");
        _jsonApiContext.AttributesToUpdate.Add(editedByAttribute, editedByAttribute);

        var editedDateAttribute = _resourceGraph.GetContextEntity(typeof(T)).Attributes.Single(a => a.InternalAttributeName == "EditedDate");
        _jsonApiContext.AttributesToUpdate.Add(editedDateAttribute, editedDateAttribute);

        var updatedEntity = await base.UpdateAsync(id, entity);

        return updatedEntity;
      }
    }
```

**Comment by fdlane** [comment]
Thanks for the help.
