### ISSUE TITLE
Adding custom methods to controllers

### ISSUE THREAD

**Issue by CrispyBaguette** [json-api-dotnet/JsonApiDotNetCore#648]
Hello, I have a question.

I am currently porting parts of an existing API to this framework. One of the functionalities I need to replicate is the ability to export data in Excel format. It's currently accessed using a route that looks something like that: `api/<Resource>/{id}/export`.

Would it be possible to add a method to handle this route to a `JsonApiController`, or do I need to implement it elsewhere ?

## Environment

- JsonApiDotNetCore Version: 3.1

**Comment by wisepotato** [comment]
We do this in our own internal API as well. You need to create a controller anyway and you can just add another route/method. It works like a normal controller.
