### ISSUE TITLE
FilterQueryContext naming

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#654]
A `FilterQueryContext` currently has a `FilterQuery` Inside of it. So far so good.

This `FilterQuery` also has an `Attribute` property, which would make sense because usually filters are defined on attributes. BUT what if they are not? Let's say I have a object with 3 attributes; `firstName`, `tussenVoegsel` and `lastName`. All of these concatenated (with certain rules) would make a full name and I would expect to be able to search on that. (https://en.wikipedia.org/wiki/Tussenvoegsel)

`?filter[fullName]=wise`, would return the results containing wise in any shape or form in the full name.

Ergo: I suggest changing the `Attribute` property to `Key`.

**Comment by fdlane** [comment]
@bart-degreed can this issue be closed because of ...

https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/591/commits/90ab4cf0b1d76b6727f4dafba37ba2c604e3bdda

**Comment by bart-degreed** [comment]
I'm not entirely sure, but I think it can.

@wisepotato Feel free to reopen if needed.
