### ISSUE TITLE
Invalid Patch request body format required (most likely user error)

### ISSUE THREAD

**Issue by martinmike2** [json-api-dotnet/JsonApiDotNetCore#655]
## Description
Either I am doing something incorrectly (likely), or there is an inconsistency with PATCH request required format (unlikely).  I also realize that I am operating with an alpha version, and as such things might be goofy.

I am having a few issues, but the salient issue for this post is that I can't get a PATCH request to result in a deserialized type with the format specified in the json:api spec 1.0

Expected format per spec:
`{
	"data": {
		"type": "users",
		"id": 10,
		"attributes": {
			"userType": "Employee"
		}
	}
}`
This format actually results in a null type being presented to the JsonApiController PatchAsync method.

Actual format required to get a deserialized type that contains the value presented in the userType property (:
`{
    "type": "users",
    "id": "10",
    "userType": "Employee"
}`

All other imagined variations of the request body format either result in null types or types with default values that do not reflect the values passed in the request body.
...

## Environment

- Targeted Version: .netcore3.0
- JsonApiDotNetCore Version: 4.0.0-alpha4
- Other Relevant Package Versions:
-- Microsoft.AspNetCore.Mvc.NewtonsoftJson: 3.1.0
-- Newtonsoft.Json: 12.0.3

**Comment by wisepotato** [comment]
are you sure you're also adding the `application/vnd.api+json` value for the `Content-Type` header.

**Comment by wisepotato** [comment]
if so, if you can make a test that simulates the issue, we can start work on it very quickly.

**Comment by maurei** [comment]
I would expect this to be an issue with the content type, indeed. Any update on this?

**Comment by N1ghtStorm** [comment]
The problem really exists when you dont write "id" section in request(it was possible in 3 version):

![image](https://user-images.githubusercontent.com/43716547/71409622-59442280-2653-11ea-8da4-d7af14c9b491.png)

When field "id" is present in the request and is not 0 the problem dissapears
Ofc i use application/vnd.api+json value for the Content-Type

**Comment by maurei** [comment]
If I remember correctly we changed the "id" member to be required as it required by the spec. Nevertheless the error should be more clear when when this occurs, it shouldn't just fall back on  a reply with regular json output content

**Comment by bart-degreed** [comment]
@martinmike2 Can you please verify if #699 fixes your problem?
