### ISSUE TITLE
Allow user flexibility in authentication/authorization middleware options

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#656]
https://stackoverflow.com/questions/58089827/asp-net-core-authentication-broken-after-upgrade-to-3-0

We need to execute `app.UseAuthentication()` and `app.UseAuthorization()` in between `UseRouting` and `UseEndpoints`. Will investigate.

**Comment by maurei** [comment]
Can you elaborate a bit on this? What is the status on this?

**Comment by Lobosque** [comment]
@bjornharrtell would you please provide an example of how to pass custom Authentication and Authorization as per your Pull Request?

**Comment by bart-degreed** [comment]
@Lobosque In your `Startup.cs`:
```csharp
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public virtual void Configure(IApplicationBuilder app, AppDbContext context)
{
    app.UseJsonApi(_ =>
    {
        app.UseAuthentication();
        app.UseAuthorization();
    });
}
```

**Comment by maurei** [comment]
@Lobosque we're doing some changes in the PR and the example provided in the PR won't be functional in the master branch (see related PR #665, expecting to merge tomorrow)
