### ISSUE TITLE
Bug: Filter passes query validation, but the filter is not applied

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#659]
## Description
Consider the request:

```
/documents/1?include=collaborators&filter[collaborators.first-name]=like:john
```
This request passes query validation, but the filter is not applied. It returns all collaborators. This is likely caused by EF Core not supporting filtered includes. In contrast, the next request:
```
/documents/1/collaborators?filter[first-name]=like:john
```
returns the next error message:
```
Query parameter filter is currently not supported on nested resource endpoints (i.e. of the form '/article/1/author?filter=...'
```

which is helpful. I think the fix would be to return the same error message in this case, instead of silently ignoring the filter.

## Environment
v4.0.0-alpha4

**Comment by bart-degreed** [comment]
I was looking into fixing this, but unfortunately the error is raised from within the query string parsing logic. Since I'm actually using the nested filtering construct for Elasticsearch-based resources (non-Entity Framework Core), I'll leave the bug in for now.

**Comment by maurei** [comment]
This should be a fairly easy issue to pick up for anyone out there looking to make a first contribution. Indeed, it looks like a validation issue in the corresponding `IQueryParameterService` implementation.

**Comment by bart-degreed** [comment]
For my use case, it is unfortunate that the query validation logic is implemented apart from the resource-specific service that can or cannot provide nested includes. To overcome that, the `IResourceService` would need to have some mechanism to expose its capabilities.

I haven't tried, but maybe we can add a capabilities property to IFilterService or its base, and then have `IResourceService` assign that from its constructor.

**Comment by bart-degreed** [comment]
This works correctly for 1-to-1 relationships, but does not apply the filter on 1-to-many.

filtered: /articles?include=author&filter[author.firstName]=John
discarded: /blogs/1?include=articles&filter[articles.title]=like:art
