### ISSUE TITLE
Allow classes which inherit from DefaultResourceRepository more control of SaveChangesAsync

### ISSUE THREAD

**Issue by jeff-becker-projekt202** [json-api-dotnet/JsonApiDotNetCore#666]
## Description
Feature Request: Add methods in DefaultResourceRepository so that derived classes have access to the DBContext and an opportunity to intercept calls to _context.SaveChangesAsync() in CreateAsync, UpdateAsync, UpdateRelationshipsAsync, DeleteAsync.

Use Case: I have a fairly complex order-entry model. Any time any part of the hierarchy is modified I need to load the aggregate root and the subtotals for the entire hierarchy. Simply inheriting  DefaultResourceRepository and overriding the relevant methods presents the following problems:
1) The derived class doesnt have direct access to the DBContext
2) Putting my recalculation call before the call to the base class means the entity instance will not have its relationships loaded which is required in this case to perform the calculation
3) Putting my recalculation call after the call the the base class would result in multiple calls to _dbContext.SaveChangesAsync() and thus multiple database transactions.

I can put together a PR for this if you want.

## Environment

- JsonApiDotNetCore Version: 4.0.0-alpha4
- Other Relevant Package Versions: (presumably all?)

**Comment by maurei** [comment]
Hi @jeff-becker-projekt202, sorry for the delayed response. 


In theory we could expose more direct control of SaveChangesAsync, but I'm wondering how doing that would fit in the bigger picture of a default boilerplate implementation of the repository layer. In such implementation we have attempted to abstract away EF Core API and with that the overhead of having to call methods like SaveChanges. Introducing such method would reflect the EF Core API in the repository API.

A concern with such a change is that we might introduce coupling with a subset of the EF Core API for which there is no equivalent in a different (eg nosql-based) database ORM, i.e. it comes with a risk of loss of generality. 

Nevertheless it is true that the current default repository layer is designed for fairly simple CRUD use-cases, and this might simply not be enough for more complex use-cases such as yours. An alternative strategy could be to design a service (which has access to `DbContext`) and inject that in your repository, and let it deal with any request that requires complex handling. 

Either way, to be able to get a better idea of your requirement in the context of the bigger architectural picture, I would need to have a more detailed idea of what you're trying to achieve, preferably accompanied with some (generic pseudo) code.

**Comment by maurei** [comment]
Feel free to reopen with more information
