### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#678]
Hi @jaredcnance, @maurei and @wisepotato, 

I’m a big fan of the JADNC framework you have developed and our company is starting to use it as a framework for our own APIs. I noticed lately that there was reduced activity in the repository and I wanted to reach out if I could help out as a contributor. I think I have a good grasp on your vision for the framework — see my PRs —  and would love to invest my time to help improve it, in collaboration with you.

Would love to hear from you!
Best, Bart.

**Comment by fdlane** [comment]
I am also a big fan. The framework is working so well our Ember Data projects. How can we help?

**Comment by jaredcnance** [comment]
I haven't had the time to continue working on this project and passed the torch to  @maurei, @wisepotato and a few others. I'm not up to speed on the current status of the project. So, I'll first give them a chance to respond.

**Comment by jeff-becker-projekt202** [comment]
I'd definitely love to jump in and tackle a couple of the open issues in addition to my own wants. I'm just not sure if there's any plans for them specifically.

**Comment by Stefanu83** [comment]
FYI, due to circumstances it may take a bit longer for @maurei to respond. @wisepotato  just started a new job so I don't know if he has time at the moment to respond. But the project is actively worked on by both.

**Comment by wisepotato** [comment]
I don't have time at the moment, but am tracking the contents of this repo as I still like it very much. So expect some prs from me in some time.

**Comment by bart-degreed** [comment]
Is there anything I can do to become a member of the "json-api-dotnet" team? Would love to work on some of the improvements for the framework in collaboration and sign off with the team.

**Comment by maurei** [comment]
Hi people. I have been distracted from JADNC for the past weeks but I definitely have the biggest intentions to keep this project rolling. I am happy to see people are reaching to help out as the workload was starting to exceed what I could handle as a one-man team. I will be more actively monitoring this repo again from now and will guide people in solving issues. I also hope to be finishing the issues that have been on my list (mostly related to releasing v4; we have been on a preview version for too long now)

**Comment by bjornharrtell** [comment]
Also liking this project alot and see myself long term using/contributing to it.

**Comment by maurei** [comment]
I'll be getting back at this with a list of priorities. Obviously, as this is an open-source project these priorities will not be set in stone and your input will be greatly appreciated.

**Comment by ahmadalli** [comment]
I think since asp.net core 2.2 has reached its end of life, releasing a version compatible with asp.net core 3 would be great. I would love if I could help out but unfortunately I don't have time for that

**Comment by maurei** [comment]
@ahmadalli v4 (which is in prerelease) is currently on v3.0. I'm planning on migrating it to v3.1 before fully releasing it.

**Comment by ahmadalli** [comment]
@maurei I've tried the prerelease a few month back but I faced some issues and I needed to clone to project and change some code in order to make it work. unfortunately I don't recall much about what I needed to change in order to make it work

**Comment by bart-degreed** [comment]
Closing, as I'm now a contributor of the project.

I'm tracking pending work for v4 release at #693.

Thanks for all responses so far, looking forward to our future collaborations!
