### ISSUE TITLE
Running JADNC 3.1.0 with netcoreapp3.1

### ISSUE THREAD

**Issue by iamandymcinnes** [json-api-dotnet/JsonApiDotNetCore#686]
Hi I'm currently holding off on moving to v4 as there seems to be a fair few moving parts atm, so I've been trying to get v3.1.0 working with netcoreapp3.1. I just wondered if anyone has had any success, I think I'm running in to issues with the the Json formatters as I'm currently getting this error on my tests:

> {"errors":[{"title":"Object reference not set to an instance of an object.","status":"400","meta":{"stackTrace":["System.NullReferenceException: Object reference not set to an instance of an object.","   at Document JsonApiDotNetCore.Builders.DocumentBuilder.Build(IIdentifiable entity)","   at string JsonApiDotNetCore.Serialization.JsonApiSerializer.SerializeDocument(object entity)","   at string JsonApiDotNetCore.Serialization.JsonApiSerializer.Serialize(object entity)","   at string JsonApiDotNetCore.Formatters.JsonApiWriter.GetResponseBody(object responseObject)","   at async Task JsonApiDotNetCore.Formatters.JsonApiWriter.WriteAsync(OutputFormatterWriteContext context)"]}}]}

```
            services.AddJsonApi(options =>
            {
                options.BuildResourceGraph(builder =>
                {
                    builder.AddResource<MyResource, Guid>("test-resource");
                });
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            }, services.AddMvcCore().AddDataAnnotations().AddNewtonsoftJson().AddAuthorization());
```

**Comment by bjornharrtell** [comment]
I'm running v4 with netcoreapp3.1 and haven't had issues with that combination.

**Comment by maurei** [comment]
I don't think JADNC v3 will work with .NET Core 3^ because a lot of stuff changed in .NET Cores middleware which is not easy to fix as a user; it requires a lot of digging in the internals.

Let me know if you have any more related questions, otherwise closing this issue.
