### ISSUE TITLE
Review logging

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#689]
## Description
Now that we have the right logging dependencies in place, we should review when, what and at which level logging occurs within JADNC.

Official guidance on logging levels: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-level

I'm thinking of:
- Do not log events at **error** level which cannot be solved by us, but are functional errors that do not require investigation. Like resource-not-found, invalid-attribute-name, resource-already-exists, input validation errors etc.
- Basic trace/debug logging of JSON request/response, along with qualified URL
- Log query string parsing results, maybe

Additions are welcome!

**Comment by maurei** [comment]
It might be a good idea to check out another big framework and see how they approached this. But indeed, there is a lot of room for improvement here!

**Comment by bart-degreed** [comment]
Sure. Do you have any in mind?
