### ISSUE TITLE
Restore SourceLink support

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#692]
It was introduced in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/325, but then removed in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/619 for reasons unknown to me.

https://github.com/dotnet/sourcelink/blob/master/docs/README.md

**Comment by maurei** [comment]
It [was removed](https://github.com/dotnet/sourcelink/issues/178) because it made development with Visual Studio Mac impossible [see this issue](https://github.com/dotnet/sourcelink/issues/178). Looks like the issue has been resolved and we should be able to pull it back
