### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#715]
## Description
I would like to give the integration tests in this project a big overhaul. Things I would like to address:
- [x] Use [WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1) instead of TestServer
- [x] Update Startup/Program from IWebHostBuilder to IHostBuilder
- [x] Use a centralized set of typed deterministic (based on test name) Fakers and reuse them
- [x] Use [FluentAssertions](https://fluentassertions.com/introduction) for more readable tests and better failure messages
- [x] Create a shared project with common building blocks, like executing a request, replacing an injected service etc.
- [x] Have unit tests that assert exact json-text output (guards against breaking changes)

I'm also thinking about running tests in parallel.
- [x] Each test class has its own database and factory, so classes can run in parallel
- [x] Within a test class, use a unique database name (guid appended) and server instance, then run its containing test methods sequentially on that

**Comment by maurei** [comment]
I've never gotten to doing a serious clean up of the test projects, this is highly wanted.

> Each test class has its own database and factory, so classes can run in parallel
I think it is good to use actual db for tests rather than an in memory ones to include things like FK violations. But this might get a little complicated when running tests in parallel.
