### ISSUE TITLE
Create (POST) does not return entity including changed values from trigger

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#724]
This only works correctly when the POST request has an 'includes' query string parameter.

**Comment by maurei** [comment]
Could you elaborate with a little example?

**Comment by bart-degreed** [comment]
You create a resource, which has a CreationTime column that is auto-filled from a database trigger with the current time. So after create, a re-fetch is needed to observe the change. The relationship part, I don't remember which test covers that, but the code used to be to re-fetch only when the request also contains a relationship (in DefaultService or DefaultRepo).
