### ISSUE TITLE
Feature Request: Use C# Source Generators to reduce boilerplate controllers

### ISSUE THREAD

**Issue by jeff-becker-projekt202** [json-api-dotnet/JsonApiDotNetCore#732]
## Description
One of my current annoyances is )that I have a lot of boilerplate controllers. This could be addressed with a [Source Generator](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) which inspects a data context and emits controllers for the configured resources.

I'll implement & PR this, I'd just like feedback on what it needs to look like.
...

## Environment

- JsonApiDotNetCore Version: 4.x
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
This sounds interesting. I'm wondering how you would know which controllers to generate, based on the syntax trees that represent the project source code. In the past, all resources had to be exposed as DbSet properties on DbContext, but we've recently switched to using EF Core's DbContext.Model instead, which is populated at application runtime.

**Comment by jeff-becker-projekt202** [comment]
So my thinking was to determine the set of resources based on classes marked with the resource attribute. Then only emit controllers for those if there is not already a controller defined for that resource.

**Comment by bart-degreed** [comment]
I think that could work. `ResourceAttribute` currently requires to specify a resource name. but we can make that optional.

**Comment by wayne-o** [comment]
Does this need to be actual real code generated - could the framework
CreateInstance of the type if it senses there isn't one? Kind of like what
ember does.

**Comment by bart-degreed** [comment]
Probably that is possible too, according to https://stackoverflow.com/questions/848904/in-asp-net-mvc-is-it-possible-to-make-a-generic-controller.

**Comment by KirovAir** [comment]
It should be fairly easily doable.
https://www.strathweb.com/2018/04/generic-and-dynamically-generated-controllers-in-asp-net-core-mvc/

**Comment by jeff-becker-projekt202** [comment]
@wayne-o @KirovAir  just to be clear, this is proposing using the new [Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) feature in the C# compiler.  Source Generators are a hook into the compiler pipeline that allows you to generate the code during the compile without having to write it out to disk. They're a much more powerful form of code generation in that they have access to the compilation pipeline as well as all the traditional types of code generation sources. The thought here was that I could write a source generator that inspects the code-base for classes tagged with the ResourceAttribute and if no corresponding controller class is found, emit a boilerplate controller. This would prevent having to implement complicated generic / inheritance / DI based strategies which would make the controller interfaces more complicated than they already are.
