### ISSUE TITLE
Strange behaviour on DefaultPageSize

### ISSUE THREAD

**Issue by YaLehin** [json-api-dotnet/JsonApiDotNetCore#735]
## Description
Hi,
Exploring the new version I understood that at the commit https://github.com/json-api-dotnet/JsonApiDotNetCore/commit/36979679fc50edecef3889c68bcf7edb6e025b17 you have changed the DefaultPageSize to 10 from 0. But it influences not only on paged request results but also for all types of request result (e.g. /items) Is this normal behaviour?
The version of JADNC is latest (alpha 5).
Thanks.
...

**Comment by bart-degreed** [comment]
Yes, this is a breaking change. Paging is now enabled by default. Set options.DefaultPageSize to 0 in Startup for the old behavior.

**Comment by YaLehin** [comment]
Thanks for clarification
