### ISSUE TITLE
Question: GetDefaultSortOrder not firing

### ISSUE THREAD

**Issue by fdlane** [json-api-dotnet/JsonApiDotNetCore#736]
## Description
In my `ResourceDefinition` I have two overrides, one for `GetQueryFilters` and one for `GetDefaultSortOrder`.  For some reason, only the `GetQueryFilter` override fires.

My Postman request does not include any sort params. 

Any ideas what I have done wrong here?

...

```C#
  public class ClientResource : ResourceDefinition<Client>
    {
      public ClientResource(IResourceGraph resourceGraph) : base(resourceGraph) { }
      public override PropertySortOrder GetDefaultSortOrder() => new PropertySortOrder
      {
        (t => t.DisplayName, SortDirection.Ascending)
      };
      public override QueryFilters GetQueryFilters() => new QueryFilters
      {
        {
        "search",
        (items, filter) => items.Where(i => i.DisplayName.Contains(filter.Value))
        }
      };
    }
```
## Environment

- JsonApiDotNetCore Version:  v4.0.0-alpha5
- Other Relevant Package Versions: core 3.1

**Comment by bart-degreed** [comment]
Hi @fdlane, thanks for asking. I don't think you did anything wrong, this looks like a bug. 

The `_queries` field in [SortService](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/237dbba50dcd3633d28fc9fe5af5013ddea0df93/src/JsonApiDotNetCore/QueryParameterServices/SortService.cs) is initialized with an empty list [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/237dbba50dcd3633d28fc9fe5af5013ddea0df93/src/JsonApiDotNetCore/QueryParameterServices/SortService.cs#L26), so the null check [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/237dbba50dcd3633d28fc9fe5af5013ddea0df93/src/JsonApiDotNetCore/QueryParameterServices/SortService.cs#L32) never succeeds, resulting in the `if` statement never being entered and thus the callback never getting fired.

**Comment by fdlane** [comment]
Thanks for the fast response.

Change to...? 

```c#
     if (_queries == null ||  _queries.Count == 0)
```

**Comment by bart-degreed** [comment]
I would only check for empty, because the field can never be null.

**Comment by bart-degreed** [comment]
But we should have a test that covers this, too.
