### ISSUE TITLE
Bug: sorting on multiple fields does not work

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#745]
A query like /api/articles?sort=authorName,-pageCount should sort on author, and within that subset sort in pageCount in descending order.

QueryableExtensions contains two methods:
```csharp
public static IOrderedQueryable<TSource> Sort<TSource>(this IQueryable<TSource> source, SortQueryContext sortQuery) { ... }

public static IOrderedQueryable<TSource> Sort<TSource>(this IOrderedQueryable<TSource> source, SortQueryContext sortQuery) { }
```

But the second one (building query based upon a parent ordering) is never called.

**Comment by fdlane** [comment]
Also use cases with multiple sorts on the same entity like ` /api/user?sort=-lastLoginTime, username`  no longer sort.

**Comment by bart-degreed** [comment]
How is that use case different from the problem stated?

**Comment by fdlane** [comment]
It may not be...Just wanted to point out that if there were no related entities involved, the multiple sort does not work either.  

From your example, if you specify sort by `title` and `pageCount`, no sorting occurs.  Note, author is not part of this sort.  This may be a distinction without a difference. :)

**Comment by bart-degreed** [comment]
Ah, I understand now. My example could have been clearer. with 'author' I meant a single string attribute containing the author name, not a relationship. I don't think specifying a relationship in sort is possible -- at least, I would not know what sort=author means when author is a relationship, because it does not indicate on which author attribute to sort.

**Comment by fdlane** [comment]
@bart-degreed thank you for your patience.

**Comment by bart-degreed** [comment]
No problem :)
