### ISSUE TITLE
Does JADNC allow custom api controllers name to be inherited from JSONAPIController

### ISSUE THREAD

**Issue by c2develop** [json-api-dotnet/JsonApiDotNetCore#756]
## Description
Do i always need to have a controller implementation to inherit from JsonAPIController<model>
public class {ControllerName}Controller: BaseJsonApiController<>
or
could i have something like this to be inherited JsonAPIController<>
public class api:jsonapicontroller<model>
??
...

## Environment
.Core 2.2
- JsonApiDotNetCore Version: 3.1.0
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
Yes, for each resource you need to create a controller class that derives from JsonApiController.

**Comment by bart-degreed** [comment]
I hope this answers your question. Feel free to reopen or create a new issue if something else comes up.
