### ISSUE TITLE
Response content with 204 response code

### ISSUE THREAD

**Issue by YaLehin** [json-api-dotnet/JsonApiDotNetCore#760]
## Description
As I could understand from the code the JsonApiWriter tries to write a response content to the response with StatusCode 204, that causes the exception:
```
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
  at at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowWritingToResponseBodyNotSupported() 
```

**Comment by bart-degreed** [comment]
Thanks for reporting. Can you provide some more details? What does your
request look like (verb, url, body) and which version are you using?

**Comment by YaLehin** [comment]
I use the alpha5 version of JADNC. This occurs when on delete request. The request like this `(Method=DELETE) http://localhost:5000/api/v1/item/3`
After successful deletion, the response is forming with a status code of 204 and at JsonApiWriter.cs is an attempt to write response content
`{"links":{"self":"http://localhost:5000/api/v1/item/3"},"data":null}`
This leads to that exception.
I found this exception only running under the debugger. No crashes at normal running.
Maybe it is a planned situation, I am quite new to JADNC and all dot net ecosystem and trying to get acquainted with it.

**Comment by bart-degreed** [comment]
Hi @YaLehin, thanks for the details. I can see this exception in the Kestrel console. Can you test if my PR fixes this for you?

**Comment by YaLehin** [comment]
Thank you, I'll test and will report here the result.

**Comment by YaLehin** [comment]
Hi @bart-degreed,
I have tested your PR. All works fine, there is no exception now. Thank you.
