### ISSUE TITLE
Namespace not honored when RelativeLinks=true

### ISSUE THREAD

**Issue by fdlane** [json-api-dotnet/JsonApiDotNetCore#763]
## Description

In the GettingStarted App if you set `RelativeLinks = true;`  the links in response do not include the namespace. Should it not return `"self": "api/people"`?

```c#
services.AddJsonApi<SampleDbContext>(options =>
    {
        options.Namespace = "api";
        options.RelativeLinks = true;
     });
```

```json

{
    "links": {
        "self": "/people"
    },
    "data": [
        {
            "type": "people",
            "id": "1",
            "attributes": {
                "name": "John Doe"
            },
            "relationships": {
                "articles": {
                    "links": {
                        "self": "/people/1/relationships/articles",
                        "related": "/people/1/articles"
...
```
...

## Environment

- JsonApiDotNetCore Version: master
- Other Relevant Package Versions: core 3.1

**Comment by fdlane** [comment]
Is this correct? 

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/ac5b100b37246d7c8f1f24d1d9b0da79543c32d6/src/JsonApiDotNetCore/Serialization/Server/Builders/LinkBuilder.cs#L227

**Comment by bart-degreed** [comment]
You are right that the current behavior is wrong. I'm just wondering if it
should be /api/people.

Op za 16 mei 2020 00:27 schreef F. DeWayne Lane <notifications@github.com>:

**Comment by bart-degreed** [comment]
LinkBuilder is the place to fix this, but there's also some path parsing in JsonApiMiddleware you may want to verify.

**Comment by bart-degreed** [comment]
@fdlane Do you wanna take this one?

**Comment by fdlane** [comment]
@bart-degreed will do
