### ISSUE TITLE
Multiple published versions of documentation

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#768]
> F. DeWayne Lane @fdlane May 15 19:58
> What is the vision for documentation? I noticed that different instances are available at both
> https://json-api-dotnet.github.io/#/ and https://json-api-dotnet.github.io/JsonApiDotNetCore/
>
> PR to removed links to https://json-api-dotnet.github.io/#/ ?

We should consolidate the two versions.

/cc @fdlane

**Comment by bart-degreed** [comment]
@maurei @wisepotato do you know anything about this?

**Comment by bart-degreed** [comment]
Based on https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7, I think this can only be fixed by making changes in the https://github.com/json-api-dotnet/json-api-dotnet.github.io repository.

**Comment by wisepotato** [comment]
the latter one is newer is all i know

**Comment by bart-degreed** [comment]
Looked into this a while ago. Turns out that the root documentation was created from the json-api-dotnet GitHub container, while the nested (and most-recent) one is coming from json-api-dotnet/JsonApiDotNetCore GitHub project.

@maurei It looks like you have permissions on the GitHub container. Can you look into replacing the existing docs there with a simple redirect to https://json-api-dotnet.github.io/JsonApiDotNetCore/?

**Comment by maurei** [comment]
I don't have write permissions to the docs repository. I reached out to Jared about this.

**Comment by maurei** [comment]
Solved in https://github.com/json-api-dotnet/json-api-dotnet.github.io/commit/0aba4ae41223a5bccc7c1d32d0acee1962abd3f0
