### ISSUE TITLE
AddClientSerialization should register (de)serializers as scoped services

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#783]
## Description
the `AddClientSerialization` extension on `IServiceCollection` registers client-side (de)serializers as singleton services, but `ResponseDeserializer` depends on `IResourceFactory` which is a scoped service, i.e. ResponseDeserializer should be registered as a scoped service too.

## Environment
- JsonApiDotNetCore Version: master

**Comment by bart-degreed** [comment]
Alternatively, we can register `IResourceFactory` as a singleton as well.
