### ISSUE TITLE
Hard-coded convention

### ISSUE THREAD

**Issue by mkoppanen** [json-api-dotnet/JsonApiDotNetCore#787]
## Description

The API has hardcoded convention at places and it would be nice to change this by simply providing a ConventionProvider or similar. An example is: 

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Serialization/Server/Builders/MetaBuilder.cs#L46

Where "total-records" is hardcoded. One could provide different implementation of IMetaBuilder but it seems like an overkill when doing such simple changes.

...

## Environment

- JsonApiDotNetCore Version: all
- Other Relevant Package Versions: none

**Comment by bart-degreed** [comment]
Hi @mkoppanen, thanks for reporting this. I recently found this one too. The fix is easy, I'll add it to the changes I'm currently working on and link to here once I have a PR.

Any other places where you've seen that casing conventions are not respected?

**Comment by mkoppanen** [comment]
Haven't seen other ones. I think another similar thing I ran into was using "id" as hardcoded route parameter for patch requests. I sometimes see cases where API has "one of" something /api/users/{userId}/profile and thus natural patch endpoint would be PATCH /api/users/{userId}/profile. If one has other things tied into {userId} being the route it would be nice to have attribute to override "BaseId" per controller or per endpoint.

**Comment by bart-degreed** [comment]
I'm afraid I don't understand what you mean by that. If this "id' thing is unrelated to casing convention, can you please open a new issue for it and provide an example to clarify the problem?

**Comment by mkoppanen** [comment]
Sure thing and it was unrelated to the original. Thanks for quick replies!
