### ISSUE TITLE
[Question] How to force an Include in a Controller

### ISSUE THREAD

**Issue by fdlane** [json-api-dotnet/JsonApiDotNetCore#804]
## Description

I have an action route on a controller and I would like to force a related entity to always be included when `GetAsync()` is called.

I know that I can add a query string parm, `include=client`, but since this action method will always need the client, I do not want to require the user to add the param.

```C#
        //how to include the client on the invoice without requiring the user to add the query string param?
        var invoice = await _resourceService.GetAsync(invoiceId)
```

## Environment

- JsonApiDotNetCore Version: v4.0.0-alpha5
- Other Relevant Package Versions:

**Comment by wisepotato** [comment]
You'll have to make a seperate controller as this is not within json;api spec afaik

**Comment by bart-degreed** [comment]
Override OnApplyIncludes in an Invoice resource definition and add your include there. See doc-comments on the resource definition method in the base class for details.

**Comment by fdlane** [comment]
Thanks for the quick response.
