### ISSUE TITLE
Allow custom filter operators

### ISSUE THREAD

**Issue by bjornharrtell** [json-api-dotnet/JsonApiDotNetCore#810]
If one implements the service layer with custom code and want to use a method of filtering that is beyond the ones supported by the current QueryLayer it would be nice to at least be able to get it as a CustomExpression with just the plain unprocessed strings as Operator and Arguments properties.

**Comment by bart-degreed** [comment]
What is the use case you're trying to solve?

**Comment by bjornharrtell** [comment]
It would allow implementing custom filtering fx spatial filters (but would probably be better if implemented by https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/809) but perhaps also filtering for less common types fx. PostgreSQL jsonb queries.

**Comment by bart-degreed** [comment]
I've striven to make the querying subsystem pluggable (unsealed classes, injectable dependencies, virtual methods), so it should be possible to implement those outside the JADNC source code. If you need more parts to be opened up for extensibility, I'm willing to consider that.

How CustomExpression (which contains just anything you like) would be validated, resolved and translated into a LINQ expression tree is unclear to me, but I can see how anyone would add additional typed expressions for specific spatial clauses and provide LINQ translations for them.

**Comment by bjornharrtell** [comment]
I agree it's probably better to approach this by enabling injecting additional typed expressions. I'll try to rework my PR allow that (I don't think the current code base does..).

**Comment by bart-degreed** [comment]
@bjornharrtell as there is a separate open issue for spatial types, is there any reason to keep this one open too?

**Comment by bjornharrtell** [comment]
@bart-degreed I think it still make sense to be able to implement custom filters (other than spatial), but I'm not sure when/if i can get time to investigate it at this time.

**Comment by bart-degreed** [comment]
Implementing your own filters is something you can already do today, like I mentioned. That requires no changes in JADNC, as the system is pluggable. Therefore I think its best to open specific issues if you run into trouble while trying to do that. The current issue is not actionable for me, therefore I'd like to close it.

**Comment by bjornharrtell** [comment]
@bart-degreed that's fine, if I get the chance to try out actually doing a custom filter and have problems with that I'll open a new issue.
