### ISSUE TITLE
id vs string-id when a resource is nested as a complex type in another resource

### ISSUE THREAD

**Issue by c2develop** [json-api-dotnet/JsonApiDotNetCore#812]
## Description

Iam using a Resource<identifiable,string> A as an attribtute on another resource B  as a complex type.
and the response has the string-id introduced for resource A
Can we get the string-id to be taken off from the response ??
current response: string-id along with the id response
id: 'abcd_12345'
string-id: 'abcd-12345'
...

## Environment

- JsonApiDotNetCore Version: 3
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
If I understand correctly, you should be able to do that by overriding the virtual `Id` property on A and putting [JsonIgnore] on it. Otherwise please share your resource classes A and B here to clarify.

**Comment by c2develop** [comment]
Implemented overriding the virtual Id property on A and putting [JsonIgnore] on it also did implement Jsonproperty defaultvalues ingoring on it and it worked.
