### ISSUE TITLE
Fluent API for resources' configuration

### ISSUE THREAD

**Issue by poneymusical** [json-api-dotnet/JsonApiDotNetCore#849]
I haven't seen this in the docs nor the open issues.

## Description
It would be great to have the possibility to use a fluent API instead of attributes for the resources' configuration, a bit like the fluent API in EF core. Some of us like to keep their entities devoid of any attributes, and overriding the properties just to add attributes seems kind of hacky. 

One could imagine having an interface like `IResourceConfiguration<TResource>` or `IResourceConfiguation<TResource, TId>` that could be implemented for each resource, very much like `IEntityTypeConfiguration<TEntity>` in EF Core.

I have no clear idea on how to implement this, as I've only discovered this lib, but it's been great so far and I think it would be a valuable addition.

Thanks in advance for your feedback!

**Comment by poneymusical** [comment]
Sorry, just found out there's another issue covering this

**Comment by alastairtree** [comment]
Over at #776 in case others are looking for it
