### ISSUE TITLE
Question: Why Does BeforeUpdate Hook cant Persist LastModified  attribute changes to DB?

### ISSUE THREAD

**Issue by simsadrowpsx** [json-api-dotnet/JsonApiDotNetCore#855]
## Description
So i am trying to add a `lastModifiedOn` DateTime Attribute to Article Model,
Currently i have implemented the below BeforeUpdate Hook
```c#
public override IEnumerable<Article> BeforeUpdate(IDiffableResourceHashSet<Article> resources, ResourcePipeline pipeline)
{
   foreach (Article element in resources)
  {
         element.lastModifiedOn=DateTime.UtcNow;
  }        
return base.BeforeUpdate(resources, pipeline);
}
```
However when i fetch again the `lastModifiedOn` attribute is still null,
is this the intended behavior?, or can hooks in this way?

If so how can i implement such an attribute??

## Environment
- JsonApiDotNetCore Version: master branch as of 7th October 2020

**Comment by maurei** [comment]
Is your `LastModifiedOn` property annotated with `AttrAttribute`? If so, it should be enough to add it to the `ITargetedFields.Attributes` collection. This service keeps track of which attributes are targeted by the request, so that the data layer will know which properties to update.

```c#
public class ArticeHooks : ResourceHooksDefinition<Article>
{
    private readonly ITargetedFields _targetedFields;
    public ArticeHooks(IResourceGraph resourceGraph, ITargetedFields targetedFields) : base(resourceGraph)
    {
        _targetedFields = targetedFields ?? throw new ArgumentNullException(nameof(targetedFields));
    }

    public override IEnumerable<Article> BeforeUpdate(IDiffableResourceHashSet<Article> resources, ResourcePipeline pipeline)
    {
        var lastModifiedOnAttr = ResourceGraph.GetAttributes<Article>(a => new {a.LastModifiedOn}).Single();
        _targetedFields.Attributes.Add(lastModifiedOnAttr);
        
        foreach (var resource in resources)
        {
            resource.LastModifiedOn = DateTime.Now;
        }
        
        return base.BeforeUpdate(resources, pipeline);
    }
}
```

If you don't want to add `AttrAttribute` there are several other ways you can achieve it. Let me know.

**Comment by simsadrowpsx** [comment]
Yes, this works, thanks @maurei. Greatly appreciate it.

I still have a few  more questions about this library.

One: How to add global meta object?, (I am able to add to individual resources, but not globally)

Two: How to Define the functionality in `JsonApiResourceDefinition?` (if possible)
 - Dynamically set/Change `LinkType` of a resource?
 - Remove/Add model attributes?
 - Remove/Add ?include resources?

From the stuff in Doc i think only the `softDelete` is working , others produces errors or not works at all, what am i doing wrong here?
