### ISSUE TITLE
How to modify SparseFieldSet by overidding SparseFieldSetExpression Method in JsonApiResourceDefinition

### ISSUE THREAD

**Issue by simsadrowpsx** [json-api-dotnet/JsonApiDotNetCore#858]
### How to modify SparseFieldSet by overidding SparseFieldSetExpression Method in JsonApiResourceDefinition

```c#
public override SparseFieldSetExpression OnApplySparseFieldSet(SparseFieldSetExpression existingSparseFieldSet)
{
    // Add/Remove Attributes Here??? 
    return existingSparseFieldSet;
}
```

**Comment by bart-degreed** [comment]
This is documented at https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resources/resource-definitions.html, for details see https://json-api-dotnet.github.io/JsonApiDotNetCore/api/JsonApiDotNetCore.Resources.IResourceDefinition-2.html#JsonApiDotNetCore_Resources_IResourceDefinition_2_OnApplySparseFieldSet_JsonApiDotNetCore_Queries_Expressions_SparseFieldSetExpression_.

The examples and tests in the repo solution also show how this can be used.

**Comment by simsadrowpsx** [comment]
Yh, tried that but i get the following

Error : CS7036	There is no argument given that corresponds to the required formal parameter 'resourceGraph' of 'SparseFieldSetExpressionExtensions.Excluding<TResource>(SparseFieldSetExpression, Expression<Func<TResource, dynamic>>, IResourceGraph)'

**Comment by bart-degreed** [comment]
You need to pass the `IResourceGraph`, obtained via dependency injection in constructor. The examples show this. I'd recommend you start from a working example, then adapt to what you're trying to accomplish step-by-step.

**Comment by simsadrowpsx** [comment]
Hey @bart-degreed ,
i looked into the doc before asking here, but code in doc was giving me the error mentioned before,

**Comment by simsadrowpsx** [comment]
Finally figured it, may not be ideal/as intended but works , thanks @bart-degreed 
```c#
public override SparseFieldSetExpression OnApplySparseFieldSet(SparseFieldSetExpression existingSparseFieldSet)
{
    // Get the User Resource Context
    var attributes = _resourceGraph.GetResourceContext<User>().Attributes;

    // Filter the Attributes
    var scopedAttributes = (IReadOnlyCollection<AttrAttribute>) 
        attributes.Where ( a => a.Property.Name != nameof(Note.IsDeleted) ).ToList();

    // set new SparseFieldSetExpression
    existingSparseFieldSet = new SparseFieldSetExpression(scopedAttributes);

    return existingSparseFieldSet;
}
```

**Comment by bart-degreed** [comment]
Looks wrong to me. You're ignoring any incoming `?fields=` from the query string, always selecting all fields except IsDeleted. The extension methods take an existing set into account.

**Comment by simsadrowpsx** [comment]
Yh, i have considered that, but not shown here

**Comment by bart-degreed** [comment]
You were right that documentation was outdated. I've merged a commit to fix that. Should be visible in a few minutes.
