### ISSUE TITLE
why we are providing {id}/relationships/{relationshipName} and using PostRelationshipAsync() instead of PostRelationshipsAsync() 

### ISSUE THREAD

**Issue by macmanishkr20** [json-api-dotnet/JsonApiDotNetCore#863]
## Description

```
.../// <inheritdoc />
        [HttpPost("{id}/relationships/{relationshipName}")]
        public override async Task<IActionResult> PostRelationshipAsync(
            TId id, string relationshipName, [FromBody] IReadOnlyCollection<IIdentifiable> secondaryResourceIds)
            => await base.PostRelationshipAsync(id, relationshipName, secondaryResourceIds);
```

why we are providing `{id}/relationships/{relationshipName}` and using `PostRelationshipAsync()` instead of `PostRelationshipsAsync()` ?

## Environment

- JsonApiDotNetCore Version: 4 feature branch post-relationship
- Other Relevant Package Versions:

**Comment by macmanishkr20** [comment]
why we are providing" {id}/relationships/{relationshipName} "and using PostRelationshipAsync() instead of PostRelationshipsAsync() ?

**Comment by bart-degreed** [comment]
Hi @macmanishkr20,

To answer you question: Because that endpoint targets a single ToMany relationship. Similar to how /users/1 targets a single user. A relationship consists of a left and right side, both of which can be a single element or a collection of elements.

Hope that answers your question.

**Comment by macmanishkr20** [comment]
Thanks for reply @bart-degreed 

If that is the case then URL should be like {id}/{relationshipname}. For Example: articles/1/comments

**Comment by bart-degreed** [comment]
articles/1/comments targets a list of comment resources, articles/1/relationships/comments targets the relationship itself. See the json:api spec for details.

**Comment by maurei** [comment]
Another way to consider it is that the controller names are of the following format:  `{HttpVerb}{EndpointKind}Async`. Here, `EndpointKind` can be [Primary, Secondary or Relationship](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Middleware/EndpointKind.cs). In the case of `Primary` we're leaving it out for brevity. We could consider adding it for consistency.

**Comment by bart-degreed** [comment]
Closing, as the question has been answered.
