### ISSUE TITLE
Read request Header Values from JsonApiResourceDefinition

### ISSUE THREAD

**Issue by simsadrowpsx** [json-api-dotnet/JsonApiDotNetCore#866]
## Description
So I am trying to manipulate JsonApiResourceDefinition's Expression depending on a header value in the request Header For AuthZ purposes.
Is there a way to read request Header values from resource definitions.
Or what is the recommended way of doing this?

**Comment by bart-degreed** [comment]
I would inject HttpContextAccessor.

**Comment by mdhthahmd** [comment]
Thank you @bart-degreed

**Comment by bart-degreed** [comment]
Closing this as answered.
