### ISSUE TITLE
POST/PATCH Resource with Relationship

### ISSUE THREAD

**Issue by lrfahmi** [json-api-dotnet/JsonApiDotNetCore#871]
## Description
I wasn't sure before that whether the json: api spec supports POST/PATCH with single-request relationships. I intend to add resources, they are called Master-Detail.

### Configuration
```csharp
services.AddDbContext<FabrikamContext>(options =>
{
	options.UseSqlServer("Data Source=localhost;User ID=sa;Password=password;Initial Catalog=master");
});

services.AddJsonApi<FabrikamContext>(options =>
{
	options.AllowClientGeneratedIds = true;
}, discovery =>
{
	discovery.AddCurrentAssembly();
});
```
### Models
For this case, I tried based on the model below:
```csharp
[Table("Department")]
public class Department : Identifiable<string>
{
	[Key]
	[Column("DepartmentId")]
	public override string Id { get; set; }

	[Attr]
	public string Name { get; set; } = "";

	[Attr]
	public string Description { get; set; } = "";

	[HasMany]
	public ICollection<Category> Categories { get; set; }
}

[Table("Category")]
public class Category : Identifiable<string>
{
	[Key]
	[Column("CategoryId")]
	public override string Id { get; set; }

	[Attr]
	public string Name { get; set; } = "";

	[Attr]
	public string Description { get; set; } = "";

	[HasOne(IdentifiablePropertyName = "DepartmentId")]
	public Department Department { get; set; }
	public string DepartmentId { get; set; }
}
```
> These `category resource` require a `DepartmentId` before being added.

### Questions
What is the mechanism for POST/PATCH `Department` resources and `categories` in a single request?

#### Method 1 (It looks like JSON: the API can't handle this / I was wrong in spec, sorry)
I sent a post request to add `Department` along with a new `Categories`.
```
POST /departments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type": "departments",
        "id": "10",
        "attributes": {
            "name": "Department 10",
            "description": ""
        },
        "relationships": {
            "categories": [
                {
                    "data": {
                        "type": "categories",
                        "id": "10-1",
                        "attributes": {
                            "name": "Category 1 at Department 10",
                            "description": "This category is child of Department 10."
                        }
                    }
                }
            ]
        }
    }
}
```
```
{
    "errors": [
        {
            "id": "19d07b38-5193-4219-9a76-c0ca65d0c755",
            "status": "422",
            "title": "Failed to deserialize request body.",
            "detail": "Error setting value to 'Data' on 'JsonApiDotNetCore.Serialization.Objects.Document'. - Request body: <<{\r\n    \"data\": {\r\n        \"type\": \"departments\",\r\n        \"id\": \"10\",\r\n        \"attributes\": {\r\n            \"name\": \"Department 10\",\r\n            \"description\": \"\"\r\n        },\r\n        \"relationships\": {\r\n            \"categories\": [\r\n                {\r\n                    \"data\": {\r\n                        \"type\": \"categories\",\r\n                        \"id\": \"10-1\",\r\n                        \"attributes\": {\r\n                            \"name\": \"Category 1 at Department 10\",\r\n                            \"description\": \"This category is child of Department 10.\"\r\n                        }\r\n                    }\r\n                }\r\n            ]\r\n        }\r\n    }\r\n}>>"
        }
    ]
}
```

#### Method 2
I sent a post request to add `Department` along with a new `Categories` (`included`).
```
POST /departments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type": "departments",
        "id": "10",
        "attributes": {
            "name": "Department 10",
            "description": ""
        },
        "relationships": {
            "categories": {
                "data": [
                    {
                        "type": "categories",
                        "id": "10-1"
                    }
                ]
            }
        },
        "included": [
            {
                "type": "categories",
                "id": "10-1",
                "attributes": {
                    "name": "Category 1 on Department 10",
                    "description": "This category is child of Department 10."
                }
            }
        ]
    }
}
```
```
{
    "errors": [
        {
            "id": "7cf7d4ed-feee-48cf-87d5-9e5fa9952b93",
            "status": "500",
            "title": "An unhandled error occurred while processing this request.",
            "detail": "Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions."
        }
    ]
}
```
```
fail: JsonApiDotNetCore.Middleware.ExceptionHandler[0]
      Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at void Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(int commandIndex, int expectedRowsAffected, int rowsAffected)
   at async Task<int> Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(int commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at async Task Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at async Task Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
```
## Environment

- JsonApiDotNetCore Version: 4.0.0-beta1

**Comment by bart-degreed** [comment]
> What is the mechanism for POST/PATCH Department resources and categories in a single request?

This is currently not possible unfortunately. The json:api spec does not foresee in such an operation. So you'll need to issue two requests to accomplish that.

 There's an experimental proposal though, called Atomic Operations, that would enable compound requests like that. We intend to implement Atomic Operations in a future version.

**Comment by lrfahmi** [comment]
Thanks for some of your replies. In another case, I have a `Sales` and `SalesItems` table, each `SalesItems` rows requires a `SalesId` before it is added.

Example: There are **15 data sales items** that have been **changed** on the client side. With the current feature version, the client **must send 15 PATCH requests**?

**Comment by lrfahmi** [comment]
Thanks for the information. With this explanation, I can understand.

**Comment by bart-degreed** [comment]
Assuming that both the sales row and the 15 items already exist in the database, you can connect them (establish the relationship) in a single call. There's two ways to do that.

1. PATCH on /sales/1, which enables to update attributes and relationships in a single call.
2. PATCH on /sales/1/relationships/items, which affects only the items relationship.

Both calls replace the whole one-to-many relationship. This means when trying to connect 15 items but before the call 5 other items were already connected, the existing items will be disconnected.

We are implementing support for POST /sales/1/relationships/items, which adds only the new items without disconnecting existing ones in #851.

**Comment by lrfahmi** [comment]
Is it not possible to change the attribute value of the relation, like the statement below?
```
{
    "data": {
        "type": "accounts",
        "id": "1-11001",
        "attributes": {
            "name": "Cash 1 (edited)",
            "description": ""
        },
        "relationships": {
            "balances": {
                "data": [
                    {
                        "type": "accountBalances",
                        "id": 1
                    }
                ]
            }
        }
    },
    "included": [
        {
            "type": "accountBalances",
            "id": "1",
            "attributes": {
                "amount": 20000
            }
        }
    ]
}
```

**Comment by lrfahmi** [comment]
> Assuming that both the sales row and the 15 items already exist in the database, you can connect them (establish the relationship) in a single call. There's two ways to do that.

Instead, I am confused, how best way to add `salesItem`, while `salesItem` rows requires `SalesId` first.

**Comment by bart-degreed** [comment]
First of all, urls like /accounts/balances violate the json:api spec. This library tries to make it easy to build spec-compliant apis. If that is not your goal, you're probably better off not using it, as you'll run into all kinds of issues while trying to 'break' things. I recommend you study the json:api spec very closely first, to determine if it fits your needs.

Atomic Operations is described at https://jsonapi.org/ext/atomic/.

I was just making an assumption to explain how connecting multiple resources in a relationship could be done in a single call. If I misunderstood your use case, then ignore it. To clarify: `included` cannot be used in client request bodies.

I understand you have all kinds of questions, but I think [this](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/872#issuecomment-720109901) applies here too.

**Comment by lrfahmi** [comment]
Thank you for the advice. My question is solved with your help as well as the article from https://discuss.jsonapi.org/t/create-update-relationships-with-attributes/1701. Once again, thank you for the advice.
