### ISSUE TITLE
Building Dynamic SparseFieldSetExpression at runtime

### ISSUE THREAD

**Issue by simsadrowpsx** [json-api-dotnet/JsonApiDotNetCore#872]
## Description
I am trying to dynamically set which attributes are returned for a resource, i have a string passed to `SparseFieldSetExpression` method that has attributes comma separated
```c#
string attr = "firstname,lastname"
```
for a User model, while the complete model is something like
```c#
public class User : Identifiable
{
        [Attr]
        public string FirstName { get; set; }

        [Attr]
        public string LastName { get; set; }

        [Attr]
        public string Address { get; set; }
}
```
My question is how can i dynamically build the SparseFieldSetExpression to have only the fields passed in the comma separated string

**Comment by bart-degreed** [comment]
This is certainly possible. But the thing is, our time is limited and we don't have the luxury to be able to guide you and others step-by-step in how to build the features your api needs. So please stop creating issues for questions on how to accomplish something.

On the other hand, if you're confident (after reading the json:api spec and our documentation) that our library misbehaves, then please do create an issue so we can investigate.

The good news is that we provide working examples of various features in the JsonApiDotNetCoreExample project within this repro, including automated tests on how to use various features. There's a wealth of information in there. So I would recommend you browse through them and run them locally. From there, you can adapt and experiment to achieve your goals.

**Comment by simsadrowpsx** [comment]
Yes, it is indeed possible, I have just implemented it in ResourceDefintion Class. My Role-based-Access-Control Module is almost done

Apologies for asking for help here, I know this is an open source project and this is not the intended use for gh issues, and your help so far is not expected of you , but rather voluntary and I am so very grateful for the help. couldn't have done it without it
