### ISSUE TITLE
Custom sort with value?

### ISSUE THREAD

**Issue by RKennedy9064** [json-api-dotnet/JsonApiDotNetCore#901]
#### DESCRIPTION

I'm looking to implement a custom sort that accepts a value, similar to `GET /api/blogs?sort=count(articles) HTTP/1.1` like in the sorting example, but not sure I'm looking in the right place. Where would be a good place to look to implement something like this. I see examples with custom filtering, but I don't see an example of a custom sort that accepts a parameter. Essentially I'm hoping to add a sort by distance feature that allows me to execute my code in Sql Server. Something like this:

```http
// Distance parameters would be lat/long
GET /api/cities?sort=distance(27.0, -92.0)
```
```
// Somewhere in a ResourceDefinition, or Controller, or somewhere else?
var point = new Point(lat, long);
var results = queryable.OrderBy(m => m.Location.Distance(point));
```

Is there an exposed hook, or good place for me to look to get started on something like this?

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.0-rc
- ASP.NET Core version: 3.1
- Entity Framework Core version: 5.0
- Database provider: Sql Server

**Comment by bart-degreed** [comment]
There's basically two ways to approach this: a generic solution and an endpoint-specific solution. The former is complex and involves a lot of work:
1. Think about what the EF Core LINQ query would look like
2. Write code to generate such an expression tree at runtime
3. Extend QueryExpression class hierarchy to feed the required parameters
4. Come up with universal query string syntax and update parsers
5. Add type checks to the parsers to ensure the column type is compatible
6. Write lots of automated tests
7. Now that you're into internals this deep, it would be good to consider what other gis features are worth adding

The latter (and easier) approach would be to implement `IResourceDefinition.OnRegisterQueryableHandlersForQueryStringParameters`. Using that you can bind a custom query string parameter to an `IQueryable<T>` to extend the EF Core query with custom sort. Example: `/stores?sort-by-location=27.0,-92.0`

**Comment by RKennedy9064** [comment]
Thanks for the quick response. I'm working on setting up a really basic version and have a question about the sort functionality. Right now I have a query parameter that looks like this.
```http
http://localhost:5000/api/v1/Cities?fields=name&distance=41.881832,-87.62317
```

I set up a handler for the query string that looks like this.
```csharp
public override QueryStringParameterHandlers<City> OnRegisterQueryableHandlersForQueryStringParameters()
{
    return new QueryStringParameterHandlers<City>
    {
        ["distance"] = (source, parameterValue) =>
        {
            var point = CreatePoint(parameterValue);
            return source.Where(c => c.Location.IsWithinDistance(point, _fiftyMilesInMeters)).OrderBy(c => c.Location.Distance(point));
        }
    };
}
```

When doing testing, it seems like the order by gets overridden by the `Id` column even though I'm not specifying it. Do I need to override anything else, or do something special for it not remove the order by distance? I haven't looked into how entity framework compiles it's query expressions, so I'm not sure why it would remove the distance order by, but keep the Id order by.

```sql
dbug: 12/8/2020 11:54:14.918 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
Compiling query expression:
'DbSet<City>()
    .Where(c => c.Location.IsWithinDistance(
        geom: __point_0,
        distance: 80467.2))
    .OrderBy(c => c.Location.Distance(__point_0))
    .OrderBy(city => city.Id)
    .Select(city => new City{
        Name = city.Name,
        Id = city.Id
    }
)'

dbug: 12/8/2020 11:54:14.931 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query)
Generated query execution expression:
'queryContext => new SingleQueryingEnumerable<City>(
    (RelationalQueryContext)queryContext,
    RelationalCommandCache.SelectExpression(
        Projection Mapping:
            Name -> 0
            Id -> 1
        SELECT c.city AS Name, c.city_id AS Id
        FROM city AS c
        WHERE c.geog.STDistance(@__point_0) <= 80467.199999999997E0
        ORDER BY c.city_id ASC),
    Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, City>,
    Contexts.ApplicationContext,
    False,
    False
)'

SELECT [c].[city] AS [Name], [c].[city_id] AS [Id]
FROM [city] AS [c]
WHERE [c].[geog].STDistance(@__point_0) <= 80467.199999999997E0
ORDER BY [c].[city_id]
```

**Comment by bart-degreed** [comment]
It looks like you did everything right, based on my suggestions. JADNC adds sort by ID if none is provided, to prevent random orderings. It is unaware of your custom sort expression. EF Core probably understands that the sort by ID already makes the rows unique, so it discards any additional sort expressions (yours). The problem stems from [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/7a8d3eb7d554a00d97b8480e254c79a142f8d11c/src/JsonApiDotNetCore/Repositories/EntityFrameworkCoreRepository.cs#L91-L109), where we _first_ append the outcome of `OnRegisterQueryableHandlersForQueryStringParameters` to the EF Core query, before adding the outcome of query string parameters (including default sort if omitted). We do things in this order because usually devs implement `OnRegisterQueryableHandlersForQueryStringParameters` to add extra filter conditions and we don't want them to end up _after_ sorting, projections etc. So my suggested approach does not work in your case.

What you can try instead:
```c#
public class CitiesRepository : EntityFrameworkCoreRepository<City>
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private double _fiftyMilesInMeters = 1.0;

    public CitiesRepository(IHttpContextAccessor httpContextAccessor, ITargetedFields targetedFields,
        IDbContextResolver contextResolver, IResourceGraph resourceGraph, IResourceFactory resourceFactory,
        IEnumerable<IQueryConstraintProvider> constraintProviders, ILoggerFactory loggerFactory)
        : base(targetedFields, contextResolver, resourceGraph, resourceFactory, constraintProviders, loggerFactory)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    protected override IQueryable<City> ApplyQueryLayer(QueryLayer layer)
    {
        var source = base.ApplyQueryLayer(layer);

        var parameterValue = GetDistanceFromQueryString();
        if (parameterValue != null)
        {
            var point = CreatePoint(parameterValue);

            source = source
                .Where(c => c.Location.IsWithinDistance(point, _fiftyMilesInMeters))
                .OrderBy(c => c.Location.Distance(point));
        }

        return source;
    }

    private string GetDistanceFromQueryString()
    {
        string value = _httpContextAccessor.HttpContext.Request.Query["distance"];
        return string.IsNullOrEmpty(value) ? null : value;
    }

    private Point CreatePoint(string parameterValue)
    {
        throw new NotImplementedException();
    }
}
```

Next, you'll need to register the custom repository from `Startup.ConfigureServices` (if you're using auto-discovery, you can skip this step):
```c#
services.AddResourceRepository<CitiesRepository>();
```

The above results in your ordering being added _after_ any existing orderings, which makes the earlier orderings irrelevant. It now depends on how smart EF Core is in eliminating unneeded sorts and reordering the query so that your where clause executes server-side. I hope this helps.

Another solution would be to implement `CitiesRepository.ApplyQueryLayer` like this:
```c#
protected override IQueryable<City> ApplyQueryLayer(QueryLayer layer)
{
    layer.Sort = null;
    return base.ApplyQueryLayer(layer);
}
```

and keep using your resource definition with `OnRegisterQueryableHandlersForQueryStringParameters` override. The code above throws out any sort coming from query string or `IResourceDefinition.OnApplySort`. The downside is you'll get random ordering in case users do not specify your `distance` query string parameter. But you can even work around that by only clearing `layer.Sort` if the query string parameter is provided (using `IHttpContextAccessor` check like above).

**Comment by RKennedy9064** [comment]
I just had some time to test out your newest suggestion and think I got it working, but had some unexpected results along the way. If I use `ApplyQueryLayer` as originally shown, I end up getting an error when it tries to translate the expression.
```csharp
protected override IQueryable<City> ApplyQueryLayer(QueryLayer layer)
{
    var source = base.ApplyQueryLayer(layer);

    var parameterValue = GetDistanceFromQueryString();
    if (parameterValue != null)
    {
        var point = CreatePoint(parameterValue);

        source = source
            .Where(c => c.Location.IsWithinDistance(point, _fiftyMilesInMeters))
            .OrderBy(c => c.Location.Distance(point));
    }

    return source;
}

dbug: 12/9/2020 11:01:04.865 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<City>()
          .OrderBy(city => city.Id)
          .Select(city => new City{
              Name = city.Name,
              Id = city.Id
          }
          )
          .Where(c => c.Location.IsWithinDistance(
              geom: __point_0,
              distance: 80467.2))
          .OrderBy(c => c.Location.Distance(__point_0))'
fail: JsonApiDotNetCore.Middleware.ExceptionHandler[0]
      The LINQ expression 'DbSet<City>()
          .OrderBy(c => c.Id)
          .Where(c => new City{
              Name = c.Name,
              Id = c.Id
          }
          .Location.IsWithinDistance(
              geom: __point_0,
              distance: 80467.2))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
If I use your suggestion of continuing to use `OnRegisterQueryableHandlersForQueryStringParameters` and null out `layer.Sort` it seems to work.
```csharp
protected override IQueryable<City> ApplyQueryLayer(QueryLayer layer)
{
    var parameterValue = GetDistanceFromQueryString();
    if (parameterValue != null)
    {
        layer.Sort = null;
    }

    return base.ApplyQueryLayer(layer);
}

public override QueryStringParameterHandlers<City> OnRegisterQueryableHandlersForQueryStringParameters()
{
    return new QueryStringParameterHandlers<City>
    {
        ["distance"] = (source, parameterValue) =>
        {
            var point = CreatePoint(parameterValue);
            return source.Where(c => c.Location.IsWithinDistance(point, _fiftyMilesInMeters)).OrderBy(c => c.Location.Distance(point));
        }
    };
}

dbug: 12/9/2020 11:10:59.329 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<City>()
          .Where(c => c.Location.IsWithinDistance(
              geom: __point_0,
              distance: 80467.2))
          .OrderBy(c => c.Location.Distance(__point_0))
          .Select(city => new City{
              Name = city.Name,
              Id = city.Id
          }
          )'
dbug: 12/9/2020 11:10:59.340 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query)
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<City>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  Name -> 0
                  Id -> 1
              SELECT c.city AS Name, c.city_id AS Id
              FROM city AS c
              WHERE c.geog.STDistance(@__point_0) <= 80467.199999999997E0
              ORDER BY c.geog.STDistance(@__point_0) ASC),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, City>,
          Contexts.ApplicationContext,
          False,
          False
      )'

SELECT [c].[city] AS [Name], [c].[city_id] AS [Id]
FROM [city] AS [c]
WHERE [c].[geog].STDistance(@__point_0) <= 80467.199999999997E0
ORDER BY [c].[geog].STDistance(@__point_0)
````

One thing I noticed is that when only using `ApplyQueryLayer`, it looks like the expression does a select before applying  my distance expressions, which causes it to fail, but when applying it from `ApplyQueryLayer`, it does the select last, which allows it to be translated to sql correctly. Does that have to do with the order things are called in? When I put a breakpoint in I noticed `OnRegisterQueryableHandlersForQueryStringParameters` gets called before `ApplyQueryLayer`. I'm guessing something in `base.ApplyQueryLayer(layer)` causes the expression to work correctly if it's set before being called, but if I set it after calling `base.ApplyQueryLayer(layer)` I get the expression that won't compile.

It seems to be working correctly with the mixed solution, but I'm curious what you think. Should it be possible to have a solution using only `ApplyQueryLayer`?

**Comment by bart-degreed** [comment]
You're hitting the breakpoint in `OnRegisterQueryableHandlersForQueryStringParameters` at the time JADNC _captures_ the expression for later use, so that must have put you on the wrong track.

Based on your latest scenario, things happen in this order:
- `CitiesRepository.ApplyQueryLayer`: `layer.Sort = null`
- `base.ApplyQueryLayer`:
    - `source = this.GetAll()`: this returns the basic `IQueryable<T>` from `dbContext.DbSet<T>`
    - loop over query handlers (this is what you registered in `OnRegisterQueryableHandlersForQueryStringParameters`) and apply them on `source`
    - apply query string data and defaults (coming from `layer)` on `source`

So if you want to replace the 2nd substep, you can override GetAll() and after calling its base method, conditionally apply your custom sort as you would have done in `OnRegisterQueryableHandlersForQueryStringParameters`.

**Comment by bart-degreed** [comment]
@RKennedy9064 Are you still working on this or can this issue be closed?

**Comment by RKennedy9064** [comment]
Sorry about that, I managed to get it working, so I'll close out this issue. Thanks for all the help.

**Comment by bart-degreed** [comment]
Thanks, no problem.
