### ISSUE TITLE
Allow other content-types on controllers not derived from JsonApiController

### ISSUE THREAD

**Issue by ahmadalli** [json-api-dotnet/JsonApiDotNetCore#910]
#### DESCRIPTION

I want to be able to upload files using form-data. Apparently this was possible when #257 was authored. But now it's not possible and JADNC is forcing `application/vnd.api+json` header on all requests regardless of the controller which is serving the request.

#### STEPS TO REPRODUCE

the example on https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/257#issuecomment-380397621 now returns 415 error.

this is the output I'm getting

```json
{
    "errors": [
        {
            "id": "26c4f7a0-66b2-4b43-a69b-f6fca372f151",
            "status": "415",
            "title": "The specified Content-Type header value is not supported.",
            "detail": "Please specify 'application/vnd.api+json' instead of 'application/json' for the Content-Type header value."
        }
    ]
}
```

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.0
- ASP.NET Core version: 5.0.1
- Entity Framework Core version: 5.0.1
- Database provider: Pomelo.EntityFrameworkCore.MySql:5.0.0-alpha.2

**Comment by bart-degreed** [comment]
Hi @ahmadalli,

The json:api specification requires clients to always send request bodies with the `application/vnd.api+json` Content-Type header, see [here](https://jsonapi.org/format/1.1/#content-negotiation-all), specifically:

_"Clients and servers MUST send all JSON:API payloads using the JSON:API media type in the Content-Type header."_

Earlier versions of JsonApiDotNetCore did not implement content negotiation consistently and we fixed several bugs in that area. However, you can add controllers that do _not_ derive from `JsonApiController` or `BaseJsonApiController` in your project, which are ignored by the framework. For reference, the JsonApiDotNetCoreExample project in this repo contains such controllers (see [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/Examples/JsonApiDotNetCoreExample/Controllers/TestValuesController.cs)).

If you need more help, please post your controller code so we can analyze what is going on.

**Comment by bart-degreed** [comment]
@ahmadalli Can this be closed or are you still working on this?

**Comment by ahmadalli** [comment]
sorry my focus switch to another project. I'll try to find the differences between my project and the sample code and will provide a test project if necessary, otherwise close the issue in the next 10 days

**Comment by ahmadalli** [comment]
Unfortunately I couldn't get the time to test it again
