### ISSUE TITLE
GetRelationshipAsync returns RelationshipNotFoundException

### ISSUE THREAD

**Issue by fdlane** [json-api-dotnet/JsonApiDotNetCore#911]
#### DESCRIPTION

After upgrading to v4 we noticed that GetRelationshipAsync  now throws an exception. 

This was working...

```c#
await base.GetRelationshipAsync(id, "client-discount-details", cancellationToken);
```

Current error 

![image](https://user-images.githubusercontent.com/735646/103320544-bbbcc500-4a03-11eb-94ee-0481f32857c5.png)

Relationships seem correct.

![image](https://user-images.githubusercontent.com/735646/103320557-c37c6980-4a03-11eb-8545-16fd3536efd6.png)

The entity

![image](https://user-images.githubusercontent.com/735646/103320585-e0b13800-4a03-11eb-9047-5f7a8390ac6c.png)

TIA.

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.0
- ASP.NET Core version: 3.1
- Entity Framework Core version: 3.1.10
- Database provider: Sql Server

**Comment by bkoelman** [comment]
Based on the exception stack trace, it looks like `_request.Relationship` is null, which is set from Middleware. Do you have a custom controller in place? I'm asking because the controller method name and parameter names are used to determine routing data. Also I see that the resource property is defined both as an attribute and a relationship, which may cause problems.

If this does not help to solve the issue, can you provide some more info for us to repro?

**Comment by bkoelman** [comment]
It looks like you're passing a hardcoded relationship name "client-discount-details". This value is only used to produce the error message, as we assume it matches with the incoming HTTP request. If your goal is to fetch a relationship _different_ from the one coming from the request, you'll also need to set the `JsonApiRequest.Relationship` property. You can inject the interface and cast to overwrite the property. Get the value using `IResourceContextProvider`. Hope that helps.

**Comment by fdlane** [comment]
Bart, thank you for the help.

> Do you have a custom controller in place?

No, just typical boilerplate

> resource property is defined both as an attribute and a relationship

fixed.  Thank you

> can you provide some more info for us to repro

My use case:  **Clone an existing entity, including child records**.  

My solution was...
POST to the parent resource with an extra property named `idToClone`. 
In the Service layer, check if `idToClone` is null.  
If not null, 
  call `var entityToClone = await base.GetAsync(idToClone)` to get the entity to clone
  call `base.GetRelationshipAsync(idToClone)` to load the child records
  map values from entityToClone to new entity
  call `base.CreateAsync(entity)`

This approach worked in previous versions because all the related child records were included. 

How would you recommend that I implement cloning and entity, including child records?

**Comment by bart-degreed** [comment]
Cloning sounds like a separate concern to me that is independent from the JsonApiDotNetCore pipeline. So I would keep it simple. Just add a class that provides the clone operation, taking `DbContext` as dependency and call that from within your service.

How that can be implemented is described [here](https://www.dmcinfo.com/latest-thinking/blog/id/9953/duplicating-related-entities-using-entity-framework-core). I would first execute a LINQ query with `.Include()`s to fetch the tree in a single operation, using `AsNoTracking()` and clear out all IDs afterwards, so they are assigned on save. Then add the root object to the `DbContext` and save it.

**Comment by fdlane** [comment]
Thank you for the great input and talking me off the cliff.  We implemented the cloning as separate service.

Thank you.
