### ISSUE TITLE
Question: Overriding Identifiable.Id Property leads to error

### ISSUE THREAD

**Issue by sandreas** [json-api-dotnet/JsonApiDotNetCore#912]
Hey there, since I'm new to this framework, this is more a question than a bug... Is this behaviour intended or am I missing something?

#### DESCRIPTION

Overriding `Identifiable.Id Property` leads to error `Sequence contains more than one matching element`, because of `resourceContext.Attributes.Single` in https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e63ddf145aee9897c124c5b7c37aac973c737a52/src/JsonApiDotNetCore/Queries/Internal/QueryLayerComposer.cs#L444

#### STEPS TO REPRODUCE

Using a basic `AbstractModel` extending `Identifiable` to use the `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` 
```c#
    public abstract class AbstractModel : Identifiable<Guid>
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public new Guid Id { get; set; }
        [Attr] public DateTime CreatedDate { get; set; } = DateTime.MinValue;
        [Attr] public DateTime UpdatedDate { get; set; } = DateTime.MinValue;
    }
```

Then use a non-abstract model extending this one.

#### EXPECTED BEHAVIOR

It uses the correct Id field of the `AbstractModel`

#### ACTUAL BEHAVIOR

Error `Sequence contains more than one matching element`.

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.0
- ASP.NET Core version: 3.1.102
- Entity Framework Core version: 5.0.0
- Database provider: sqlite

**Comment by bart-degreed** [comment]
> public new Guid Id { get; set; }

In C#, this means: break the inheritance chain and add a second property with the same name. You'll want to override the existing property from base class instead, so use:
```c#
public override Guid Id { get; set; )
```

See also https://www.jsonapi.net/usage/resources/index.html

**Comment by sandreas** [comment]
> You'll want to override the existing property from base class instead

OMG thank you for taking the time to explain C# basics to me ;) Sometimes suggestions of the IDE are just not what the dev should do in this case.
