### ISSUE TITLE
Dependency on 3.1.10 of EF Core

### ISSUE THREAD

**Issue by alastairtree** [json-api-dotnet/JsonApiDotNetCore#913]
#### DESCRIPTION

Version four of Json Api dotnet as published includes a dependency on EF core >= 3.1.10. In the [code ](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/Directory.Build.props) this is actually expressed as `<EFCoreVersion>3.1.*</EFCoreVersion>` but nuget resolves as >= 3.1.10 as seen at https://www.nuget.org/packages/JsonApiDotNetCore/4.0.0

Because of a bug in [Azure Functions](https://github.com/Azure/Azure-Functions/issues/1613) (and [here](https://github.com/tntwist/NL.Serverless.AspNetCore/issues/30)) I need to lock in a downgrade to Ef Core 3.1.3 but am unable to. Can json api dotnet be published as requiring EF core >= 3.1.0 (as in source)  instead of  EF core >= 3.1.10?

**Comment by bart-degreed** [comment]
Thanks for reporting. I've published v4.0.1 ([GitHub](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v4.0.1), [NuGet](https://www.nuget.org/packages/JsonApiDotNetCore/4.0.1)), which depends on EF Core >= 3.1.0.

**Comment by alastairtree** [comment]
Amazing quick fix, thank you.
