### ISSUE TITLE
Custom middleware

### ISSUE THREAD

**Issue by PawelTomkow** [json-api-dotnet/JsonApiDotNetCore#925]
Hello,

Is it possible to add custom middleware (handling errors, prefer then filters) or create abstract for it? Also possible to add sub-middleware or change pipline of .net core request.
MS pattern: https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0

BR,
Pawel

**Comment by bart-degreed** [comment]
This is documented at https://www.jsonapi.net/usage/extensibility/middleware.html and https://www.jsonapi.net/usage/errors.html.

This library has been designed around dependency injection, making extensibility incredibly easy.
