### ISSUE TITLE
Legacy filters don’t work anymore?

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#931]
#### DESCRIPTION

Should they just work or do I need to do something to get them working? 

New style filters work but if I do something like

&filter[name]=eq:wayne

I get an error saying name isn’t a property of the resource or something.

**Comment by bart-degreed** [comment]
You need to enable it in options: https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/7b37eeb17bd777a0e4ddb37a15a1a8dbf26095ac/src/JsonApiDotNetCore/Configuration/IJsonApiOptions.cs#L150-L154

**Comment by wayne-o** [comment]
thank you - this is great because it allows me to do a phased migration to latest :)
