### ISSUE TITLE
Edit resource content with overrided controller

### ISSUE THREAD

**Issue by MehdiR-S** [json-api-dotnet/JsonApiDotNetCore#968]
#### DESCRIPTION

All informations are on the title.

#### STEPS TO REPRODUCE

1. Create entity
![image](https://user-images.githubusercontent.com/66245266/111447782-11089880-870e-11eb-913d-02409b35d45b.png)

2. Create controller with overriding
![image](https://user-images.githubusercontent.com/66245266/111446198-7196d600-870c-11eb-8479-effb7e1b21ae.png)

3. Edit resource before the base.PostAsync(resource, cancellationToken)
![image](https://user-images.githubusercontent.com/66245266/111447560-d9015580-870d-11eb-8666-dd9430735986.png)

#### EXPECTED BEHAVIOR
It should update resource with the one that I sent to the parent.
#### ACTUAL BEHAVIOR
It doesn't care about my modifications.

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.4
- ASP.NET Core version: 3.1
- Entity Framework Core version: 3.1.10
- Database provider: Postgre

**Comment by maurei** [comment]
Currently you're required to update add `ExpenseNote.UserId` and `ExpenseNote.Status` to  `ITargetedFields.Attributes`. See https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/876 and https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/934.

Closing as duplicate
