### ISSUE TITLE
How can we replace default ResponseSerializer to our CustomSerializer in JsonApiotNetCore 4.0.2 and using .NetCore 3.1

### ISSUE THREAD

**Issue by macmanishkr20** [json-api-dotnet/JsonApiDotNetCore#971]
#### DESCRIPTION

We want to use Custom serialiser apart from the newtonsoft.json which is by default in JsonApiDotNetCore 4.0.2.

#### STEPS TO REPRODUCE

using System.Text.Json;

CustomResponseSerializer<TResource> : CustomBaseSerializer : IJsonApiSerializer
{
// Business logic
}

CustomServices(this IServiceCollection services)
{
services.Replace<IJsonApiSerializer, typeof(CustomResponseSerializer<>)>(ServiceLifetime.Scoped);
}

#### EXPECTED BEHAVIOR
To inject our CustomReponseSerializer and not to use the default one in JsonApiDotNetCore 4.0.2

#### ACTUAL BEHAVIOR
Not able to do the injection of our CusromResponseSerializer .

#### VERSIONS USED
- JsonApiDotNetCore 4.0.2:
- ASP.NET Core 3.1:

**Comment by bart-degreed** [comment]
This is currently not possible. We have an [open issue](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/664) for that. Closing as duplicate.

**Comment by maurei** [comment]
I am not sure if only your goal is to replace `Newtonsoft.Json` with  `System.Text.Json`. In case you have other motivations: you shouldn't register `IJsonApiSerializer` but `IJsonApiSerializerFactory` instead:

```
services.AddScoped<IJsonApiSerializerFactory, CustomResponseSerializerFactory>();
```

See https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Serialization/ResponseSerializerFactory.cs.
