### ISSUE TITLE
Relationship on same table error

### ISSUE THREAD

**Issue by MehdiR-S** [json-api-dotnet/JsonApiDotNetCore#974]
#### DESCRIPTION
Hello
I don't know if I have to post this here or to post on angular2-jsonapi issues, so I did it twice ( one here, and one on the angular package's github )
I have a new problem with JsonApi when I want to findAllelements from my front-end.

#### STEPS TO REPRODUCE

My Model (Back-end) :
https://pastebin.pl/view/0806c9d1

My Frond-End (angular2-jsonapi) :
=> Request
![image](https://user-images.githubusercontent.com/66245266/111814120-64c7dd00-88da-11eb-8df3-2320434f1935.png)
=> Model
https://pastebin.pl/view/e661ac2b

Error : 
![image](https://user-images.githubusercontent.com/66245266/111814548-e455ac00-88da-11eb-8258-afc7966cc8ad.png)

Request response : 
https://pastebin.pl/view/8855ceea

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.4
- ASP.NET Core version: 3.1
- Entity Framework Core version: 3.1.10
- Database provider: Postgre
- Angular version : 10
- angular2-jsonapi version : 8.2.1

**Comment by maurei** [comment]
JsonApiDotNetCore is not affiliated with angular2-jsonapi, but as long as the response from JADNC is compliant with the json:api specification, angular2-jsonapi should be able to deal with it. Looking into your back-end model and response dump, I see nothing strange on our end. 

Perhaps angular2-jsonapi does not deal very well with cyclic relationships (nature has many natures)? 

I'm willing to dig into it a bit deeper if you can set up a repo with a minimal reproduction scenario.

**Comment by MehdiR-S** [comment]
On the response I seen that on the include, there is a type: "natures", and that's not "parent" or "children" as the property method
So on my front with angular2-jsonapi, I added the property "natures" and it worked, but I don't know if it works very well, I have to do some tests

**Comment by maurei** [comment]
Great, feel free to nudge me if you do want to look into something.
