### ISSUE TITLE
Creating a resource with a relationship

### ISSUE THREAD

**Issue by rsmith8917** [json-api-dotnet/JsonApiDotNetCore#979]
#### DESCRIPTION

When trying to create a resource with a relationship, the resource is created but it appears that the relationship is not. For example, in the Getting Started project creating a book with a person set as the author relationship results in a book created with the AuthorId set to NULL.

#### STEPS TO REPRODUCE

1. Run Getting Started Project
2. HTTP POST to /api/books
Body:
```
{
    "data": {
        "type": "books",
        "attributes": {
                "title": "New Book",
                "publishYear": 2021
        }
    },
    "relationships": {
        "author": {
            "data": {
                "type": "people",
                "id": "1"
            }
        }
    }
}
```

#### EXPECTED BEHAVIOR
A Book resource is created with the AuthorId set to 1 (Mary Shelley)

#### ACTUAL BEHAVIOR
A Book resource is created with the AuthorId set to NULL

![image](https://user-images.githubusercontent.com/8465053/115743708-e7234100-a35f-11eb-817a-968c7a134591.png)

#### VERSIONS USED
- JsonApiDotNetCore version: 4.1.1
- ASP.NET Core version: 5.0.103
- Entity Framework Core version: 3.1.0
- Database provider: Microsoft.EntityFrameworkCore.Sqlite

**Comment by bart-degreed** [comment]
As described [here](https://jsonapi.org/format/1.1/#crud-creating), you need to put the `relationships` element inside `data`.

**Comment by bart-degreed** [comment]
These may help too: https://www.jsonapi.net/request-examples/index.html

They are generated as part of our build process, so guaranteed to be up-to-date and working.

**Comment by rsmith8917** [comment]
Ah, I see. My mistake, thanks for clarifying!
