### ISSUE TITLE
Any way to use Entity Framework (.NET Framework) with JsonApiDotNetCore?

### ISSUE THREAD

**Issue by gordsmash** [json-api-dotnet/JsonApiDotNetCore#983]
I'm having trouble finding a resource that goes over using Entity Framework 6 with JsonApiDotNetCore. I see most (if not all) of the examples using the Entity Framework Core. So is it possible to use Entity Framework 6 with this package? Or, is it only possible to use the EF Core with it?

If it is possible to use EF 6, can you please link to an example of where it has been implemented successfully?

Thank you.

**Comment by bart-degreed** [comment]
Sorry, JsonApiDotNetCore has no built-in support for Entity Framework 6. And I'm not aware of anyone that has tried to implement that.

Up until recent versions, Entity Framework used to require the full .NET framework, while JsonApiDotNetCore has always required .NET Core.
